### ISSUE TITLE
Calling Toothpick.inject in a class with no dependencies

### ISSUE THREAD

**Issue by dlemures** [stephanenicolas/toothpick#101]
Should we crash? Or simple do nothing?
For example, common top class that always call it.

Right now:
```java
throw new RuntimeException
```

**Comment by dlemures** [comment]
Didn't we support this case?

**Comment by dlemures** [comment]
https://github.com/stephanenicolas/toothpick/pull/102

**Comment by stephanenicolas** [comment]
RTM

**Comment by dlemures** [comment]
Merged
