### ISSUE TITLE
Scope annotations + Bindings

### ISSUE THREAD

**Issue by dlemures** [stephanenicolas/toothpick#104]
We don't allow to bind implementations which contain "scope annotations".

For instance, the following is forbidden:
```java
interface A {
    ...
}

@Singleton
class B implements A {
    ...
}

class XModule extends Module {
    public ModuleWithNamedBindings() {
        bind(A.class).to(B.class);
    }
}
```

However, it seems a valid use case...

Should we allow it?

However, not all cases are valid (that's why it is not allowed right now)...

**Comment by stephanenicolas** [comment]
The problem with this example is where the `XModule` is gonna be used.. 
Outside of the root scope, it doesn't make any sense. 

To verify this, we would have to get the factory (or use reflection) to determine if the targets of bindings are annotated with a scope annotation that matches the scope supported annotations. It would also imply  that the scope annotation knows about its scope annotations before installing modules, which is quite a constraint and prevents dynamic scope annotation bindings to scopes.

I think I would prefer to consider this as a limitation of TP. The price to pay would actually be high to check this, even in a configuration.

An easy workaround is to instantiate the scoped instances in the module: 
```java
class XModule extends Module {
    public ModuleWithNamedBindings() {
        bind(A.class).toInstance(new B());
    }
}
```

**Comment by dlemures** [comment]
Yes, it will only make sense if the  _Scope annotation_ is attached to one of the parent scopes.

As you said, the verification would be really expensive.

So a work around would be to define a provider for B:
```java
class XModule extends Module {
    public ModuleWithNamedBindings() {
        bind(A.class).toProvider(BProvider.class);
    }
}

class BProvider  implements Provider<B> {
  B b;

  @Inject
  public BProvider(B b) {
    this.b = b;
  }

  @Override
  public B get() {
    return b;
  }
}
```

closing

**Comment by aartikov** [comment]
@dlemures 
@stephanenicolas 
Hi. There are any changes with this issue?
I am trying this code.

```
@javax.inject.Scope
@Retention(RUNTIME)
@interface MyScope {}

interface IFoo {
	String getHash();
}

@MyScope
class Foo implements IFoo {
	@Inject
	Foo() {}

	public String getHash() {
		return Integer.toString(hashCode());
	}
}

void test() {
	Scope scope = Toothpick.openScopes("root", "scope");
	scope.installModules(new Module() {{
		bind(IFoo.class).to(Foo.class);
	}});
	scope.bindScopeAnnotation(MyScope.class);

	IFoo foo1 = scope.getInstance(IFoo.class);
	IFoo foo2 = scope.getInstance(IFoo.class);
	Log.d("MY_TAG", "foo1: " + foo1.getHash());
	Log.d("MY_TAG", "foo2: " + foo2.getHash());
}
```

It prints that foo1 and foo2 are the same instance. But the strange thing is that it still works even if I remove `bindScopeAnnotation` statement. So, there are no scope verification in this case.
