### ISSUE TITLE
Stubs for testing

### ISSUE THREAD

**Issue by dlemures** [stephanenicolas/toothpick#105]
Use case:
We want to inject a Stub inside the ToothPickTestModule in a "nice way".
If we use @Mock from the mocking library, the mock is created by it.

Possible solutions:
* Create annotation @Stub. Any field that contains that annotation will be bound but not injected by the mocking library.
* Create TP own @Mock annotation, we wouldn't need to change more code. It could we be used when want the object to be bound inside the ToothPickTestModule but it won't be recognized by the mocking library.

**Comment by stephanenicolas** [comment]
the easier way is to create the stub and to bind it via a module in the test. Everything is here already for this.
