### ISSUE TITLE
Smoothie Example App Clarify Registry Classes

### ISSUE THREAD

**Issue by eygraber** [stephanenicolas/toothpick#106]
Is it just me, or do the `com.example.smoothie.MemberInjectorRegistry` and `com.example.smoothie.FactoryRegistry` classes in [SimpleApp](https://github.com/stephanenicolas/toothpick/blob/7942548ca4d5a49fa01172b98c92b3e00eec204b/smoothie-sample/src/main/java/com/example/smoothie/SimpleApp.java) not exist?

**Comment by eygraber** [comment]
I understand now. Maybe there should be a comment explaining what those classes are, with a link to the wiki page for setting up registries.

**Comment by dlemures** [comment]
Good idea.
You want to submit a PR @eygraber ?

**Comment by eygraber** [comment]
@dlemures Once I'm doing this, should `Configuration.setConfiguration(Configuration.reflectionFree())` be called? Is there a point to setting the root registries if reflection is going to be used?
