### ISSUE TITLE
Factory Created for Non-Injected Class

### ISSUE THREAD

**Issue by eygraber** [stephanenicolas/toothpick#107]
I have a class `MainActivity` (which is an `Activity`). It has injected members, but it itself is never injected anywhere, yet in the generated code there is a `Factory` implementation for it:

```java
public final class MainActivity$$Factory implements Factory<MainActivity> {
  private MemberInjector<MainActivity> memberInjector = new com.staticbloc.location.mock.activity.MainActivity$$MemberInjector();

  @Override
  public MainActivity createInstance(Scope scope) {
    scope = getTargetScope(scope);
    MainActivity mainActivity = new MainActivity();
    memberInjector.inject(mainActivity, scope);
    return mainActivity;
  }

  @Override
  public Scope getTargetScope(Scope scope) {
    return scope;
  }

  @Override
  public boolean hasScopeAnnotation() {
    return false;
  }

  @Override
  public boolean hasScopeInstancesAnnotation() {
    return false;
  }
}
```

This also happens when using a `FactoryRegistry`:

```java
public final class FactoryRegistry extends AbstractFactoryRegistry {
  public FactoryRegistry() {
    addChildRegistry(new toothpick.smoothie.FactoryRegistry());
  }

  public <T> Factory<T> getFactory(Class<T> clazz) {
    switch(clazz.getName().replace('$','.')) {
      case ("com.staticbloc.location.mock.activity.MainActivity"):
      return (Factory<T>) new com.staticbloc.location.mock.activity.MainActivity$$Factory();
      default:
      return getFactoryInChildrenRegistries(clazz);
    }
  }
}
```

**Comment by dlemures** [comment]
Hi @eygraber ,

We generate factories and member injectors at compile time. So the injection (at runtime) is much faster and reflection free. As opposed to compile-time DI libraries, Toothpick bindings are defined at runtime. Thus, Toothpick cannot know at compilation time wether or not a class will actually be instantiated via DI.

By the way, `MainActivity$$Factory` is an optimistic factory: as `MainActivity` has injected member.

Please have a look at [optimistic factories](https://github.com/stephanenicolas/toothpick/wiki/Factories-and-Member-Injectors#optimistic-factory-creation)

**Comment by dlemures** [comment]
In case you want to have more control over it, but less flexibility, we can talk about:

> You can turn off optimistic factory creation using Toothpick annotation processor options. We didn't provide a flag to turn off optimistic factory creation per say, and this could make sense as it will lead to a significant increase in the number of generated classes. Please, fill an issue or even better submit a PR if such feature happens to be needed in your case.

**Comment by eygraber** [comment]
So as I understand it, optimistic factories provide the ability to have `@Inject` fields in a class that does not have an `@Inject` constructor?

What do you think about an annotation processor "strict mode" that only creates factories for classes that have an `@Inject` constructor or a scope annotation? That way a class can only be injected if it has an annotated constructor, has a scope annotation, or if it is bound.

**Comment by dlemures** [comment]
Moreless, imaging the following code:
```java
public class A {
    @Inject B;
}
```

_A_ does not have a constructor annotated with @Inject, so the user should not be able to inject A as a dependency, as we are not creating a factory for it. For example this would not work:
```java
public class C {
    @Inject A; // A does not have a @Inject annotated constructor, so it cannot be built by TP
}
```

So the following will solve the issue:
```java
public class A {
    @Inject B;

    @Inject
    public A() {
    }
}
```

But, why should the user add a constructor just to let TP know that we need a factory for this class? Normally, all classes with @Inject annotated fields, will be injected as well, so they could need a factory. 

This is the idea behind the optimistic factory creation. Having a @Inject annotated fields inside a class is enough to say TP: hey, this class needs a factory because It will probably be injected.

Pros:
* Saving code to the user

Cons:
* Generating extra factories (not needed for injection graph roots) -> generating extra methods

**Comment by dlemures** [comment]
Regarding the "strict mode", ideally a annotation processor option would be a good solution. What do you think?

From the wiki:
> You can turn off optimistic factory creation using Toothpick annotation processor options. We didn't provide a flag to turn off optimistic factory creation per say, and this could make sense as it will lead to a significant increase in the number of generated classes. Please, fill an issue or even better submit a PR if such feature happens to be needed in your case.

**Comment by eygraber** [comment]
That's what I was thinking for "strict mode". Have an annotation processor option that only creates factories for classes that have an `@Inject` constructor or an annotation scope. That way users who are worried about the unused factories can just enable that option, and make sure their injected classes are annotated correctly. Would you be open to something like that?

**Comment by stephanenicolas** [comment]
Update: TP doesn't use optimistic factories any more. This concept is now dead as it created weir compilation cycles and duplicate factories.

To create a factory for a class C, we just rely on the fact that there is an annotated constructor or members or methods. If there is an annotated constructor, it will be used by the factory. A factory is also produced in case there is only a default constructor (i.e. either an explicit one and it's the only one, or no constructors at all). 

We could add an option to avoid generating factories for classes that don't have an explicit inject  annotated constructor. It would require a few changes to the way we handle constructors, but it would be possible to have this strict mode. 

Feel free to submit a PR, on our side we don't really need this option and won't work on this. But a PR would make it in if you anyone submits one.
