### ISSUE TITLE
Use Smoothie to Demo Registry Setup for Dependencies that Use Toothpick

### ISSUE THREAD

**Issue by eygraber** [stephanenicolas/toothpick#108]
[The example](https://github.com/stephanenicolas/toothpick/wiki/Factory-and-Member-Injector-registries#example--application-with-3-librairies) showing how to setup registries when the app depends on libraries that use Toothpick could probably be improved by presenting the setup for an app that uses smoothie.

**Comment by dlemures** [comment]
I agree. @eygraber thx

**Comment by stephanenicolas** [comment]
This is done already, no ?

**Comment by stephanenicolas** [comment]
@eygraber , you are gonna finish RC10 development tomorrow, and will probably release. With no update from you, we will then close this issue.

**Comment by eygraber** [comment]
@stephanenicolas this is not done yet. The wiki still doesn't use a concrete example. Since it's wiki based I would say it shouldn't need to be tied to a release cycle though. 

I'm pretty swamped now so I can't make the changes right now.

**Comment by stephanenicolas** [comment]
We close the issue as we don't really understand how a compilation unit using smoothie would be impacted in its registries setup. Feel free to reopen or submit a PR on the wiki if there is something we can improve there.
