### ISSUE TITLE
Wiki Incorrect Arguments for Registry Setup

### ISSUE THREAD

**Issue by eygraber** [stephanenicolas/toothpick#109]
[The wiki page for factory and member injector setup](https://github.com/stephanenicolas/toothpick/wiki/Factory-and-Member-Injector-registries#example--application-with-3-librairies) incorrectly passes a `FactoryRegistry` to `MemberInjectorRegistryLocator.setRootRegistry`

**Comment by dlemures** [comment]
Fixed! thx @eygraber
