### ISSUE TITLE
Compilation warning for all graph roots

### ISSUE THREAD

**Issue by dlemures** [stephanenicolas/toothpick#110]
As graph roots don't need to be injected, they don't need a factory, thus an empty constructor is not needed (for android: activities, fragments, views, ...).

We display several compilation warnings that make it difficult to see real problems or warning:
```
.../../DealListItemView.java:32: warning: 
The class ....DealListItemView has injected fields but has no injected constructor, 
and no public default constructor. Toothpick can't create a factory for it.
public class DealListItemView extends RelativeLayout {
```

**Comment by stephanenicolas** [comment]
Yeah, but isn't this the price to pay to make it easier to create in-graph dependencies ? 
I mean, TP creates a factory as soon as we use field injections (or `@Singleton`), and it cannot know that a class is an entry point. 

I would close the issue.

**Comment by dlemures** [comment]
Then, are those warnings useful? 
Could we remove them?

**Comment by stephanenicolas** [comment]
We should introduce an annotation processor argument to remove the warnings. It should support regular expressions, be documented in the wiki + tests.

**Comment by stephanenicolas** [comment]
Also, we could support the SuppressWarnings annotation of the JDK. If it contains the string `TOOTHPICK_NO_FACTORY` then we don't issue the warning. This seems clean.

**Comment by dlemures** [comment]
https://github.com/stephanenicolas/toothpick/pull/152

**Comment by dlemures** [comment]
https://github.com/stephanenicolas/toothpick/wiki/Suppressing-compilation-warnings
