### ISSUE TITLE
Unused local variable inside Factories

### ISSUE THREAD

**Issue by dlemures** [stephanenicolas/toothpick#111]
Unused local variable inside Factories that can make CI findbug hooks complain:

```java
public AndroidAccountIntents createInstance(Scope scope) {
     scope = getTargetScope(scope);
     AndroidAccountIntents androidAccountIntents = new AndroidAccountIntents();
     return androidAccountIntents;
}
```

Only happens when scope is not used. Can we avoid that?

**Comment by dpreussler** [comment]
for documentation: this is how to suppress for now: 

    <Match>
        
        <Class name="~.*\$\$Factory" />
        <Bug pattern="DLS_DEAD_LOCAL_STORE" />
    </Match>

**Comment by stephanenicolas** [comment]
Thx for the workaround @dpreussler, but we are gonna fix this.

**Comment by stephanenicolas** [comment]
Will be part of RC10
