### ISSUE TITLE
Does not work with Java7

### ISSUE THREAD

**Issue by dpreussler** [stephanenicolas/toothpick#112]
when using JDK 7 (tested with "1.7.0_51", "1.7.0_80")
the apk build does not contain classes, when starting:

java.lang.RuntimeException: Unable to instantiate application com.groupon.merchant.MerchantApplication: java.lang.ClassNotFoundException: Didn't find class "com.groupon.merchant.MerchantApplication" on path: DexPathList[[zip file "/data/app/com.groupon.redemption-1/base.apk"],nativeLibraryDirectories=[/data/app/com.groupon.redemption-1/lib/x86, /vendor/lib, /system/lib]]

**Comment by dlemures** [comment]
https://github.com/stephanenicolas/toothpick/pull/115 😑
