### ISSUE TITLE
Question: Runtime Discovery of Unbound Class Performance

### ISSUE THREAD

**Issue by eygraber** [stephanenicolas/toothpick#113]
Is there a significant performance gain to binding classes? For example, should I bind the following dependency (as opposed to just letting it get discovered at runtime), for performance purposes? 

```java
@ContextSingleton
public class MaterialDialogBuilderFactory {
  private final Activity activity;

  @Inject
  public MaterialDialogBuilderFactory(Activity activity) {
    this.activity = activity;
  }

  public MaterialDialog.Builder get() {
    return new MaterialDialog.Builder(activity);
  }
}
```

**Comment by dlemures** [comment]
Hi @eygraber ,
There is no performance gain. 
At compile time we generate some code, so they are exactly the same case.

Bindings are used to change the way TP injects instances: reuse instances, inject B instance when the dependency is A....

**Comment by eygraber** [comment]
So this comment in `ScopeImpl.lookupProvider`means it's relatively slow, not performance slow?

```
 // classes discovered at runtime, not bound by any module
 // they will be a bit slower as we need to get the factory first
```

**Comment by dlemures** [comment]
At that stage of the method, the type has not been injected before, so the factory needs to be found the first time, then we cache it. That is what that means.

Types bound through a module, will look for their factories on first injection as well.
