### ISSUE TITLE
No Factory for Class with Scope Annotation and No @Inject

### ISSUE THREAD

**Issue by eygraber** [stephanenicolas/toothpick#116]
I have a class:

```java
@ActivitySingleton
public class MapFragmentProvider implements Provider<SupportMapFragment> {
  @Override
  public SupportMapFragment get() {
    return SupportMapFragment.newInstance();
  }
}
```

Where `ActivitySingleton` is:

```java
@Scope
@Documented
@Retention(RUNTIME)
public @interface ActivitySingleton {
}
```

But no `Factory` is being created for it unless I add an `@Inject` constructor.

**Comment by stephanenicolas** [comment]
This is a duplicate of https://github.com/stephanenicolas/toothpick/issues/118. Thx @eygraber . I don't exactly see how we are gonna solve that, we might need some research work on it...
