### ISSUE TITLE
Is there any way to inject a generic type?

### ISSUE THREAD

**Issue by mheras** [stephanenicolas/toothpick#122]
I know the documentation says that this is not supported, but I'm wondering if there is any workaround to simulate this. I cannot find any DI solution for Android that supports injecting a generic type like this:

    public class MyActivity<P extends BasePresenter> extends Activity {
        @Inject
        P presenter;
    }

Thank you!

**Comment by stephanenicolas** [comment]
No, this is not supported by Toothpick. But it would work with a subclass
of MyActivity. We need a "real"/resolved class to perform injection.

2016-07-12 19:29 GMT-07:00 Martin Heras <notifications@github.com>:

**Comment by afaucogney** [comment]
@stephanenicolas could you please extend your explanation. I assume you can @inject the filed as soon its type is contrait, however how could I work with the injected field at abstract level ?

```
public class TheActivity extends MyActivity<ThePresenter> {
    @Inject
    ThePresenter presenter;
}
```

What to do here to handle stuff with the presenter inject in the concrete activity

```
public class MyActivity<P extends BasePresenter> extends Activity {
    @Inject
    P presenter;

   @Override
   onResume(){
    presenter.start();
  }
}
```
