### ISSUE TITLE
Bug in wiki

### ISSUE THREAD

**Issue by tomaszpolanski** [stephanenicolas/toothpick#126]
Trying out toothpick and it looks really promising!

I stumbled on a issue in wiki in [Setting up bindings in a scope](https://github.com/stephanenicolas/toothpick/wiki/Modules-&-Bindings#setting-up-bindings-in-a-scope):

Instead of ``bind(IFoo.class).to(new Foo());``, it should be ``bind(IFoo.class).toInstance(new Foo());``

Keep on doing the good work!

**Comment by stephanenicolas** [comment]
Thx. We still disagree between to overloads and toInstance in the team :)

What is your opinion about the naming @Tomasz Polanski ?

Thx for the kind words. But yeah, TP works. We have ported 2 apps and they
work super fast, even faster than dagger 1 for 2.5k injections.. We are
really quite happy ;)


2016-07-20 12:23 GMT-07:00 Tomasz Polański <notifications@github.com>:

**Comment by tomaszpolanski** [comment]
Ahhh the issue with naming things :).
I would be leaning towards ``toInstance`` but both would perfectly work for me as long the documentation is consistent :).

Waiting for 1.0 version with anticipation!

**Comment by stephanenicolas** [comment]
fixed. Thx.
