### ISSUE TITLE
Rename smoothie subproject to toothpick-android

### ISSUE THREAD

**Issue by saguinav** [stephanenicolas/toothpick#128]
Following the same naming convention as the other subprojects:
- toothpick-compiler
- toothpick-runtime
- ...

Also consider removing the prefix "Smoothie" form Android specific Modules.

**Comment by dlemures** [comment]
It will be more clear...

**Comment by dlemures** [comment]
@stephanenicolas WDYT?
I like the idea.

**Comment by stephanenicolas** [comment]
We would gladly accept a PR.. I mark it as won't fix as neither @dlemures nor I would fix it, but a PR would make it in...
