### ISSUE TITLE
Android util openScopes methods

### ISSUE THREAD

**Issue by saguinav** [stephanenicolas/toothpick#129]
For Android applications ToothPick will be commonly used in Activities and Fragments in the following way:

**SampleActivity.java**
```java
public class SampleActivity extends Activity {

   @Inject ContextNamer contextNamer;

   @Override
   protected void onCreate(Bundle savedInstanceState) {
      scope = Toothpick.openScopes(getApplication(), this);
      scope.installModules(new SmoothieActivityModule(this));
      super.onCreate(savedInstanceState);
      Toothpick.inject(this, scope);

      // ... do something
   }

   // ... more stuff

   @Override
   protected void onDestroy() {
      Toothpick.closeScope(this);
      super.onDestroy();
   }

   // ... more stuff
}
```

**SampleFragment.java*
```java
public class SampleFragment extends Fragment {

   @Inject ContextNamer contextNamer;

   @Override
   public void onCreate(Bundle savedInstanceState) {
      scope = Toothpick.openScopes(getActivity().getApplication(), getActivity(), this);
      scope.installModules(new SmoothieFragmentModule(this));
      super.onCreate(savedInstanceState);
      Toothpick.inject(this, scope);

      // ... do something
   }

   // ... more stuff

   @Override
   protected void onDestroy() {
      Toothpick.closeScope(this);
      super.onDestroy();
   }

   // ... more stuff
}
```

I have noticed that these two calls will be a constant in every project that uses TP:

```java
// Activity
scope = Toothpick.openScopes(getApplication(), this);
// Fragment
scope = Toothpick.openScopes(getActivity().getApplication(), getActivity(), this);
```

Would it make sense to have a util ToothPick class for Android that masks this? For instance:

```java
public class ToothpickAndroidUtils {

   public static Scope openActivityScope(Activity activity) {
      final Scope scope = Toothpick.openScopes(activity.getApplication(), activity);
      scope.installModules(new SmoothieActivityModule(activity));
      return scope;
   }

   public static Scope openActivityScope(Activity activity, Object... names) {
      final Scope scope = Toothpick.openScopes(activity.getApplication(), activity, names);
      scope.installModules(new SmoothieActivityModule(activity));
      return scope;
   }

   public static Scope openFragmentScope(Fragment fragment) {
      final Scope scope = Toothpick.openScopes(fragment.getActivity().getApplication(), fragment.getActivity(), fragment);
      scope.installModules(new SmoothieFragmentModule(fragment));
      return scope;
   }

   public static Scope openFragmentScope(Fragment fragment, Object... names) {
      final Scope scope = Toothpick.openScopes(fragment.getActivity().getApplication(), fragment.getActivity(), fragment, names);
      scope.installModules(new SmoothieFragmentModule(fragment));
      return scope;
   }
}
```

**Comment by dlemures** [comment]
I think it can be a good idea to have these shortcuts for android, as it will be the main usage (no intermediate scopes).

I'm not sure if we should install the smoothie modules by default.

One open question: will this change encourage users not to use nice scope features as presenter or flow scopes?

**Comment by stephanenicolas** [comment]
also in the overload using `names` I think the compiler will badly interpret the varargs and use the array as an object.

**Comment by stephanenicolas** [comment]
@dlemures @saguinav this could go in the smoothie project. But as @dlemures said, it will be for apps that want a not-so refined injection (no intermediary scopes). There could be 1 example of it, but not all examples should be using it to show the more general & flexible way to open scopes. Not so sure of the real gain here. Moreover, devs would generally do it once per project in base classes.

**Comment by saguinav** [comment]
The code written in the description is just a draft of the proposal. So don't take names, syntax or any other stuff into consideration.

**Comment by Macarse** [comment]
👎 I don't see it very useful. 
You can add this to your base activity/fragment if you think is useful for you.

**Comment by stephanenicolas** [comment]
We're kind of average open to this idea. @saguinav if you still think it's worth it, please push a PR.
Closing the issue as there is no followup.
