### ISSUE TITLE
Gradle Error Toothpick and Toothpick Parent Point to the Same Directory

### ISSUE THREAD

**Issue by eygraber** [stephanenicolas/toothpick#131]
When doing a Gradle sync the following error is produced. It doesn't seem to prevent building and compilation though.

> Error:The modules 'toothpick', 'toothpick-parent' point to same directory in the file system.
Each module has to have a unique path.

**Comment by stephanenicolas** [comment]
That is super weird. Can we get more details. We don't see that at all in IntelliJ.
