### ISSUE TITLE
Scope annotations on binding targets is allowed or not, depending on configuration

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#133]
We need to investigate this: 

reflection free config accepts provider/implementation to be scoped, but reflection config does not.
the former would accept to scope via an annotation a provider/implementation and bind it, the second does not.

**Comment by dlemures** [comment]
Reflection free does not use runtime checks, development does include checks.

**Comment by dlemures** [comment]
Configuration refactored. Closing
