### ISSUE TITLE
[Documentation] Toothpick must have one @inject annotation to generate Factory and Member Injectors

### ISSUE THREAD

**Issue by philipbjorge** [stephanenicolas/toothpick#145]
Could you update the docs here to note that you need at least one `@javax.inject.Inject`, `javax.inject.Singleton`, or `toothpick.ScopeInstances` for the injectors to be generated?
I burnt a bit of time last night during initial setup where I was faced with `warning: The following options were not recognized by any processor: '[toothpick_registry_package_name]'` errors and no classes until I had an `@Inject` annotation.

https://github.com/stephanenicolas/toothpick/wiki/Factory-and-Member-Injector-registries

Thanks (let me know if this is PR'able and I can update the docs?)

**Comment by stephanenicolas** [comment]
what do you mean by 

     injectors to be generated?

**Comment by stephanenicolas** [comment]
@philipbjorge I close the issue as there is no followup
