### ISSUE TITLE
NoFactoryFoundException when using toInstance

### ISSUE THREAD

**Issue by wongcain** [stephanenicolas/toothpick#147]
After switching to reflectionDisabled configuration, I am no longer able to inject classes that do not have @Inject annotated constructors or methods, even I am instantiating the classes directly in the module.  Specifically I am trying to inject a Retrofit implementation like this:
bind(GiphyApi.class).toInstance(retrofit.create(GiphyApi.class));

Since Retrofit creates this class, I cannot add @Inject into its implementation. However, I don't see why I should have to, as I am providing the instance myself.  This will be a problem for injecting any 3rd party library.  Enabling reflection gets rid of this problem, but I'd prefer to disable it to get the performance gains.  Please advise.

**Comment by dlemures** [comment]
Hi @wongcain ,

That should work.

Could you show how you install the Modules and the Scopes?

**Comment by wongcain** [comment]
Hmm... it may be because I am doing something unconventional. I opened this issue previously:  https://github.com/stephanenicolas/toothpick/issues/143  What I wanted to do is be able to instantiate a Module that itself receives injections.  So I have a parent module that defines an OkHttp instance, and then a child module that gets this instance injected in it and uses it to instantiate a Retrofit instance.  Using the reflection configuration this works, but then it breaks if I switch to the reflectionDisabled configuration.

Here's what I am doing...
I have an App Module like this
```
    public class AppModule extends Module {

        public AppModule(Application app) {
            HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
            interceptor.setLevel(BuildConfig.DEBUG ? HttpLoggingInterceptor.Level.BODY : HttpLoggingInterceptor.Level.NONE);
            OkHttpClient client = new OkHttpClient.Builder().addInterceptor(interceptor).build();
            bind(OkHttpClient.class).toInstance(client);

            final Gson gson = new GsonBuilder()
                    .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
                    .create();
            bind(Gson.class).toInstance(gson);
        }

    }
```

I load the module using the application context like this:
```
Scope scope = Toothpick.openScopes(mAppContext);
scope.installModules(new AppModule(mApp);
```

Then, elsewhere I have another module:
```
public class GiphyModule extends Module {
    @Inject
    public GiphyModule(Gson gson, OkHttpClient okHttpClient) {
        final Retrofit retrofit = new Retrofit.Builder().baseUrl("http://api.giphy.com")
                .client(okHttpClient)
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .addConverterFactory(GsonConverterFactory.create(gson))
                .build();
        bind(GiphyApi.class).toInstance(retrofit.create(GiphyApi.class));
    }
}
```
As you can see this module requires that the Gson and OkHttpClient are injected.  So, rather than instantiate the module directly I do this:
```
Scope appScope = Toothpick.openScopes(mAppContext);
GiphyModule giphyModule = appScope.getInstance(GiphyModule.class);
Scope thisScope = Toothpick.openScopes(mAppContext, this);
thisScope.installModules(giphyModule);
```

Like I said, it works fine as long as reflection is enabled, but complains about GiphyApi not having an @Inject annotation when I try to use reflectionDisabled.

**Comment by dlemures** [comment]
Just to confirm. 
You are using `thisScope` to inject `GiphyApi` as a dependency. Aren't you?

**Comment by wongcain** [comment]
>> You are using thisScope to inject GiphyApi as a dependency. Aren't you?
Correct.

>> Is there any singleton involved in the process of injecting GiphyApi (injection graph)?
I do have a couple of @Singleton annotated dependencies. But neither of them are related to GiphyApi.

**Comment by dlemures** [comment]
@wongcain sorry for the delay.

Could you provide the injection path that fails?

For instance:
`A (root) -> B -> C -> GiphyApi`

Are any of the dependencies inside that path annotated with scope annotations (for example `@Singleton`)?

**Comment by stephanenicolas** [comment]
Can you give a stack trace ?

**Comment by stephanenicolas** [comment]
It looks like there is no binding Giphy --> something is not defined, this cannot be related to changing the runtime configuration. Do you get any other error ?

**Comment by stephanenicolas** [comment]
@wongcain we close the issue as there is no followup.
