### ISSUE TITLE
Closing a scope from multiple locations

### ISSUE THREAD

**Issue by james5567** [stephanenicolas/toothpick#151]
How would one close a scope when it is being simultaneously accessed from multiple locations? For example in Android if you wan't to share a scope between two activities:

         Shared Scope
          /        \
         /          \
    Activity 1    Activity 2

And you wan't to close it when both the activities are destroyed i.e after both of their `onDestroy` are called. Where exactly will you call `Toothpick.closeScope(SharedScope.class)` here?

**Comment by stephanenicolas** [comment]
You have to call close when your scope is actually closing.. :) 

In the case of a scope spanning multiple activities, you have to close the scope when the user leaves this flow: 
* activity 1 on back key pressed or navigation up
* activity 2 starting an activity outside the flow.
* (if activity 1 can also start an activity outside the flow, i.e. an activity that is NOT activity 2, then you have to close the scope as well).

There is no way for TP to know which activities are grouped together in the flow and no way it can handle that for you.

**Comment by james5567** [comment]
Thanks a lot for the explanation!

But what if the scope is spanning an activity and a service and the order of them closing is undetermined?
One possible solution could be TP only closes a scope when `closeScope` has been called exact number of times `openScope` has been called?

If `openScope` was called 3 times `closeScope` should be called 3 times for it to close.
