### ISSUE TITLE
Remove warnings about last round when generating code.

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#158]
We finally decided to remove this warning. It will mean that no annotation processor will be able to generate code that will be processed by TP annotation processors, but we are not aware of any library doing so... So, it's not really a problem.

See #85

**Comment by dlemures** [comment]
Warning removed: https://github.com/stephanenicolas/toothpick/pull/159

We are processing now all the annotations during the first round.
