### ISSUE TITLE
Scope annotations must have Runtime Retention

### ISSUE THREAD

**Issue by dlemures** [stephanenicolas/toothpick#161]
Scope annotations defined by the user must have Runtime Retention (same as @Singleton does).
Otherwise, the runtime checks won't work for those annotation.

Should we force it? 
Crash the compiler if any does not have the right retention.

**Comment by stephanenicolas** [comment]
I think it would be a good practice to enforce. Though there is an issue with annotation with runtime retention : all classes using the annotation will be kept in first dex...

**Comment by stephanenicolas** [comment]
We should just fail, the first dex would not be impacted much.

**Comment by dlemures** [comment]
We will fail at compile time if it does not contain the right retention.

**Comment by dlemures** [comment]
PR: https://github.com/stephanenicolas/toothpick/pull/191

**Comment by dlemures** [comment]
WIKI updated: https://github.com/stephanenicolas/toothpick/wiki/Scope-Annotations#custom-scope-annotations

**Comment by dlemures** [comment]
PR merged.
