### ISSUE TITLE
change bind --> support for scope annotation 

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#169]
Vocabulary change: a scope will support a scope annotation. Using the word "binding" is ambiguous.

* [ ] change the code
* [ ] change the wiki

**Comment by lrn2prgrm** [comment]
I don't think it could be TP2, unless there is more breaking change features with new features. If that's not the case I would think about TP 1.1.0

**Comment by stephanenicolas** [comment]
Semantic versioning requires a major version change in case an API is
broken: http://semver.org/

2017-01-02 1:50 GMT+01:00 J Armando Cordova <notifications@github.com>:

**Comment by lrn2prgrm** [comment]
You are right. It will be nice to see Toothpick 2 then. I am enjoying a lot this DI library

**Comment by stephanenicolas** [comment]
Thanks for your words.

2017-01-03 4:19 GMT+01:00 J Armando Cordova <notifications@github.com>:
