### ISSUE TITLE
gradle example missing apply plugin call

### ISSUE THREAD

**Issue by dpreussler** [stephanenicolas/toothpick#172]
when just copy the gradle from readme I get this:

Error:(40, 0) Could not find method apt() for arguments [com.github.stephanenicolas.toothpick:toothpick-compiler:1.0.2] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
<a href="openFile:/Users/preusd/dev/DependencieTests/app/build.gradle">Open File</a>

as its adding the apt plugin but not applying it

needs to add
apply plugin: 'com.neenbedankt.android-apt'

**Comment by stephanenicolas** [comment]
PR is merged. One more thing to do is to try TP with Android Studio 2.2 and the new gradle that actually includes annotation processing out of the box. I will create a ticket for that.
