### ISSUE TITLE
Try TP with new gradle / AS annotation processor build flow

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#174]
try TP with Android Studio 2.2 and the new gradle that actually includes annotation processing out of the box. Then update the README and the samples.

See #172

**Comment by efung** [comment]
Just a quick note to say that we're successfully using TP with AS 2.2, and using the `annotationProcessor` command in our build.gradle.

**Comment by dlemures** [comment]
We need to update the README

**Comment by stephanenicolas** [comment]
Thanks @eric

2017-01-04 15:02 GMT+01:00 Daniel Molinero <notifications@github.com>:

**Comment by dlemures** [comment]
PR: https://github.com/stephanenicolas/toothpick/pull/192

**Comment by dlemures** [comment]
Wiki already updated

**Comment by dlemures** [comment]
PR merged and wiki updated.
Not possible to update smoothie-sample as we need to keep compatibility with Java 7.
