### ISSUE TITLE
Recursive injection

### ISSUE THREAD

**Issue by xtien** [stephanenicolas/toothpick#175]
What is the policy on recursive injection? Currently, Toothpick doesn't seem to support it. By "recursive injection" I mean "class A has B injected and class B has A injected"

I made a small change in my copy of Toothpick, so it now does support recursive injection, or at least it does in the way I use it. Should I contribute the change to Toothpick, or do I wait until you guys incorporate recursion?

**Comment by dlemures** [comment]
Hi @xtien ,

Thanks for the issue.

Based on your example, I would say that you are describing a cycle.

Could you provide a link with your changes?

**Comment by stephanenicolas** [comment]
Hi Christine,

cyclic dependencies are not a good thing from a DI perspective.
TP configurations allow you to check cyclic dependencies and, if the check
is activated, TP will crash at runtime. And this behavior is something
useful to clean your design.

This check can be deactivated in production configurations as it takes time
to check for the cycles.

That being said, a few things are possible to still if you need to have A &
B using each other or you want to postpone their refactor. For instance A
could use a Lazy<B> or a Provider<B>. But this is not a nice solution. I
invite you to do some reseach on cyclic dependencies, and learn how to
solve them, usually by introducing a third party component which will clear
your design.

2016-11-14 17:32 GMT+02:00 Christine <notifications@github.com>:

**Comment by xtien** [comment]
Stephane,
I know how to solve cyclic dependencies, that's what I did to resolve the issue. Then I checked the source of Toothpick, and I found a simple way to include cyclic dependencies for injections that are not constructor injections. 
In InternalProviderImpl, I replaced
`return factory.createInstance(scope);`
by 
`instance = factory.createInstance(scope);
 `
`factory.injectInstance(scope, instance);`
`return instance;`
where createInstance only creates a new instance, doesn't do injection. 
Works fine for me, in a limited number of cases. I'll check if lazy injection can do the same for me, I wasn't aware of lazy injection. 

I looked into changing constructor injection too, but that's more complicated. 

Btw, thanks for creating Toothpick. I just converted two of my projects from Roboguice-4 to Toothpick.

**Comment by xtien** [comment]
Lazy seems to work in one of my projects, so I'll stick with that.

I don't see why supporting cycles would be a bad thing. Roboguice supported it, and I was happy with that.

**Comment by stephanenicolas** [comment]
@xtien, cyclic dependencies are usually a bad smell in design. And to
support them fully when A & B had mutual constructor dependency: A(B b) and
B(A a) then Guice used proxies to solve this case and it was super slow. We
remove the support for this as it simplifies the code and enforces good
practices in DI.

But maybe I miss something here. Can we see some code and some tests that
failed but pass with your change ?

Thx for your kind words on TP.

S.

**Comment by xtien** [comment]
My code works with Lazy injection. I'll test my other project, which is a little more complex. I think lazy injection does what I need.
