### ISSUE TITLE
Replace is suboptimal in the registries

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#182]
We do a replace operation in the registries to lookup for the factories and member injectors, before bucketing. But this is so suboptimal: the bucket entries themselves should be replaced and the match should be direct.

![image](https://cloud.githubusercontent.com/assets/1832925/21615677/daf06842-d1de-11e6-87e4-5a4961d0460f.png)

**Comment by dlemures** [comment]
PR: https://github.com/stephanenicolas/toothpick/pull/184

**Comment by dlemures** [comment]
PR merged
