### ISSUE TITLE
Migration from Dagger 2 to Toothpick

### ISSUE THREAD

**Issue by markchristopherng** [stephanenicolas/toothpick#195]
Hi,

I noticed that if you have the android-apt plugin installed tooth pick doesn't work. There are quite a few libraries that use the android-apt plugin to generate code such as android annotations. Does this mean that toothpick is not compatible with these libraries? If so can this be documented.

Also i was just wondering how to convert @singleton annotated methods in toothpick? I noticed that there are providers (Factories) but i don't want a new instance of the object every time i use injection.  

Does toothpick lazy load the objects ie a singleton is not created until it is first injected.

Thanks

**Comment by stephanenicolas** [comment]
apt plugin does work with Toothpick, we are still using it and there is no
conflict with any other librairy using annotation processing. We use Dart,
Henson, butterknife, Icepick together with Toothpick and we have no issue.

With the latest AS, apt plugin is deprecated and the gradle android plugin
provides a built-in alternative for annotation processors, we are migrating
to it currently and everything seems to work well.

Regarding your question(s) about singletons, there are many things to say:

   - the equivalent of binding methods in Dagger 2 are bindings declared in
   TP modules.
   - Usually you just need a binding for things that are injected via an
   interface and then you bind an implementation class to the interface
   - we don't use a lot of bindings internally and prefer to inject the
   implementation classes directly as it's more conveninent
   - in case something is injected directly as mentioned above, not via an
   interface, you can use annotations on the class that is injected to specify
   the scope in which an entity is a singleton.
   - in case you use a binding, the programmatic binding API provides a lot
   more fine grained methods to define how entities are recycled and to which
   scope they belong

I encourage you to read TP wiki, it should answer most of your questions,
and to open very specific tickets on issues you face.

Just to let you know, for us migrating one of our app from Dagger 1 to TP
has been a charm, it worked really well and we did gain in terms of
performance.



2017-01-30 3:24 GMT-08:00 markchristopherng <notifications@github.com>:

**Comment by markchristopherng** [comment]
Hi,

Its good to know that it works with apt plugin i might dig deeper into why
it do it work for me when i had it enabled.

In dagger 2 you can create method singletons for factory/builders quite
easily. In my current app we have quite alot of these and i was just
wondering are providers the equivalent in toothpick?

    @Provides
    @Named("ExternalHttpClient")
    @Singleton
    OkHttpClient provideExternalOkHttpClient(final Application application,
final NetworkChecker networkChecker) {
        return getOrCreate("ExternalHttpClient", () -> {
            HttpClientBuilder.Builder builder = new
HttpClientBuilder.Builder();
            return builder.setDebug(!BuildConfig.PRODUCTION)
                    .setContext(application)
                    .setNetworkChecker(networkChecker)
                    .build();
        });
    }

To convert it to toothpick i created a provider/factory for each of the
method as below. Is this the correct way of doing it?
The only problem i see with this is that it is more verbose than dagger 2
plus in my module when i do the following binding

bind(OkHttpClient.class).withName("ExternalHttpClient").toProviderInstance(new
ExternalOkhttpClientProvider(application));
i believe the documentation states that would create a new instance where
ever this is suppose to be injected.
In my case this is okay except it is using more memory/resources.

public class ExternalOkhttpClientProvider implements Provider<OkHttpClient>
{

    @Inject NetworkChecker networkChecker;

    @Inject public ExternalOkhttpClientProvider(Application application) {

        this.application = application;

    }

    @Override

    public OkHttpClient get() {

        Scope scope = Toothpick.openScope(application);

        Toothpick.inject(this, scope);

        HttpClientBuilder.Builder builder = new HttpClientBuilder.Builder();

        return builder.setDebug(!BuildConfig.PRODUCTION)

                .setContext(application)

                .setNetworkChecker(networkChecker)

                .build();

    }

}

Anyway thanks for answering my questions so quickly i probably have more.

Regards
Mark

**Comment by stephanenicolas** [comment]
Please do not use mail replies when you have code to format, mail replies can't be formatted.

Yes, providers (don't call them factories, factories are something different in TP) are the way to go.

Here is a simpler version of your provider as providers are injected by TP (if you use a binding of the form `bind(OkHttpClient.class).toProvider(ExternalOkhttpClientProvider.class)`. You can also favor field injection over a mix of constructor and field injections.

```java
@Singleton @ProvidesSingletonInScope
public class ExternalOkhttpClientProvider implements Provider<OkHttpClient> {

    @Inject NetworkChecker networkChecker;
    @Inject Application application;

    @Override
    public OkHttpClient get() {
        HttpClientBuilder.Builder builder = new HttpClientBuilder.Builder();
        return builder.setDebug(!BuildConfig.PRODUCTION)
                .setContext(application)
                .setNetworkChecker(networkChecker)
                .build();
    }
}

```

**Comment by markchristopherng** [comment]
thanks that way is a lot nicer. 

Just getting back to the other problem with apt, i could only get toothpick to work if i removed the plugin. Not sure why but i have attached a cut down version of my build gradle. I don't need apt on this project but it would be good to know why, if i encountered this problem others might as well.


[app-build.txt](https://github.com/stephanenicolas/toothpick/files/744210/app-build.txt)

**Comment by stephanenicolas** [comment]
it's hard to tell about apt as you don't use the apt scope in your build file but only the new annotationProcessor scope. Or, **that** was the issue ?
