### ISSUE TITLE
Change ContextSingleton retention policy to RUNTIME

### ISSUE THREAD

**Issue by zawadz88** [stephanenicolas/toothpick#196]
Hi,
First of all thanks for the great library!
Recently, I tried updating toothpick from 1.0.3 to 1.0.5 in my Android project and got:
`Error:Scope Annotation toothpick.smoothie.annotations.ContextSingleton does not have RUNTIME retention policy.` during compilation.
I checked and `ContextSingleton` from _smoothie_ has runtime policy `CLASS` currently unlike e.g. Singleton from javax.inject or the custom scope in _smoothie-sample_ which probably causes this error. This is probably due to the changes in #191 

Could you help please?

**Comment by dlemures** [comment]
Hi @zawadz88 ,

Thanks for the issue.

This class was meant to be there just as an example. However, the javadoc is not really clear and probably the class is not useful either.

Therefore, we will deprecate the class, change the retention and update the javadoc.
The class will be removed in a later release.

If you are using context singletons, please create the annotation yourself and bind it to the right scopes:
https://github.com/stephanenicolas/toothpick/wiki/Scope-Annotations#binding-a-scope-to-a-scope-annotation

**Comment by stephanenicolas** [comment]
I would add that `ContextSingleton` was really a RoboGuice thing. It looked really cool at that time as you could quickly inject a context. At Groupon, we used a TP ContextSingleton for our migration from RG to TP. 

But, later, we just removed it. The issue is that when you `@Inject Context`, then you just don't know exactly which context you are injecting : an activity or the app context ?? And one can create a leak, not the other one, simply depending on where you inject your entity. 

So, definitely ContextSingleton is more a simple example of a custom annotation but it should not be used in a production app. At Groupon, we ActivityScope, ServiceScope, and we never inject a context, always either the Application or an Activity or a Service, so that we have full control over what is injected. And we use the scope verification mechanism of TP to be sure we don't leak the activity.

**Comment by zawadz88** [comment]
Thanks for the clarification and sorry for the misclick ;)

**Comment by HugoGresse** [comment]
I was searching how to inject the `Application` in a `@Singleton` is there any example on the documentation/demo? 
I also don't find any documentation about Toothpick. I'm just a beginner with DI :/

**Comment by stephanenicolas** [comment]
If you install the smoothie application module in your app scope, then you can simply use `@Inject Application app` in this scope or any sub scope. 

All the docs of TP is in the wiki in the repo... @HugoGresse

**Comment by HugoGresse** [comment]
well, that what I thought but I can't seem to make it work in my `@Singleton` 

```
public class MyApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        Scope appScope = Toothpick.openScope(this);
        appScope.installModules(new SmoothieApplicationModule(this));
    }
}
```

```
@Singleton
public class ServiceProvider {

    @Inject
    protected SocialService                mSocialService;

    public ServiceProvider() {
    }
```

```

@Singleton
public class SocialService {

    @Inject
    public Application mApplication;

    public SocialService() {
        mChromeCustomTabsManager = new ChromeCustomTabsManager(mApplication);
    }

```

I can't achieve to inject the Application in the last SocialService singleton... Am I missing something? I'm using `@Inject ServiceProvider` in activities like this

```

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        Scope scope = Toothpick.openScopes(getApplication(), ServiceProvider.class, this);
        scope.installModules(new SmoothieActivityModule(this));
        super.onCreate(savedInstanceState);
        Toothpick.inject(this, scope);
```

**Comment by dlemures** [comment]
@HugoGresse were you able to do it?

**Comment by HugoGresse** [comment]
yep, that was fine. I've still some issue where the @Inject is done after constructor call which conduce me to delay some action. For example [here](https://github.com/HugoGresse/Anecdote/blob/favoris/app/src/main/java/io/gresse/hugo/anecdote/anecdote/like/FavoritesRepository.java#L46). I've probably made something wrong but I am inject the scope on the class AFTER is instantation that maybe be this.

**Comment by stephanenicolas** [comment]
@HugoGresse there are 2 things you can do with TP, and I believe it's the same with dagger / Roboguice:

* use a constructor with `@Inject` annotation, then all arguments will be created by TP (it needs to have a provider / or a binding or the classes to be annotated properly).

```java
class Foo {
  Bar bar;

  @Inject
  public Foo(Bar bar) {
     bar.bar(); // <-- would work as long as TP knows how to create the instance of Bar 
  }
```
* use a `@Inject` annnotated method. These methods are executed after fields are initialized.
```java
class Foo {
  @Inject Bar bar;

  @Inject
  public Foo() {
     bar.bar(); // <-- would fail because members are not initialized yet, see the factory code.
  }

 @Inject
 void init() {
     bar.bar(); // <-- would work
  }
}
```

**Comment by stephanenicolas** [comment]
Release 1.0.8 will solve this issue.
