### ISSUE TITLE
Espresso and Toothpick

### ISSUE THREAD

**Issue by markchristopherng** [stephanenicolas/toothpick#197]
Hi,

I am getting the following error when i have more than 1 test in my espresso test class.
java.lang.IllegalStateException: TestModules can only be installed once per scope.

My test rule is as follows;

I noticed it didn't matter if i reset or closed the scope i still got this error. I looked into your code and could the problem be due to a flag not being reset? 

 ActivityTestRule<ExampleMainActivity> testRule = new ActivityTestRule<ExampleMainActivity>(ExampleMainActivity.class, false) {

        @Override
        protected void beforeActivityLaunched() {
            super.beforeActivityLaunched();
            Context appContext = InstrumentationRegistry.getTargetContext().getApplicationContext();
            scope = Toothpick.openScope(appContext);
            scope.installTestModules(new ExampleMainActivityTest.TestModule());
        }

        @Override
        protected void afterActivityFinished() {
            super.afterActivityFinished();
            Toothpick.reset();
        }
    };

It all seems to work when i have just one test. Thanks for looking into it.

**Comment by stephanenicolas** [comment]
I would swap the reset and the super call in `afterActivityFinished `. But it's probably not the issue.

We need you to debug your test and see if really there are consecutive callls to `installTestModules` without `reset` being called.

**Comment by markchristopherng** [comment]
Hi,
I had the wrong method it should have been afterActivityLaunched() and NOT afterActivityFinished(). The reset is now being called however i am getting a new error 

java.lang.IllegalStateException: The scope with name au.com.auspost.digitalid.android.app.Application@f1ceca4 has been already closed. It is not possible to use it to create new instances.

With the type of testing i am doing i would need openScope and Install Modules and then reset when it finishes for every test.

**Comment by markchristopherng** [comment]
here is the test class that is producing the exception "has been already closed"

This occurs when testLaunchApplication2() executes which calls beforeActivityLaunched again with the same application context.

@RunWith(AndroidJUnit4.class)
public class ExampleMainActivityTest {

    WeatherManager weatherManager;

    ActivityTestRule<ExampleMainActivity> testRule = new ActivityTestRule<ExampleMainActivity>(ExampleMainActivity.class, false) {

        @Override
        protected void beforeActivityLaunched() {
            super.beforeActivityLaunched();
            Context appContext = InstrumentationRegistry.getTargetContext().getApplicationContext();
            Scope scope = Toothpick.openScope(appContext);
            scope.installTestModules(new ExampleMainActivityTest.TestModule());
        }

        @Override
        protected void afterActivityLaunched() {
            Toothpick.reset();
            super.afterActivityFinished();
        }
    };

    @Test
    public void testLaunchApplication1() {
        weatherManager = mock(WeatherManager.class);
        testRule.launchActivity(null);
        when(weatherManager.getWeatherRxJava(anyObject())).thenReturn(rx.Observable.just(getWeather()));
        onView(withId(R.id.navigate)).perform(click());
        assertTrue(true);
    }

    @Test
    public void testLaunchApplication2() {
        weatherManager = mock(WeatherManager.class);
        testRule.launchActivity(null);
        when(weatherManager.getWeatherRxJava(anyObject())).thenReturn(rx.Observable.just(getWeather()));
        onView(withId(R.id.navigate)).perform(click());
    }

    private class TestModule extends Module {
        public TestModule() {
            bind(WeatherManager.class).toInstance(weatherManager);
        }
    }

    public Weather getWeather() {
        Weather weather = new Weather();
        Weather.Main main = new Weather.Main();
        weather.setMain(main);
        main.setTempMax(31d);
        return weather;
    }
}

**Comment by markchristopherng** [comment]
Hi,

Apparently afterActivityFinished() wasn't been called so i added a method to do the reset after each test using the @After annotation as below;

@RunWith(AndroidJUnit4.class)
public class ExampleMainActivityTest {

    public static String TAG = "toothpick-test";

    WeatherManager weatherManager;

    ActivityTestRule<ExampleMainActivity> testRule = new ActivityTestRule<ExampleMainActivity>(ExampleMainActivity.class, false) {

        @Override
        protected void beforeActivityLaunched() {
            super.beforeActivityLaunched();
            Log.d(TAG, "beforeActivityLaunched()");
            Context appContext = InstrumentationRegistry.getTargetContext().getApplicationContext();
            Scope scope = Toothpick.openScope(appContext);
            scope.installTestModules(new ExampleMainActivityTest.TestModule());
        }
    };


    @After
    public void tearDown() {
        Log.d(TAG, "teardown");
        Toothpick.reset();
    }

    @Test
    public void testLaunchApplication1() {
        weatherManager = mock(WeatherManager.class);
        Log.d(TAG, "before launchActivity1");
        testRule.launchActivity(null);
        Log.d(TAG, "after launchActivity1");
        when(weatherManager.getWeatherRxJava(anyObject())).thenReturn(rx.Observable.just(getWeather()));
        onView(withId(R.id.navigate)).perform(click());
        assertTrue(true);
    }

    @Test
    public void testLaunchApplication2() {
        weatherManager = mock(WeatherManager.class);
        Log.d(TAG, "before launchActivity2");
        testRule.launchActivity(null);
        Log.d(TAG, "after launchActivity2");
        when(weatherManager.getWeatherRxJava(anyObject())).thenReturn(rx.Observable.just(getWeather()));
        onView(withId(R.id.navigate)).perform(click());
    }

    private class TestModule extends Module {
        public TestModule() {
            bind(WeatherManager.class).toInstance(weatherManager);
        }
    }

    public Weather getWeather() {
        Weather weather = new Weather();
        Weather.Main main = new Weather.Main();
        weather.setMain(main);
        main.setTempMax(31d);
        return weather;
    }
}

02-02 15:54:52.857 9001-9026/au.com.auspost.digitalid.android.debug D/toothpick-test: before launchActivity1
02-02 15:54:52.862 9001-9026/au.com.auspost.digitalid.android.debug D/toothpick-test: beforeActivityLaunched()
02-02 15:54:53.243 9001-9026/au.com.auspost.digitalid.android.debug D/toothpick-test: after launchActivity1
02-02 15:54:53.923 9001-9026/au.com.auspost.digitalid.android.debug D/toothpick-test: teardown
02-02 15:54:54.098 9001-9026/au.com.auspost.digitalid.android.debug D/toothpick-test: before launchActivity2
02-02 15:54:54.114 9001-9026/au.com.auspost.digitalid.android.debug D/toothpick-test: beforeActivityLaunched()


I am now getting a different exception when the second test case runs.

java.lang.IllegalStateException: The scope with name android.app.Application@f1ceca4 has been already closed. It is not possible to use it to create new instances.

**Comment by dlemures** [comment]
Do you have a stacktrace?

When `Toothpick.reset()` is called, all TP scopes are closed. Thus, they cannot be used anymore. However, you can open new ones.

Is it possible that your activity is still using the old scope? The one closed after `testLaunchApplication1 `.

**Comment by markchristopherng** [comment]
Hi,

Here is the stack trace. The reset is being called before the testLauchApplication2 is executed.


java.lang.IllegalStateException: The scope with name au.com.app.android.app.Application@89995e9 has been already closed. It is not possible to use it to create new instances.
at toothpick.ScopeImpl.crashIfClosed(ScopeImpl.java:509)
at toothpick.ScopeImpl.getInstance(ScopeImpl.java:53)
at toothpick.ScopeImpl.getInstance(ScopeImpl.java:48)
at au.com.app.android.activity.main.ExampleMainFragment$$MemberInjector.inject(ExampleMainFragment$$MemberInjector.java:12)
at au.com.app.android.activity.main.ExampleMainFragment$$MemberInjector.inject(ExampleMainFragment$$MemberInjector.java:9)
at toothpick.InjectorImpl.inject(InjectorImpl.java:25)
at toothpick.Toothpick.inject(Toothpick.java:140)
at au.com.app.android.activity.main.ExampleMainFragment.onCreate(ExampleMainFragment.java:35)
at android.app.Fragment.performCreate(Fragment.java:2198)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
at android.app.BackStackRecord.run(BackStackRecord.java:793)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
at android.app.FragmentController.execPendingActions(FragmentController.java:325)
at android.app.Activity.performStart(Activity.java:6252)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)


java.lang.RuntimeException: Unable to start activity ComponentInfo{au.com.app.android.debug/au.com.app.android.activity.main.ExampleMainActivity}: java.lang.IllegalStateException: The scope with name au.com.app.android.app.Application@89995e9 has been already closed. It is not possible to use it to create new instances.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: The scope with name au.com.app.android.app.Application@89995e9 has been already closed. It is not possible to use it to create new instances.
at toothpick.ScopeImpl.crashIfClosed(ScopeImpl.java:509)
at toothpick.ScopeImpl.getInstance(ScopeImpl.java:53)
at toothpick.ScopeImpl.getInstance(ScopeImpl.java:48)
at au.com.app.android.activity.main.ExampleMainFragment$$MemberInjector.inject(ExampleMainFragment$$MemberInjector.java:12)
at au.com.app.android.activity.main.ExampleMainFragment$$MemberInjector.inject(ExampleMainFragment$$MemberInjector.java:9)
at toothpick.InjectorImpl.inject(InjectorImpl.java:25)
at toothpick.Toothpick.inject(Toothpick.java:140)
at au.com.app.android.activity.main.ExampleMainFragment.onCreate(ExampleMainFragment.java:35)
at android.app.Fragment.performCreate(Fragment.java:2198)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
at android.app.BackStackRecord.run(BackStackRecord.java:793)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
at android.app.FragmentController.execPendingActions(FragmentController.java:325)
at android.app.Activity.performStart(Activity.java:6252)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
... 9 more

Test running failed: Instrumentation run failed due to 'java.lang.IllegalStateException'

**Comment by markchristopherng** [comment]
i even changed to the code

**Comment by dlemures** [comment]
Could I see the code of `ExampleMainActivity ` and `ExampleMainFragment`?

According to the stacktrace, it looks like `ExampleMainFragment.onCreate()` is using an old scope when calling `Toothpick.inject`

**Comment by markchristopherng** [comment]
Here the requested classes

public class ExampleMainActivity extends DrawerBaseActivity {

    private final String TAG = ExampleMainActivity.class.getSimpleName();

    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);
        setContentView(R.layout.empty_base);
        addFragment(new ExampleMainFragment());
        setTitle("This is the Main Test Page");
        Log.d(TAG, "onCreate()");
    }

    public boolean isTopLevelActivity() {
        return true;
    }
}


public class ExampleMainFragment extends BaseFragment {
    static final String TAG = ExampleMainFragment.class.getSimpleName();

    @Inject
    Whiteboard whiteboard;

    @Inject
    WeatherManager weatherManager;

    boolean showProgress = true;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Toothpick.inject(this, getApplicationScope());
        Log.d("----- W ------", " whiteboard is " + whiteboard);

    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view =  inflater.inflate(R.layout.example_fragment_main, container, false);
        return view;
    }

    @OnClick(R.id.info_button)
    public void onInfoClicked() {
        Log.d(TAG, "onInfoClicked()");
        MessageUtils.showInlineInfoMessage("This is an info message.");
    }

    @OnClick(R.id.warning_button)
    public void onWarningButtonClicked() {
        Log.d(TAG, "onWarningButtonClicked()");
        MessageUtils.showInlineWarningMessage("This is an warning message.");
    }

    @OnClick(R.id.error_button)
    public void onErrorButtonClicked() {
        Log.d(TAG, "onErrorButtonClicked()");
        MessageUtils.showInlineErrorMessage("This is an error message.");
    }

    @OnClick(R.id.sucess_button)
    public void onSuccessButtonClicked() {
        Log.d(TAG, "onSuccessButtonClicked()");
        MessageUtils.showInlineSuccessMessage("This is a success message.");
    }

    @OnClick(R.id.progress_button)
    public void onProgressButtonClicked() {
        Log.d(TAG, "onProgressButtonClicked()");
        if (showProgress) {
            ProgressUtils.showProgress();
            showProgress = false;
        } else {
            ProgressUtils.hideProgress();
            showProgress = true;
        }
    }

    @OnClick(R.id.simple_dialog)
    public void onMaterialDialogButtonClicked() {

        MaterialDialog.Builder builder =
            new MaterialDialog.Builder(getActivity())
                .title("This is a test title")
                .content("This is a test message")
                .positiveText(R.string.button_OK)
                .negativeText(R.string.button_no)
                .onPositive((dialog, which) -> {
                    dialog.dismiss();
                })
                .onNegative((dialog, which) -> {
                    dialog.dismiss();
                });
        MaterialDialog materialDialog = builder.build();
        materialDialog.show();
    }

    @OnClick(R.id.navigate)
    public void onWeatherClicked() {
        addCompositeSubscription(weatherManager.getWeatherRxJava("melbourne, australia")
                .compose(defaultOptions())
                .subscribe(weather -> {
                    String msg = String.format("The max temp today in %s is: %s F", weather.getName(), weather.getMain().getTempMax());
                    MessageUtils.showInlineSuccessMessage(msg);
                }, error -> {
                    MessageUtils.showInlineErrorMessage("Could not retrieve the temp." + error.getMessage());
                })
        );
    }

}

**Comment by dlemures** [comment]
@markchristopherng can i see all the logic related to `getApplicationScope` ?

**Comment by markchristopherng** [comment]
i am almost giving you all the code :) If i have time over the next couple of weeks i will try to create a public repo (i need to strip out all the company ip). my gut feeling is that this could be related with espresso, do you use espresso at groupon?

BaseFragment.java

  public Scope getApplicationScope() {
        return ((Application) getActivity().getApplication()).getScope();
    }

Application.java
 //Toothpick scope
    Scope scope;
    
    @Override
    public void onCreate() {
        super.onCreate();
        Log.d(TAG, "onCreate()");
        scope = Toothpick.openScope(this);
        scope.installModules(new ApplicationModule(this));
        Toothpick.inject(this, scope);

    }

    public Scope getScope() {
        return scope;
    }

**Comment by dlemures** [comment]
Thx for sharing all the code 😄.

The issue is related to the way you keep the app scope inside `Application.java`.

These are the steps:
1. `Application.java` opens `app scope` (**scope 1**) and installs `ApplicationModule`.
2. **Scope 1** is saved inside the Application instance.
3. The first activity launch opens **scope 1** and install test module.
4. **Scope 1** is used inside the fragment to inject.
5. The **scope 1** is reset. It cannot be used anymore.
6. The second activity launch opens a new `app scope` (**scope 2**) and install test module.
7. **Scope 1** (and not 2) is used inside the fragment to inject. Scope 1 is the one return by `Application.getScope()`.
8. **Scope 1** is closed -> It cannot be used anymore -> It fails

I have a couple of suggestions:

1. What is defined inside `ExampleMainActivityTest.TestModule()`? If you don't have mocks or anything that needs to be reset, do you need to reset TP?

```java
// NEEDED?
Context appContext = InstrumentationRegistry.getTargetContext().getApplicationContext();
Scope scope = Toothpick.openScope(appContext);
scope.installTestModules(new ExampleMainActivityTest.TestModule());
```

2. If you do need to reset it, you can have a look at this issue: https://github.com/stephanenicolas/toothpick/issues/188

**Comment by markchristopherng** [comment]
The TestModule is binding to a mock and overriding the real implementation.

I tried your second suggestion and it seems to work, i was wondering if you could describe what is happening in detail like you did above as i am not exactly sure i fully understand it.

Through app the app i used Toothpick.openScope(APP_SCOPE) as suggested in the comments but i was wondering why wouldn't you use Toothpick.openScopes(ROOT_SCOPE, APP_SCOPE) instead. I changed the code code as follows;

Application.java

@Override
public void onCreate() {
    super.onCreate();
    scope = Toothpick.openScope(ROOT_SCOPE);
    scope.installModules(new ApplicationModule(this));
    Toothpick.inject(this, scope);

    Scope appScope = Toothpick.openScopes(ROOT_SCOPE, APP_SCOPE); 
}

Is the openScopes(ROOT_SCOPE, APP_SCOPE) necessary to say APP_SCOPE is a child of ROOT_SCOPE? 

Activity.java
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    Toothpick.inject(this, APP_SCOPE);
}

Thanks looking forward for you reply.

**Comment by dlemures** [comment]
Glad it worked!

**Steps Production:**
1. `Application.java` opens `ROOT_SCOPE` and installs `ApplicationModule`.
2. `Application.java` opens `APP_SCOPE` and makes it a child of `ROOT_SCOPE`. So `APP_SCOPE` inherits the bindings of `ROOT_SCOPE`. 
```
ROOT_SCOPE
      \
    APP_SCOPE
```
3. All injections throughout the app use `APP_SCOPE` as the base scope. Everything works as if `ROOT_SCOPE ` didn't exist:
```java
// Here we are reopening the APP_SCOPE.
// It was already defined as a child of ROOT_SCOPE in Application.onCreate
// and we are not changing that.
Toothpick.inject(this, Toothpick.openScope(APP_SCOPE));
```

**Steps Espresso Tests:**
1. `Application.java` opens `ROOT_SCOPE` and installs `ApplicationModule`.
2. `Application.java` opens `APP_SCOPE` (**scope 1**) and makes it a child of `ROOT_SCOPE`. So `APP_SCOPE` inherits the bindings of `ROOT_SCOPE`. 
```
ROOT_SCOPE
      \
    APP_SCOPE
```
3. The first activity launch opens **scope 1** and install test module.
```java
// We need to specify ROOT_SCOPE as we will need to link again after the every run
Scope appScope = Toothpick.openScopes(ROOT_SCOPE, APP_SCOPE);
appScope.installTestModules(new YourTestModule());
```
4. **Scope 1** is used inside the fragment/activity to inject.
5. **Scope 1** is closed when first activity launch is over. 
```java
Toothpick.closeScope(APP_SCOPE);
```
6. The second activity launch opens a new `APP_SCOPE` (**scope 2**) and makes it a child of `ROOT_SCOPE` (still the one defined at step one, we didn't touch it). It install test module as well.
```java
// We need to specify ROOT_SCOPE as we will need to link again after the every run
Scope appScope = Toothpick.openScopes(ROOT_SCOPE, APP_SCOPE);
appScope.installTestModules(new YourTestModule());
```
7. **Scope 2** is used inside the fragment/activity to inject.

**Comment by dlemures** [comment]
Feel free to close it once you are happy with the result.

Also, if you come with another solution that you would like to share, I'd be happy to see it.

Regarding your previous question: At Groupon we didn't have this issue as we "don't use mocks" with our Espresso tests.

**Comment by markchristopherng** [comment]
Thanks for the detailed explanation it really helps, closing this issue.
