### ISSUE TITLE
Migrating from RoboGuice 3 to ToothPick

### ISSUE THREAD

**Issue by vj12354** [stephanenicolas/toothpick#204]
Hi @stephanenicolas ,

Firstly, thank you for a such a nice DI lib and I see it has go some real potential. Currently, my app uses RoboGuice DI and considering to replace it with Dagger 2 or other better frameworks. I'm not 100% happy with Dagger 2 because of the boilerplate code & mandator constructor injection for non UI classes. As an alternative I found TP and impressed so far, also it looks very close to RoboGuice, which means a quicker migration for me.

My Query: I don't the smoothie example `Module` cover `Binding.to()`, can I rely on `bind(Xxx.class).to(XxxImpl.class)` for the framework to creating an instance for me, similar to roboguice?
And my implementation class annotated with `@Singleton` if needed.

Thanks,
Vijay

**Comment by stephanenicolas** [comment]
Hi Vijay,

you will see that TP is really worth it and yes migrating from RG to TP is much easier than to Dagger2. 

```java
bind(X.class).to(Y.class)
```

will create a binding from `X` to `Y`. Which means everytime, in a scope using this module, you will be able to do `@Inject X x` and you will get an instance of `Y`.

If you want to get a singleton instance of `Y` in this scope, then you have a few alternatives:
* use `bind(X.class).toInstance( <a given y instance>)`
* use `bind(X.class).toInstance( <a given y instance>).singletonInScope()`
* use `bind(X.class).toProvider(XProvider.class)` where XProvider is either annotated with @ProvidesSingletonInScope or manually manage to return a singleton. You can also use our API to say a normal provider instance provides singletons..

There are really a lot of ways to do it. But,no, annotating `Y` with `@Singleton` won't work. Such annotations are only taken into account if there is no explicit binding.

**Comment by stephanenicolas** [comment]
There is more details in our [wiki](https://github.com/stephanenicolas/toothpick/wiki) about all this, it's really worth it:
* https://github.com/stephanenicolas/toothpick/wiki/Modules-&-Bindings#binding-modes
* https://github.com/stephanenicolas/toothpick/wiki/Scoped-&-Unscoped%20Bindings

and feel free to get guided by the binding API completion, it will work well.

**Comment by vj12354** [comment]
Looks like `bind(X.class).to(Y.class)` is not working keep getting this error:
`java.lang.ClassNotFoundException: Didn't find class "com.example.beans.Greeting$$Factory" on path: DexPathList`

Not I'm not using Registry stuff, just wanted simple reflection based to work.

Falling back to use `bind(X.class).toProviderInstance(new XYProfider(activity))` before giving up.

**Comment by stephanenicolas** [comment]
@vj12354 , you won't be able to use TP without reading the docs.

To be able to build `Y`, TP needs a `Factory`, and it builds a factory if and only if `Y` has an `@Inject` annotated constructor or some other easier conditions (like being scope annotated or using field or method injection and having a default constructor).

Please, take some time to read the documentation, it is quite detailed about how TP works. There is no magic, and you need a base of understanding of its internal work. The same applies to other DI libs, especially when they use annotation processing.
