### ISSUE TITLE
Register modules through annotation 

### ISSUE THREAD

**Issue by digitalbuddha** [stephanenicolas/toothpick#208]
It would be nice to have something like 

```java
@Modules(activityModule.class) 
public class Activity
```

Instead of 
https://github.com/stephanenicolas/toothpick/blob/master/smoothie-sample/src/main/java/com/example/smoothie/RxMVPActivity.java#L35

You should be able to generate the instantiation and pass whatever `this` is when creating the scope

**Comment by stephanenicolas** [comment]
Though this annotation is not inside the JSR, we could add a feature like this. It makes me wonder about the sharpness of the lib though. Also, I am really not sure that we can always get the value of all params of a module, they can indeed be coded in so many ways (using an application, an activity, a service are common requirements but you can really do what you want programmtically). 

Though, what would be interesting for TP is a new module to support dagger 1 or dagger 2 modules. It would definitely help people to migrate from these to TP.

**Comment by stephanenicolas** [comment]
It looks like no one is interested in implementing this, I close the issue.
