### ISSUE TITLE
MemberInjectorRegistry doesn't contain classes with @Inject annotations from androidTest package

### ISSUE THREAD

**Issue by L7ColWinters** [stephanenicolas/toothpick#209]
```
javaCompileOptions {
            annotationProcessorOptions {
                    arguments=[toothpick_registry_package_name : "com.cool.name.goes.here"]
            }
 }
```

After putting the above into the defaultConfig block that was mentioned on https://github.com/stephanenicolas/toothpick/wiki/Factory-and-Member-Injector-registries, I'm able to run my app with an application level scope that is stored in the Application instance and references an auto generated MemberInjectorRegistry that contains all classes that I gave @Inject tags on. 

However, now I'm trying to add some instrumented tests, below for example

```
    private Scope currentTestScope;

    @Before
    public void setup() {
        currentTestScope = Toothpick.openScope(this);
        currentTestScope.installModules(new TestMessageHelperModule(), new PreferenceUserHelperModule(), new SMSSenderHelperModule());
        Application.getCoolApplication().setTestScope(currentTestScope);
    }

    @After
    public void tearDown() {
        Application.getCoolApplication().setTestScope(null);
        Toothpick.reset();
    }
```

I see toothpick.registries.NoFactoryFoundException: No factory could be found for class TestMessageHelper. TestMessageHelper is defined inside of the androidTest code which has the same package so i'm kinda at a loss because it seems all of the example code i've seen doesn't change anything for the registry with regards to the test code. 

The setTestScope is a method that overrides the default application scope since I read somewhere that you cannot override modules after they have been installed in a scope. I'm still learning Toothpick.

Any idea on why my registry isn't generating properly?

```
    compile "com.github.stephanenicolas.toothpick:toothpick-runtime:$rootProject.ext.toothpickVersion"
    annotationProcessor "com.github.stephanenicolas.toothpick:toothpick-compiler:$rootProject.ext.toothpickVersion"

    //highly recommended
    testCompile "com.github.stephanenicolas.toothpick:toothpick-testing:$rootProject.ext.toothpickVersion"
```

Also when trying to do this with reflection it fails, not able to find the class TestMessageHelper.

**Comment by stephanenicolas** [comment]
Can we see `TestMessageHelper` ? 

To get created by TP, it should have either:
* an injected field or method + a default constructor
* a scope annotation + a default constructor. If it is a custom scope, there is a little more setup.
* or have an annotated constructor.

**Comment by L7ColWinters** [comment]
```
public class TestMessageHelper implements MessageHelper {

    private HashMap<Integer, Message> messages = new HashMap<>();

    @Inject
    public TestMessageHelper() {
        Message initialMessage = new Message();
        initialMessage.setId(1);
        initialMessage.setLabel("Archers revenge");
        initialMessage.setMessage("Ha! Cool Text. You know what to do.");
        create(initialMessage);
    }
```

as you can see I have an annotated constructor

**Comment by L7ColWinters** [comment]
I don't understand why yet but when I set an annotated constructor visibility to private it will error when trying to build as per spec but when I do that to the TestMessageHelper, nothing happens. Seems like the annotation processor is not running on my test code but not sure what I did for that to happen.

**Comment by stephanenicolas** [comment]
Sorry, I understand the issue now. 

To solve it, you need to enable the TP compiler for testing scope. Something like:
```groovy
    testAnnotationProcessor "com.github.stephanenicolas.toothpick:toothpick-compiler:$rootProject.ext.toothpickVersion"
```

The issue though is that I don't think there is such a scope available for test code. If not, you should, please:
1) report it here
2) open a ticket on android bugs
3) use apt as it does provide such a scope

Finally, it's not a direct resolution, but I think you should consider using a mock libary instead of creating a fake test class manually. You can use either Mockito or EasyMock. And TP can help to achieve quite good mocking + injection for testing.

We didn't have time to write a proper wiki doc, @dlemures am I wrong ? 
But here is a screenshot from our latest Android conference talk about it, it will guide you to use the TP testing stuff.

![image](https://cloud.githubusercontent.com/assets/1832925/25042125/deafcc6c-2115-11e7-98bc-75b1a56b3d1a.png)

**Comment by stephanenicolas** [comment]
Note that annotated constructors can't be private as they need to be callable from the generated factory.

**Comment by stephanenicolas** [comment]
testAnnotationProcessor has been added in android gradle plugin 3. Otherwise, apt plugin is still a valid work around. I close this issue.
