### ISSUE TITLE
Explore TP + Kotlin

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#211]

**Comment by kelsos** [comment]
@stephanenicolas is it about something specific, or general use of kotlin and TP?

**Comment by stephanenicolas** [comment]
@kelsos really a general question. Neither @dlemures nor me have any experience in Kotlin. 
* Does TP work well ? (I think you mentioned it was working well, @dpreussler mentioned it worked well in tests).
* Do we need any special setup ?
* Should we add a wiki page ?

**Comment by kelsos** [comment]
@stephanenicolas I use toothpick on both a project that is completely in Kotlin and one that contains both Kotlin and Java. Toothpick works well on both situations. Following the existing wiki instructions was all I needed to do, nothing special required.

**Comment by BugsBunnyBR** [comment]
Is there any android project on github using toothpick? If it is in kotlin, even better...

**Comment by kelsos** [comment]
@BugsBunnyBR It is far from being something satisfactory, but you could check mbrc (last tagged release) on my repositories.

**Comment by stephanenicolas** [comment]
Actually I tried TP on a small project in Kotlin for a friend and it worked seamlessly. Not sure I could take advantage of all the language features (like lazies) but still there was no issue at all. 

I will close this issue to clean our issue list but feel free to add comments, sample repos etc.
