### ISSUE TITLE
Releasing singletons on low memory

### ISSUE THREAD

**Issue by dlemures** [stephanenicolas/toothpick#212]
Should we release singletons on low memory?

Would they be singletons in that case? 
Isn't it obscure black magic for the user?
Isn't it user design problems?

**Comment by stephanenicolas** [comment]
We should release all internal providers, but it is not possible to release all of them automatically as some can't recover their state. Thus, users should have full control over this. We should provide different mechanisms to let user makr things that can be released:
* add an annotation `@Releasable` that can apply to a type that is injected
* add `.markAsReleasable()` to the bindings API
