### ISSUE TITLE
Unit tests with Mockito

### ISSUE THREAD

**Issue by fabiogrum** [stephanenicolas/toothpick#214]
Hi, 
I'm trying to do some unit testing with Toothpick and Mockito, but I have a null pointer exception, when I try to inject the class under test (ContactsPresenter mContactsPresenter).

```
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;

import java.util.ArrayList;
import java.util.List;

import javax.inject.Inject;

import io.reactivex.Single;
import toothpick.testing.ToothPickRule;

import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;


@RunWith(MockitoJUnitRunner.class)
public class ContactsPresenterTest {
    @Rule public ToothPickRule toothPickRule = new ToothPickRule(this);

    @Mock ContactsView mContactsView;

    @Mock UserModel mUserModel;
    @Mock ContactsDataSource mContactsDataSource;
    @Inject ContactsPresenter mContactsPresenter;

    @Before
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
        when(mUserModel.fetchCountries("")).thenReturn(Single.just((List<Country>) new ArrayList<Country>(0)));
        toothPickRule.inject(this);
        mContactsPresenter.fetchUsers();
    }

    @Test
    public void testUserCalled() {
        verify(mContactsView).onUsersListFetching();
    }

}
```

I have these dependencies : 

```
    compile 'com.github.stephanenicolas.toothpick:toothpick-runtime:1.0.6'
    testCompile 'com.github.stephanenicolas.toothpick:toothpick-testing:1.0.6'
    annotationProcessor 'com.github.stephanenicolas.toothpick:toothpick-compiler:1.0.6'
    testCompile "org.mockito:mockito-core:2.8.9"
```

This is the generated factory : 

```
import java.lang.Override;
import toothpick.Factory;
import toothpick.MemberInjector;
import toothpick.Scope;

public final class ContactsPresenter$$Factory implements Factory<ContactsPresenter> {
  private MemberInjector<ContactsPresenter> memberInjector = new ....ContactsPresenter$$MemberInjector();

  @Override
  public ContactsPresenter createInstance(Scope scope) {
    scope = getTargetScope(scope);
    ContactsPresenter contactsPresenter = new ContactsPresenter();
    memberInjector.inject(contactsPresenter, scope);
    return contactsPresenter;
  }

  @Override
  public Scope getTargetScope(Scope scope) {
    return scope;
  }

  @Override
  public boolean hasScopeAnnotation() {
    return false;
  }

  @Override
  public boolean hasProvidesSingletonInScopeAnnotation() {
    return false;
  }
}
```

java.lang.NullPointerException
	at ...ContactsPresenterTest.setUp(ContactsPresenterTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at toothpick.testing.ToothPickStatement.evaluate(ToothPickStatement.java:17)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:78)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:84)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:161)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by stephanenicolas** [comment]
Can you debug the test and tell what is going wrong more precisely ?

**Comment by fabiogrum** [comment]
Thank for your help and for this amazing library. It seems like there is a problem with the mockito interceptor. The mocks are created, but the class under test is null.

```
((ScopeImpl)((ToothPickRule)((ContactsPresenterTest)this).toothPickRule).scope).name = "testScope"
 value = {char[9]@1855} 
 hash = -1191701278
toothPickRule.testModule = {ToothPickTestModule@1840} 
 test = null
 mockCount = 3
 bindingSet = {HashSet@1849}  size = 3
toothPickRule.scope = {ScopeImpl@1838} "testScope:1495608502\r\nProviders: [com.tapptic.business.UserModel,...features.contacts.ContactsView,com.tapptic.net.api.ContactsDataSource,toothpick.Scope]\r\nUnbound providers: []\r\n"
 mapClassesToNamedBoundProviders = {IdentityHashMap@1850}  size = 0
 mapClassesToUnNamedBoundProviders = {IdentityHashMap@1851}  size = 4
 hasTestModules = true
 childrenScopes = {ConcurrentHashMap@1852}  size = 0
 parentScopes = {CopyOnWriteArrayList@1853}  size = 0
 name = "testScope"
 isOpen = true
 scopeAnnotationClasses = {CopyOnWriteArraySet@1854}  size = 0
toothPickRule = {ToothPickRule@1814} 
 testModule = {ToothPickTestModule@1840} 
  test = null
  mockCount = 3
  bindingSet = {HashSet@1849}  size = 3
 scope = {ScopeImpl@1838} "testScope:1495608502\r\nProviders: [com.tapptic.business.UserModel,...features.contacts.ContactsView,com.tapptic.net.api.ContactsDataSource,toothpick.Scope]\r\nUnbound providers: []\r\n"
  mapClassesToNamedBoundProviders = {IdentityHashMap@1850}  size = 0
  mapClassesToUnNamedBoundProviders = {IdentityHashMap@1851}  size = 4
  hasTestModules = true
  childrenScopes = {ConcurrentHashMap@1852}  size = 0
  parentScopes = {CopyOnWriteArrayList@1853}  size = 0
  name = "testScope"
  isOpen = true
  scopeAnnotationClasses = {CopyOnWriteArraySet@1854}  size = 0
mContactsPresenter = null
((ContactsPresenterTest)this).mContactsPresenter = null
((MockMethodInterceptor)mockitoInterceptor).serializationSupport = Cannot find local variable 'mockitoInterceptor'
((MockMethodInterceptor)mockitoInterceptor).mockCreationSettings = Cannot find local variable 'mockitoInterceptor'
((MockMethodInterceptor)mockitoInterceptor).handler = Cannot find local variable 'mockitoInterceptor'
mockitoInterceptor = Cannot find local variable 'mockitoInterceptor'
((ContactsPresenterTest)this).mContactsDataSource = {ContactsDataSource$MockitoMock$120191758@1822} "mContactsDataSource"
 mockitoInterceptor = {MockMethodInterceptor@1857} 
((MockMethodInterceptor)mockitoInterceptor).serializationSupport = Cannot find local variable 'mockitoInterceptor'
((MockMethodInterceptor)mockitoInterceptor).mockCreationSettings = Cannot find local variable 'mockitoInterceptor'
((MockMethodInterceptor)mockitoInterceptor).handler = Cannot find local variable 'mockitoInterceptor'
this = {ContactsPresenterTest@1808} 
 toothPickRule = {ToothPickRule@1814} 
 mContactsView = {ContactsView$MockitoMock$78838304@1820} "mContactsView"
 mUserModel = {UserModel$MockitoMock$889062427@1821} "mUserModel"
 mContactsDataSource = {ContactsDataSource$MockitoMock$120191758@1822} "mContactsDataSource"
 mContactsPresenter = null
mContactsPresenter = null
toothPickRule = {ToothPickRule@1814} 
 testModule = {ToothPickTestModule@1840} 
 scope = {ScopeImpl@1838} "testScope:1495608502\r\nProviders: [com.tapptic.business.UserModel,....features.contacts.ContactsView...net.api.ContactsDataSource,toothpick.Scope]\r\nUnbound providers: []\r\n"
```

**Comment by stephanenicolas** [comment]
But ca you debug the call to TP.inject and see what is going on ?

2017-04-28 20:31 GMT+02:00 Fabio Grumiro <notifications@github.com>:

**Comment by fabiogrum** [comment]
The memberInjector is always null. 
The currentClass contains ContactsPresenterTest, then Object and then null.

 ```
 @Override
  public <T> void inject(T obj, Scope scope) { obj: ContactPresenterTest@1810 scope: "testScope:739333799\r\nProviders: [...UserModel,...ContactsView, tootpick.Scope]\r\nUnbound providers: []\r\n"
    Class<? super T> currentClass = (Class<T>) obj.getClass();
    do {
      MemberInjector<? super T> memberInjector = MemberInjectorRegistryLocator.getMemberInjector(currentClass); memberInjector: null
      if (memberInjector != null) {
        memberInjector.inject(obj, scope); memberInjector: null onj: ContactsPresenterTest@1810 scope: "testScope:739333799\r\nProviders: [...UserModel,...ContactsView, tootpick.Scope]\r\nUnbound providers: []\r\n"
        return;
      } else {
        currentClass = currentClass.getSuperclass(); currentClass: "...ContactsPresenterTest"
      }
    } while (currentClass != null);
  }
}
```

**Comment by stephanenicolas** [comment]
The issue is on this line:
```groovy
    annotationProcessor 'com.github.stephanenicolas.toothpick:toothpick-compiler:1.0.6'
```

It looks like the `annotationProcessor` scope doesn't call annotation processors for tests sources, but only for main sources.

If you wanna use annotation processoing in tests, you should use the [apt](https://bitbucket.org/hvisser/android-apt) plugin. It provides an `apt` and `testApt` scope which allow to use annotation processors in tests too.

**Comment by stephanenicolas** [comment]
I just filled an issue on Android Dev tools for this: https://issuetracker.google.com/issues/37781142

**Comment by dlemures** [comment]
@fabiogrum , you need to provide the scope name to the ToothpickRule:

```java
@Rule public ToothPickRule toothPickRule = new ToothPickRule(this, "scopeUsedToBindTheMocks");
```

**Comment by fabiogrum** [comment]
I already tried to give a scope name to the ToothpickRule. It's just a string, right? I don't have to create a scope?

**Comment by dlemures** [comment]
Could I see the piece of code where you inject ContactsPresenter (in your prod code, no test)? 
So I can answer the question properly.

**Comment by fabiogrum** [comment]
The ContactsPresenter is a class. In the prod code I don't inject it. I inject only the members. 

```
public class ContactsPresenter extends MvpRxBasePresenter<ContactsView> {

    private final static String TAG = "ContactsPresenter";

    @Inject
    UserModel mModel;
    @Inject
    ContactsDataSource mContactsDataSource;

    private Disposable mDisposable;

    @Inject
    public ContactsPresenter() {}

    public ContactsPresenter(Scope viewScope) {
        mDisposable = null;
        Toothpick.inject(this, viewScope);
    }
...
```

**Comment by fabiogrum** [comment]
Thank you again for your help. My test is working now with the `apt` plugin.

**Comment by dlemures** [comment]
Hi @fabiogrum .

Glad it is working.

Regarding the scope, in TP we always need a scope to make the injections. So you should provide an scope name inside the rule.
