### ISSUE TITLE
Make TP more robust with multiple rounds of annotations processing.

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#215]
We need to double check that TP can also be used when another annotation processor generates code using the @Inject annotations.

**Comment by lukoerfer** [comment]
Maybe I can help you guys on this one. I recently started working on an annotation processor and encountered the same warning as you did in #85, which was the reason for you to modify your annotation processor (see #158), which causes Toothpick to be incompatible with *AutoFactory* (see #187) and other annotation processors, that use `@Inject` and maybe other annotations in their generated code.

My (not yet fully tested) solution was to register a source file for generation at the start of annotation processing (e.g. in the first round or even in `init(...)`) via `Filer.createSourceFile(...)`, but do not write to that source file until the last round of annotation processing (when `roundEnv.processingOver()` evaluates to `true`):

	@Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        try {
            targetFile = processingEnv.getFiler().createSourceFile("package.and.Class");
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
    }
    
    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        // do something
        if (roundEnv.processingOver()) {
            try (Writer writer = targetFile.openWriter()) {
                // write to writer
            } catch (IOException ex) {
                throw new RuntimeException(ex);
            }
        }
        return false;
    }

In my (very limited) test, the warning did not appear, but the content of the generated file was exactly the same. Maybe this will help you in the future, as soon as I find out more I'll let you know.

**Comment by lukoerfer** [comment]
Sadly, it seems like Gradle does not compile source files generated in the last round of annotation processing at all. Whether it should, I found different statements, but the warning of the Java compiler states that the generated source will not be annotation processed, but it does not say anything about not being compiled. In my test, Gradle reported the missing class as error even before showing the warning on not annotation processing the generated file.

If I understand [this issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=329156) right, the Eclipse compiler now (from 2010 on) supports generation of source files in the last annotation processor round.

**Comment by stephanenicolas** [comment]
I close this issue as it's being adressed in the upcoming TP2
