### ISSUE TITLE
Incomplete FactoryRegistry generated when using Kotlin annotation processor

### ISSUE THREAD

**Issue by segabond** [stephanenicolas/toothpick#219]
When using `kapt` instead of android `apt`, partial project builds result into the corrupt FactoryRegistry class generated. It seems that `kapt` processes only files that are being currently complied. If some of the files are already complied from previous builds, they are not included into the `FactoryRegistry` class, resulting into the runtime crash

**Comment by stephanenicolas** [comment]
That is pretty true, TP registries do not support incremental compilation.

The only work around would be not to use registries, which is possible
using annotation processor options.

If there is way to get all files varying g the javax.inject annotations, it
would work, but they all need to be compiled for registries.

Note that registries are really for highly demanding apps, a conventional
app would not be much faster with registries.

Thx for reporting, we are open to PRs if you think you can find a way to
get that working.

Le mar. 30 mai 2017 20:35, Sergey Bondari <notifications@github.com> a
écrit :

**Comment by segabond** [comment]
Thank you for the explanation, if there is no reasonable workaround, we will use for now

```
android {
        compileOptions.incremental = false
}

```

**Comment by stephanenicolas** [comment]
I would add that even beyond registries, incremental annotation processing is broken. And this is not a TP issue only but a problem in java annotation processing, and in kotlin I am really not sure this can work well neither. Probably not.
