### ISSUE TITLE
Kotlin Sample

### ISSUE THREAD

**Issue by cs-victor-nascimento** [stephanenicolas/toothpick#220]
I've tried using this project on a kotlin Android application but could not make it work with the reflection free configuration. I tried:

```groovy
kapt {
    generateStubs = true

    arguments {
        arg("toothpick_registry_package_name", "myproject.package")
        arg("toothpick_registry_children_package_names", "toothpick.smoothie")
    }
}
```

and

```groovy
dependencies {
    // ...
    kapt 'com.github.stephanenicolas.toothpick:toothpick-compiler:1.0.6'
    compile "com.github.stephanenicolas.toothpick:toothpick-runtime:1.0.6"
    compile "com.github.stephanenicolas.toothpick:smoothie:1.0.6"
}
```

But the processor is not generating classes for the reflection free configuration.

**Comment by kelsos** [comment]
@cs-victor-nascimento Any more information? maybe I could help. I am using toothpick on a couple of kotlin Android applications with the reflection free configuration without any issue.

**Comment by cs-victor-nascimento** [comment]
Well, I am using the latest gradle plugin 3.0.0-alpha3. It won't read the apt options. Room's annotation processor is working normally but Toothpick's nope.

When I assemble with the `--info` flag I get a message that the options "toothpick_registry_package_name" and "toothpick_registry_children_package_names" were not read by any processor.

**Comment by kelsos** [comment]
@cs-victor-nascimento 

I am also using the alpha3 plugin on one project. Any idea which version of kapt are you using? 
The latest kapt version requires you to use ```apply plugin: 'kotlin-kapt'``` on your build.gradle ```generateStubs = true``` has been depercated.

**Comment by cs-victor-nascimento** [comment]
I am using the plugin. CUrrently I have enabled:

```groovy
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
```
The message is:

```
w: warning: The following options were not recognized by any processor: '[toothpick_registry_package_name, toothpick_registry_children_package_names, kapt.kotlin.generated]'
```

**Comment by cs-victor-nascimento** [comment]
My Kotlin version is: `1.1.2-4`

**Comment by cs-victor-nascimento** [comment]
@kelsos Could you link your project? Is it open source?

**Comment by stephanenicolas** [comment]
@Victor, you should not use the arguments:

arg("toothpick_registry_package_name", "myproject.package")
arg("toothpick_registry_children_package_names", "toothpick.smoothie")


Then it should work. You cannot use registries with Kotlin's incremental apt.


2017-06-09 13:29 GMT-07:00 Victor Oliveira Nascimento <
notifications@github.com>:

**Comment by cs-victor-nascimento** [comment]
Not use the arguments? 

Tried and it did not work. But I think this is the way to pass arguments to the processors. Anyway, my FactoryRegistry and MemberInjectorRegistry are not being generated.

I followed the samples and [this](https://github.com/stephanenicolas/toothpick/wiki/Factory-and-Member-Injector-registries#example--simple-application) link.

**Comment by victor** [comment]
s/@victor/@cs-victor-nascimento/g

**Comment by stephanenicolas** [comment]
Sorry @cs-victor-nascimento , I was writing from my mails and don't get completion there.

So, with Kotlin, as you can't use registries, there should be no need for the arguments.

**Comment by cs-victor-nascimento** [comment]
Thanks @stephanenicolas! In that project you are not using the reflection free configuration, right?

I wanted the reflection free configuration :) 

I will try to debug my issues. In any case, it would be nice to have a Kotlin Sample with a reflection free configuration.

**Comment by cs-victor-nascimento** [comment]
Well, it worked \o/

My configuration was perfectly right from the beginning. The issue was that I had no classes annotated with either `@Inject` nor anything. So the processor was not being called upon. I think it is worth mentioning this in the README or in the wiki.

**Comment by stephanenicolas** [comment]
Do you mind to write the text you would like us to add ?

2017-06-10 7:29 GMT-07:00 Victor Oliveira Nascimento <
notifications@github.com>:

**Comment by cs-victor-nascimento** [comment]
@stephanenicolas sure!

In [this](https://github.com/stephanenicolas/toothpick/wiki/Factory-and-Member-Injector-registries#setting-up-the-registries) part of the wiki you have:

> 
> Setting up the registries
> 
> Toothpick generates the registries at the same time it generates the factories and member injectors. As a developer using Toothpick, you need to
> 
> -  configure the package into which the annotation processor will generate the registries for a given compilation unit (the application and each library);
> -  inform the toothpick annotation processor of possible dependency of your compilation unit : toothpick will need to know where to find the registries for each of them.

I'll add something like:

> Notice that for the annotation processor to generate these classes, your project must already contain at least one class with an annotation that Toothpick's processor is marked to process. If you don't have any class annotated with `@Inject` or the other annotations, then Toothpick's processor will simply be skipped.

Also, in order to enhance the documentation, I think there should be some more pages to the wiki:

- **Getting Started**: an obvious one that I was surprised it is missing. It should provided a step by step guide to configuring an application.
- **Kotlin setup**: which would only show how to use kapt with argumets (currently not a very famous option IMHO).
- **Testing**: there is currently only a link to an implementation in the README. 
- **Smoothie library**: there is but a few words about what it does.

Perhaps it is only a matter of creating a README in those submodules' roots. I could propose some initial content in a PR if you agree that this is a good direction.

I think a gh-pages with JavaDoc hosting and some other goodies would greatly enhance the experience of getting acquainted with the project.

**Comment by juanvimartinez** [comment]
thanks @cs-victor-nascimento for your comment about having at least one class with an annotation to be processed by Toothpick, I was having the same error that you reported a year ago while setting up my project from the scratch and it was driving me crazy that it wasn't even building with an empty activity.

@stephanenicolas it could be a really good idea to include in the wiki the texts that @cs-victor-nascimento wrote for you, as well as to add the mentioned wiki pages.
