### ISSUE TITLE
NoClassDefException when working with Room

### ISSUE THREAD

**Issue by cooperkong** [stephanenicolas/toothpick#226]
Hi, I'm facing this weird issue, not sure if it related with TP or Room.
Basically this line throws Exception
```bind(InputMethodManager.class).toProviderInstance(() -> (InputMethodManager) application.getSystemService(INPUT_METHOD_SERVICE));```

```
java.lang.NoClassDefFoundError: Failed resolution of: Lau/com/abc/android/common/injection/ApModule$$Lambda$1;
```

However, if I remove all Room related dependencies. App works fine.

PS: Commented out that binding also works.

**Comment by stephanenicolas** [comment]
It can depend on so many things. Do you use retro lambda ? Which SDK etc.
And it could also be a decent issue..

For sure, it s not related to TP and it s proven by the fact that keeping
TP it works.

To investigate this, compile your app and use javap to look at what the
mandatory class is doing.

But it s gonna be hard if you are not familiar with byte code. What you
could try, more easily,is not to use a lambda but a full class or an
anonymous class.

**Comment by cooperkong** [comment]
Hi @stephanenicolas 
It was originally a normal java class, and it was throwing same NoClassDefException.
So that means it may not relate to retro-lambda I suppose.

**Comment by stephanenicolas** [comment]
I don't see how this can be related to TP. I am closing the issue.
