### ISSUE TITLE
Allow to reset a single scope for integration tests

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#232]
blah blah.. context. Link this PR to the original issue, explain the integration test context where the application is recycled during multiple integration tests.

TODO:
* [x] `reset` --> `resetUnBoundProviders` (this api change is not part of the public api, so version change can still be y+1 in x.y.z.
* [x] create a `reset` method that resets the internal scope state : `mapClassesToNamedBoundProviders` + `mapClassesToUnNamedBoundProviders` + `hasTestModules = false` + `isOpen = true` + `scopeAnnotationClasses`.
* [x] provide a snapshot of 1.1.0 for Cody to try.
* [x] add a wiki page to explain how to use this feature for integration tests (moved to https://github.com/stephanenicolas/toothpick/issues/255)
* [x] a sample integration test (#242)
* [x] link the wiki page from the issue where the ROOT_SCOPE workaround was first suggested. 
Subtask assigned to cody. We will add him as a TP contributor when PR is RTM.
* [x] internal to GRPN: kick off integration tests api calls mocking project + notify matthijs.

**Comment by dlemures** [comment]
https://github.com/stephanenicolas/toothpick/pull/234 (1, 2 & 3)

**Comment by stephanenicolas** [comment]
As an update on this topic, the test orchestrator allows to get a new app instance for every instrumentation test: https://developer.android.com/training/testing/junit-runner.html#using-android-test-orchestrator
