### ISSUE TITLE
Dealing with scope states on process death

### ISSUE THREAD

**Issue by GisoBartels** [stephanenicolas/toothpick#243]
Currently I use a custom scope to start a user flow in an Android app and I bind a parameter, defined by the item the user has clicked on. So my scope tree looks like `App -> UserFlow -> Activity`. In subsequent activities I just have to take the UserFlow scope, to get the needed bindings.
But if a process death occurs and a sub activity is recreated, I cannot rely on just taking the UserFlow scope, because its state is also gone. I have to recreate the the whole tree, which means every scope user has to know all ancestors of the UserFlow scope including all bindings to correctly recreate the whole scope tree.
This gets pretty bloated, having the pass this information to all activities.
Is there any recommended way to deal with this situation? I mean besides stopping to use activities for navigation ;) Or am I just doing it wrong, by trying to have dynamic bindings?

**Comment by dlemures** [comment]
Hi @GisoBartels ,

What do you mean by:
> I have to recreate the the whole tree, which means every scope user has to know all ancestors of the UserFlow scope including all bindings to correctly recreate the whole scope tree.

Could you provide some code?

**Comment by stephanenicolas** [comment]
Issue is orphan, I close it.

**Comment by GisoBartels** [comment]
I finally found some time to create an example project:
https://github.com/GisoBartels/toothpick-scope-on-process-death

You can reproduce the problem by  going to second or third activity, putting the app into background and then kill the process. After reopening from task switcher, the scope tree is gone.

**Comment by GisoBartels** [comment]
@dlemures: any ideas?

**Comment by the-rs** [comment]
@GisoBartels @stephanenicolas any solutions or workarounds? It could be reproduced by minimizing an app into background, then opening a task switcher, rotating screen several times, and then reopening the app from task switcher. I get an exception that there's no bindings provided (possibly all the scopes are being destroyed).
