### ISSUE TITLE
Kotlin: compilation error after any change

### ISSUE THREAD

**Issue by romansl** [stephanenicolas/toothpick#245]
Demo project: https://github.com/romansl/KotlinWeather

Environment: 
```
Toothpick: 1.0.8
Kotlin: 1.1.4-3
Andoird Studio: 2.3.3
Android gradle pugin: 2.3.3
Gradle: 3.3
Instant run: enabled
```

How to reproduce:
1. Open Weather.kt
2. Add variable val ggg: Int = 1
3. Got compilation error: `error: cannot find symbol`

```
D:\Projects\KotlinWeather\app\build\generated\source\kapt\debug\weather\ekamp\com\weatherappkotlin\FactoryRegistry.java:32: error: cannot find symbol
      return (Factory<T>) new weather.ekamp.com.weatherappkotlin.presenter.LandingPresenter$$Factory();
                                                                          ^
  symbol:   class LandingPresenter$$Factory
  location: package weather.ekamp.com.weatherappkotlin.presenter
```

**Comment by stephanenicolas** [comment]
You have to disable incremental compilation in kapt. Kapt incremental
annotation processing will break with annotation processors that generate a
single file out of multiple source files (like TP, dagger, henson, and some
auto value extensions, and probably many others).

https://stackoverflow.com/questions/36740100/disable-incremental-build-for-kapt

2017-09-18 3:08 GMT-07:00 Roman Leukin <notifications@github.com>:

**Comment by stephanenicolas** [comment]
Also, another workaround is not to use TP registries but to use reflection. For most apps, you won't see the difference.

**Comment by romansl** [comment]
It does not help:
```
kotlin.incremental=false
```

https://github.com/romansl/KotlinWeather/commit/89b7c7a08bc25d79aca72315447b0b8d4ff119dc

**Comment by lassem** [comment]
I would like to keep the incremental compilation, but removing our registry configuration will yield a warning saying `warning: No option -Atoothpick_registry_package_name to the compiler. No registries will be generated.` and we're treating warnings as errors (`-Pwerrror`).

Can you provide some mechanism that will allow us to specifically run without registries and not get this warning?

**Comment by romansl** [comment]
If I disable TP registries, then I got runtime error.
