### ISSUE TITLE
Need a way to effectively disable warning

### ISSUE THREAD

**Issue by lassem** [stephanenicolas/toothpick#246]
Due to kotlin incremental compilation (that we want to keep) and us treating warnings as errors, we need a way to silence the `warning: No option -Atoothpick_registry_package_name to the compiler. No registries will be generated.`-warning.

I'm thinking a new configuration option explicitly stating that we're running without registries.

**Comment by stephanenicolas** [comment]
That's a good idea. Do you wanna issue a PR ? Or maybe just using the same flag but with a special value like "no registry" <<-- pick a value that can't be a package.

**Comment by stephanenicolas** [comment]
TP 2 doesn't use registries any more.
