### ISSUE TITLE
Basic explanation required about Providers

### ISSUE THREAD

**Issue by afaucogney** [stephanenicolas/toothpick#247]
1/ Even is the question may be see as a bit theoritical, I would like to know exactly the purpose of Providers in a general manner and for ToothPick ?

2/ When we see this code in Smoothie:
`bind(FragmentManager.class).toProviderInstance(new SupportFragmentManagerProvider(activity));`

What is the difference with:
`bind(FragmentManager.class).toInstance(((FragmentActivity) activity).getSupportFragmentManager());`
So why there is a need for the provider

3/ And finally, if provider is required for any reason (I'm sure of that, but I wait reason) as Toothpick intended to reduce the boilerplate, this is a real pain to write all those Providers
Why not giving the possiblity to generate simple providers like that:

`bind(FragmentManager.class).toInstanceProvider(((FragmentActivity)activity).getSupportFragmentManager());`

would generate the provider like this:

```
public class SupportFragmentManagerProvider implements Provider<FragmentManager> {
  Activity activity;

  public SupportFragmentManagerProvider(Activity activity) {
    this.activity = activity;
  }

  @Override
  public FragmentManager get() {
    return ((FragmentActivity) activity).getSupportFragmentManager();
  }
}
```

Thanks for helping me to better understand DI and TP.

**Comment by stephanenicolas** [comment]
@afaucogney Sorry for the delay in answering. Here are some answers.

1) `Providers` in DI are entities that know how to produce instances. They are used to "provide" the instances when you request an injection:
```java
   class ElectricCar {
     @Inject Engine engine;
     @Inject Body body;
     ....
   } 
```
Here, a TP user requests 2 injections (an `Engine` and a `Body`). DI has 2 different problems to solve: 
1. creating the instances of the `Engine` and `Body` classes, and
2. assigning them to the fields of an instance of `ElectricCar`. 

The second problem is solved in TP by generated code (Member Injectors), while the first problem is solved by providers.

A provider is the entity that has the knowledge to create objects of a given type. In TP, internally, all things (i.e. scopes) are represented by hashmaps that link a given injected type (e.g. `Engine` or `Body`) to an internal provider: an entity that knows how to produce instances (resp. of `Engine` and `Body`). These internal providers use generated factories by default.

But they can be replaced by a custom provider in cases where the creation of instances cannot be automated, for instance if you need to pass some special parameters to the classes you create, or return special subclasses. To tell TP to use these providers, you bind them to injected classes inside a TP module:
```java
scope.install( new Module() {{
   bind(Body.class).toProviderInstance( new Provider<Body>() {
     public Body get() {
        return new PlasticBody("Polypropylene");
     }
  })
}});
```

Another usage of Providers defined by [JSR 330](http://javax-inject.github.io/javax-inject/api/javax/inject/Provider.html) is that you can directly inject a `Provider`. This is less current and often considered a design flaw: 
```java
   class ElectricCar {
     @Inject ElectricCar(Provider<Seat> seatProvider) {
       Seat driver = seatProvider.get();
       Seat passenger = seatProvider.get();
       ...
     }
   } 
```

2. There is no difference between:
```java
bind(FragmentManager.class).toProviderInstance(new SupportFragmentManagerProvider(activity));
```
and
```java
bind(FragmentManager.class).toInstance(((FragmentActivity) activity).getSupportFragmentManager()); 
```

If you go again through my first answer, you will understand that internally, anyway, all bindings are gonna be converted to an internal provider. In the first case, the internal provider uses an instance of `SupportFragmentManagerProvider` to create the `FragmentManager`, and in the second case the internal provider will directly know about an instance of `FragmentManager` to recycle.
But both of these bindings will indifferently return the same instance of `FragmentManager`.

3. There is no need for a provider per say, both forms are equal. We have created providers to get more isolation of the code related to creating special entities. It's cleaner than having all code in the module. But again, it ends up to producing the same instances.

TP is a very free system and up to you to use providers or not. Our best practices tell us that providers are useful to isolate a non trivial object creation logic.
