### ISSUE TITLE
@Inject not working

### ISSUE THREAD

**Issue by sysint64** [stephanenicolas/toothpick#249]
Hello, i'm new in DI. I'm tying to make dependency in class e.g. `BookPresenter` like this:
```Java
class BookPresenter {
    @Inject BooksService service;

    public BookPresenter(BookView bookVIew, Context context) {
       ...
    }
}
```

An in my `BookActivity`:
```Java
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_books);
    
    if (presenter == null) {
        final BookVIew view = this;
        Scope scope = Toothpick.openScopes("App", "ChatRoomActivityOld");
        scope.installModules(new Module() {{
            bind(BooksService.class).toInstance(new BookServiceHttpImpl("my cateory"));
        }});

        presenter = new BookPresenter(this, this);
    }
}

@Override protected void onDestroy() {
    super.onDestroy();
    presenter.onDestroy();
    Toothpick.closeScope("ChatRoomActivityOld");
}
```

now `BookServiceHttpImpl` instance is accessable and I can get instance for service if I'll write something like this: `service = scope.getInstance(BooksService.class);` it will be working, but annotated field with `@Inject` - service was not assigned automatically.

**Comment by stephanenicolas** [comment]
There are a few things to change in your PR: 

* for scope names, we recommend using activities and application instances: `openScopes(getApplication(), this)`
* the problem you have is that BookPresenter will be injected only if it is created by TP. TP is not magic. Either you instanciate your BookPresenter by injecting (declare it as field in the activity, and do inject(this) in the activity, which is recommended) or get the instance of book presenter via TP (TP.getInstance()). 

But in your case, you are using constructors that require parameters. So, either you inject these parameters (create binding for book view and activity, then add @Inject to your constructor, recommended). Or you can also make your book presenter an entry point (not recommended) and call `scope.inject(this)` in the book presenter constructor.

As you see, it's a endless suite of recipe if you don't understand how TP / DI work. I would recommend reading the manuel watching a few slides / talk about it.
