### ISSUE TITLE
Add documentation for unit tests

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#254]
https://github.com/stephanenicolas/toothpick/wiki/Unit-Testing

**Comment by perpetuatingcuriosity** [comment]
Any chance we will see this soon?

**Comment by perpetuatingcuriosity** [comment]
@dlemures Is this in progress?

**Comment by dlemures** [comment]
Hey @perpetuatingcuriosity ,

Next week i'll have time to work on this.

**Comment by dlemures** [comment]
Please review: https://github.com/stephanenicolas/toothpick/wiki/Unit-Testing

**Comment by stephanenicolas** [comment]
👍
