### ISSUE TITLE
1.1.0 Generated annotation not available on Android

### ISSUE THREAD

**Issue by RocketRider** [stephanenicolas/toothpick#258]
In the Version 1.1.0  the Class "javax.annotation.Generated" can not be resolved on Android.
Relates to: #256

**Comment by stephanenicolas** [comment]
Thx @RocketRider , you need to add 
```java
provided 'javax.annotation:jsr250-api:1.0'
```
(or compileOnly if you use GAP3). We will add the dependency to the generated core lib.

**Comment by stephanenicolas** [comment]
@RocketRider , do you wanna give a try to our latest snapshot. It contains the PR above. Versions 1.1.1-SNAPSHOT

**Comment by stephanenicolas** [comment]
We are releasing 1.1.1 which fixes the issue.
