### ISSUE TITLE
Update wiki of named bindings

### ISSUE THREAD

**Issue by RocketRider** [stephanenicolas/toothpick#259]
https://github.com/stephanenicolas/toothpick/wiki/Modules-&-Bindings#namedqualified-bindings

The wiki entry about named bindings should be updated.
- Replace TootPick with ToothPick
- ToothPick.getInstance() does not exist
- add sample for named annotation

**Comment by stephanenicolas** [comment]
Thx, I just updated the docs.

**Comment by RocketRider** [comment]
I mean a sample with "@named" for a field or constructor.

Like this:
```
@Inject
@Named("foo")
public IFoo foo;
```
