### ISSUE TITLE
Gradle module only provides Singletons, MemberInjectorRegistry is not created

### ISSUE THREAD

**Issue by RocketRider** [stephanenicolas/toothpick#264]
I am having an android app with a few gradle/library modules. I am using the reflection free approach. 
One module is only providing Singleton classes. No Injection is needed in that module.
So TP does not generate a MemberInjectorRegistry.
But the Registry from the app module needs the registry:
`addChildRegistry(new com.xx.yy.common.MemberInjectorRegistry());`

**Comment by stephanenicolas** [comment]
@RocketRider you could still add an `@Inject` annotation in your module somewhere to get a member injector. Of course this is a workaround. We will do our best to fix the issue, but we would also be glad to accept a PR ;)

**Comment by RocketRider** [comment]
Thank you.
yes I am using this workaround at the moment.

**Comment by stephanenicolas** [comment]
This is gonna be obsolete in TP2, there are no regisitries any more.
