### ISSUE TITLE
How inject dependency by Constructor with parameter if the parameter is not available

### ISSUE THREAD

**Issue by afaucogney** [stephanenicolas/toothpick#267]
Let's have a simple Logger:

```
class LogString1 @Inject constructor(var text: String) {
    fun execute() {
        Log.v(this.toString(), text)
    }
}
```

When I inject the LogString1, I need to have text:String available. How to do if it is not available ?

Without Injection

```
class Activity2 : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        var activityScope = Toothpick.openScopes(application, this)
        activityScope.installModules(SmoothieActivityModule(this), Activity2Module(this))
        Toothpick.inject(this, activityScope)

        setContentView(R.layout.activity_1)

        fab.setOnClickListener { view ->
            LogString1(Math.random().toString()).execute()
        }
    }
}
```
I didn't find any way to do it cleanly

Only by doing that:

```
class LogString @Inject constructor() {
  
  var text: String? = null

    fun execute() {
        text?.let {

        Log.v(this.toString(), text)
        }
    }
}
```

With the following activity

```
class Activity2 : AppCompatActivity() {

    @Inject
    lateinit var log : LogString

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        var activityScope = Toothpick.openScopes(application, this)
        activityScope.installModules(SmoothieActivityModule(this), Activity2Module(this))
        Toothpick.inject(this, activityScope)

        setContentView(R.layout.activity_1)

        fab.setOnClickListener { view ->
            log.text = Math.random().toString()
            log.execute()
        }
    }
}
```

Is there a better or more elegant way to do that, as I think this is a common case ?

**Comment by stephanenicolas** [comment]
There are basically 2 things you can do, and this is not related to TP per say but more to DI. Basically all DI engines can only figure inject parameters if they know how to create these parameters (either there is a binding or there is a constructor that let's the DI lib create this entity).

The 2 workarounds are:
1) Assisted injection: (Guice has a longer explanation on the net)
```java
class Foo {
  String s;
  Foo(String s) {
   ...
  }
}

//you have to create a factory yourself to handle
//the params that DI can't guess
class FooAssistedFactory {
   Foo createFoo( String s) {
     return new Foo(s);
   }
}

//then use it:
 @Inject FooAssistedFactory factory;
 ...
 factory.createFoo("Hey !");
```

2) make Foo a new DI root:
```java
 class Foo {
  String s;
  @Inject OtherDep dep;

   Foo(String s, Scope scope) {
     this.s = s;
     //if you need other dependencies to be injected
     TP.inject(this, scope);
   }
 }

//use it
new Foo("hey !"); //<-- would inject other dependencies.
```

**Comment by stephanenicolas** [comment]
I closed the issue as it's pretty much all what there is to say, but feel free to reopen if you need more in-depth explanation about it.

**Comment by afaucogney** [comment]
@stephanenicolas thanks for the reply, that's clearer in my mind now.

- As I can feel, 1/ may probably be used in more general case to 2/, because it may happen needing injection of a couple of object, so I assumed 2/ in not anymore possible, isn't ?

- Without any experience on this, but does 1/ is not such bound that a DI framework like TP could handle it by itself ? with something like:
@AssistedInjected(String) Foo fooAssistedFactory
and TP would generate the factory. Doesn't make any sens ?

**Comment by afaucogney** [comment]
@stephanenicolas 
in addition when you say:
> either there is a binding 

it would not solve the fact that the "String s" is not available at the inject time. Should we /How ca we  postpone the injection for a dep, like in my exemple:

```
class Activity : AppCompatActivity() {

   @Inject
    lateinit var log : LogStringBinding

   var text : String

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        var activityScope = Toothpick.openScopes(application, this)
        activityScope.installModules(SmoothieActivityModule(this), object : Module() {
            init {
                bind(LogStringBinding::class.java)
                bind(String::class.java).withName("random").toInstance(random)
            }
        })
        Toothpick.inject(this, activityScope)

        setContentView(R.layout.activity_1)
fab.setOnClickListener { view ->
           text = Math.random().toString()
           // now text is available, injection can happen safely
          Toothpick..... // inject dep relative to "random"
           log.execute()
        }

```
and the LogString

```
class LogStringBinding @Inject constructor(@Named("random") var text: String) {

    fun execute() {
        Log.v(this.toString(), text)
    }
}
```

**Comment by afaucogney** [comment]
Just to help other here is the link about assistedInject with Guice https://github.com/google/guice/wiki/AssistedInject

I also read in the TP FAQ that it will probably not support AssistedInjection natively.

**Comment by stephanenicolas** [comment]
TP doesn't offer assisted injection and we don't plan to support it as we want to stick to JSR 330 and limit the complexity of the library.
