### ISSUE TITLE
Include Proguard Configuration in Smoothie Library

### ISSUE THREAD

**Issue by kingargyle** [stephanenicolas/toothpick#270]
Unfortuantely I'm at work currently otherwise I'd submit a pull request, but it would be nice, if you are using the Smoothie library that it include a default configuration for proguard.   Here is a samle proguard file that I did manage to get working with our app.   This works with Kotlin generated reflection free code from Toothpick as well as normal java code.

<pre>
# Note that if we could use kapt to generate registries, possible to get rid of this
-keepattributes Annotation
# Do not obfuscate classes with Injected Constructors
-keepclasseswithmembernames class * {
    @javax.inject.Inject <init>(...);
}
# Do not obfuscate classes with Injected Fields
-keepclasseswithmembernames class * {
    @javax.inject.Inject <fields>;
}
# Do not obfuscate classes with Injected Methods
-keepclasseswithmembernames class * {
    @javax.inject.Inject <methods>;
}
-keep @android.support.annotation.Keep class *
-keep @javax.inject.Singleton class *
-dontwarn javax.inject.**
-dontwarn javax.annotation.**
-keep class **$$Factory { *; }
-keep class **$$MemberInjector { *; }

-adaptclassstrings
-keep class toothpick.** { *; }
</pre>

One thing that a person will need to add on their own is the keep for the FactoryRegistry class that is generated as part of their application.   I was going to put this information on the Wiki, but don't have edit rights to the wiki.   Long term it should be automatically included in the smoothie library so it gets added automatically when using release build with proguard.

**Comment by stephanenicolas** [comment]
This is addressed in TP 2.
