### ISSUE TITLE
What is "smoothie"?

### ISSUE THREAD

**Issue by tir38** [stephanenicolas/toothpick#271]
Is Smoothie the name of a sample project or is it part of the library? It's very confusing. For example:

https://github.com/stephanenicolas/toothpick/blob/master/smoothie-sample/src/main/java/com/example/smoothie/SimpleApp.java

How does this class live in ` com.example.smoothie` package AND depend on `import toothpick.smoothie.module.SmoothieApplicationModule`?

**Comment by stephanenicolas** [comment]
Smoothie is an android helper module for Toothpick. It's part of TP.

2017-12-06 10:12 GMT-08:00 Jason Atwood <notifications@github.com>:

**Comment by tir38** [comment]
Ok. Can you add some clarifying documentation to either wiki or README?

**Comment by stephanenicolas** [comment]
Thx @tir38 , this is fixed by : https://github.com/stephanenicolas/toothpick/commit/35a5b974a2f0623852cea0b1ab13b3d16f6d7848
