### ISSUE TITLE
Add Bind annotation for tests

### ISSUE THREAD

**Issue by dpreussler** [stephanenicolas/toothpick#276]
Toothpicks test rule automatically maps field annotated with @Mock to fields needed to be injected.
Two problems:
1st)

in Kotlin most people dont use annotations anymore as it's easier to mock withou:
```
val viewModel = mock<CountdownViewModel>()
```
using @Mock would mean writing:
```
@Mock lateinit var viewmodel: CountdownViewModel
```

2nd)
As its a very conventient shortcut it would be nice to use even for non mocks, but adding @Mock is confusing:
```
@Mock val viewmodel = CountdownViewModel(Schedulers.trampoline())
```

**Comment by dpreussler** [comment]
for now I solved it in my code with:
```
typealias Bind = Mock
```
but thats just a workaround as behind it still annotation that Mockito or Easymock might want to fill

**Comment by stephanenicolas** [comment]
We are still considering doing a KTP (#211).

**Comment by dlemures** [comment]
On TP3, we have added support for it. Any field annotated with an annotation containing `Spy` (@Spy, @SpyK, ...) will be also used to create a test binding.
