### ISSUE TITLE
A method to tell whether a scope has modules installed or not

### ISSUE THREAD

**Issue by slamduncn** [stephanenicolas/toothpick#277]
Before installing modules to a Scope, it would be useful if we could check whether they have already been installed. A non-ideal workaround would be to do a test injection such as:
```
public void hasModules(Scope scope) {
  try { 
     scope.getInstance(Foo.class);
     return true;
  } catch(Exception ex) {
       return false;
  }
}
```

**Comment by stephanenicolas** [comment]
It's an interesting addition, I will add it to 2.0 roadmap. Though, I wanna mention that this is just an optimisation as re-installing bindings/modules on a scope that already has bindings does actually nothing.

**Comment by terrakok** [comment]
It will be very usefull! After rotate screen on android we need check savedState is not null for prevent scope initialization.

**Comment by terrakok** [comment]
For example: [prepareScope()](https://gitlab.com/terrakok/gitlab-client/blob/develop/app/src/main/java/ru/terrakok/gitlabclient/ui/issue/IssueFlowFragment.kt#L46)

**Comment by stephanenicolas** [comment]
Is it really that bad to check the saved instance state ? I mean such a
method would have a tricky semantics, scopes inherits bindings.. you're
gonna trade a method call for another one, what is the gain ?

**Comment by dmitrynerd** [comment]
We use scopes for screens with child fragments to share dependencies among children. For now it's not easy to determine do we have already opened scope with required dependencies or not.
In case when system killed our app in background we must reopen scope and install modules again. But in case of screen rotation our scope remains in application and we don't need to reopen it.

It would be very useful to check in `onCreate()` do we have required modules or not.

**Comment by terrakok** [comment]
After rotation: bundle != null but scope initialized.
After process death: bundle != null but scope doesn't initialized

**Comment by stephanenicolas** [comment]
Right. Do you wanna contribute a PR ?


Le mer. 28 nov. 2018 à 22:11, Konstantin <notifications@github.com> a
écrit :

**Comment by terrakok** [comment]
#317 
@stephanenicolas  I done but It was easy.... I think that I don't understand something

**Comment by dlemures** [comment]
TP 2.1.0 has been released with this change included.
