### ISSUE TITLE
Using toothpick with registry in lib doesn't build

### ISSUE THREAD

**Issue by afaucogney** [stephanenicolas/toothpick#278]
I'm using TP in a project that own a android module, which hold class that need TP. This is in kotlin.
With reflexion, everything works well.

This is part of the build.gradle off the app:

```
    kapt {
        arguments {
            arg("toothpick_registry_package_name", "com.afaucogney.yope.app")
            arg("toothpick_registry_children_package_names", "com.afaucogney.yop")
        }
    }
```

Nothing is inside the build.gradle of the lib

And the config inside the App:

```
    Toothpick.setConfiguration(Configuration.forProduction().disableReflection())
        MemberInjectorRegistryLocator.setRootRegistry(com.afaucogney.yope.app.MemberInjectorRegistry())
        FactoryRegistryLocator.setRootRegistry(com.afaucogney.yope.app.FactoryRegistry())
```

I do use smoothie, but I do not think some code is needed for it.

MemberInjectorRegistry and FactoryRegistry are generated for the app, but nothing is generated for the lib.

Someone may help me where/how investigate my issue ?

**Comment by pshmakov** [comment]
> Nothing is inside the build.gradle of the lib
This is the problem. Annotation processing is not run for the lib module, so nothing is generated. 
You need to configure annotation processor in the lib's build.gradle as well, with arg("toothpick_registry_package_name", "com.afaucogney.yop")

**Comment by afaucogney** [comment]
sorry, after re-reading the wiki this information was well written in https://github.com/stephanenicolas/toothpick/wiki/Factory-and-Member-Injector-registries with:

> The same would apply to lib1 has it doesn't depend on any library using Toothpick.

As this text wasn't well highlighted (or with code), I just didn't make enough attention !
