### ISSUE TITLE
Wiki: broken links

### ISSUE THREAD

**Issue by iamworkingasrudenko** [stephanenicolas/toothpick#279]
In the bottom of wiki article pages the links "Modules & Bindings" and "Scoped & Unscoped Bindings" are red, though the pages are accessible from the navigation sidebar in the right.
Example here:
https://github.com/stephanenicolas/toothpick/wiki/Scopes#links

**Comment by stephanenicolas** [comment]
Thx @iamworkingasrudenko . I fixed them. Let me know if I missed any.
