### ISSUE TITLE
Add extension instead of Rule for Junit5

### ISSUE THREAD

**Issue by dpreussler** [stephanenicolas/toothpick#280]
Junit5 doesnt now rules anymore, it has the concept of extensions:
```
@ExtendWith(TraceUnitExtension.class)
```
http://www.baeldung.com/junit-5-migration

As people start using it, the support would be great as I have mixed tests now

**Comment by dpreussler** [comment]
this would be a draft of a kotlin version of an extension function
```
class InjectionExtension(val scopeName: String = MAIN_SCOPE): AfterEachCallback, BeforeEachCallback {

    private var testModule: ToothPickTestModule? = null
    private var scope: Scope? = null

    override fun afterEach(context: ExtensionContext?) {
        Toothpick.reset(Toothpick.openScope(scopeName))
    }

    override fun beforeEach(context: ExtensionContext?) {
        testModule = ToothPickTestModule(context?.testInstance!!.get())
        scope = Toothpick.openScope(scopeName).apply {
            installTestModules(testModule)
        }
    }
}
```

you would need annotations to read the Scope value though for passing the scope, see https://github.com/junit-team/junit5/issues/1135

**Comment by dpreussler** [comment]
addon: Junit 5.1 supports @RegisterExtension, with this the scope name could be set

**Comment by stephanenicolas** [comment]
This is addressed in TP2.
