### ISSUE TITLE
Is there a way to get the dependancies tree ?

### ISSUE THREAD

**Issue by afaucogney** [stephanenicolas/toothpick#281]
I would be interested to review the dependencies tree of my app. Is there a way to get it through a command or via an intermediate generated file ?

**Comment by dlemures** [comment]
Hi @afaucogney ,

I don't think we have any. 

However, If we decided to implement it, there is something to take into account: in TP you can wired things at runtime, making the whole process really flexible. This is carried out by using `bindings`:

```java
class MyActivity {
  @Inject A a;

  @Override
  public void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      Scope scope = Toothpick.openScope(scopeName);
      scope.installModules(new Module() {{
          bind(B.class).to(C.class);
      }});
     Toothpick.inject(this, scope);
}
```

```java
class A {
  @Inject B b;
}
```
```java
class C extends B {
}
```
Here we would report:
```
   MyActivity -> A -> B
```
However, the real tree at runtime would be:
```
   MyActivity -> A -> C
```

Would it be useful anyway?

**Comment by afaucogney** [comment]
@dlemures I understand your point. The best would be to have the real dependencies tree. When tp does generates registries, isn't enougth to build this tree ?

https://github.com/dvdciri/daggraph post-generates it. But I think during the pre-build processing TP need to know that tree. At least in your example it should, isn't it ?

**Comment by stephanenicolas** [comment]
The trees of TP exist only at runtime, we can't provide such a command. For now the only feature we provide is the ability to print scopes, but not an injection tree per say. 

Indeed, we have such a tool at Groupon, we will consider open sourcing it in the future. 
@dlemures ... :)

**Comment by dlemures** [comment]
We cannot generate the DAG at compile time. Closing.
