### ISSUE TITLE
Inject Presenter is null

### ISSUE THREAD

**Issue by gabrielnra** [stephanenicolas/toothpick#282]
I`ve tried everything to inject the presenter in activity but it still null:

**Activity:**

```

@Inject
    EventListPresenter presenter;

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Scope scope = Toothpick.openScopes(getApplication(), EventListPresenter.class, this);
        Toothpick.inject(this, scope);
}
```

**Presenter:**
```
@Singleton
public class EventListPresenter implements OSSubscriptionObserver {

    @Inject
    public EventListPresenter(LoginInteractor loginInteractor, NotificationInteractor notificationInteractor, EventListInteractor interactor, EventListView view, User currentUser, int lastPage, boolean sentRegisterIdToServer, List<SearchItem> items) {
        this.loginInteractor = loginInteractor;
        this.notificationInteractor = notificationInteractor;
        this.interactor = interactor;
        this.view = view;
        this.currentUser = currentUser;
        this.lastPage = lastPage;
        this.sentRegisterIdToServer = sentRegisterIdToServer;
        this.items = items;
    }
```

:data gradle
```
compile 'com.github.stephanenicolas.toothpick:toothpick-runtime:1.1.1'

    compile 'com.github.stephanenicolas.toothpick:smoothie:1.1.1'

    annotationProcessor 'com.github.stephanenicolas.toothpick:toothpick-compiler:1.1.1'
```

**Comment by gabrielnra** [comment]
Actually the documentation ia so poor for mvp implementation that is incredible someone can use it. Improove please!!

**Comment by dlemures** [comment]
Hi @gabrielnra ,

Do you still have the problem? 

Regarding the presenter being null, I cannot see any issue in the code. After calling `Toothpick. inject`, the presenter shouldn't be null. Have you defined any binding for `EventListPresenter.class`?

However, about the annotation used for the EventListPresenter `@Singleton`, you should be using an annotation attached to the intermediate scope and not singleton. The MVP use case is an [Scope Annotations](https://github.com/stephanenicolas/toothpick/wiki/Scope-Annotations#scope-annotations-and-scoped-bindings). The steps would be:

1. Define annotation
```java
@javax.inject.Scope
@Documented
@Retention(RUNTIME)
interface @EventListPresenterSingleton {}
```
2. Annotate your presenter with it
```java
@EventListPresenterSingleton
public class EventListPresenter implements OSSubscriptionObserver {
```
3. Use annotation as the intermediate scope name and inject
```java
Scope scope = Toothpick.openScopes(getApplication(), EventListPresenterSingleton.class, this);
Toothpick.inject(this, scope);
```
4. Remember to close the intermdiate scope when you don't need it anymore, probably inside onDestroy when the activity is finishing
```java
@Override
protected void onDestroy() {
  Toothtpick.closeScope(this); 
   if (isFinishing()) {
     Toothpick.closeScope(EventListPresenterSingleton.class);
   }
}
```

I guess that you are right and we could have a detailed explanation of the MVP use case in the wiki. Do you wanna open an issue for that?

**Comment by gabrielnra** [comment]
Yes please! I've being struggling to integrate, but, bad news. I couldn't do it. Is frustrating and I would love to be using it.

**Comment by dlemures** [comment]
Could you provide an example where I can see the issue? 

The only reasons I can think of:
1. You have a binding for EventListPresenter.class
2. TP.inject is not being called

**Comment by gabrielnra** [comment]
This piece of the article presented below helped me to figure out that scope should be applied in both application and activity. 

Updating the docs with something based on the article mentioned would be awesome!

Tks!


Article from: https://medium.com/@markchristopherng/migrating-off-roboguice-3-part-2-c06644d2d1ef


Toothpick
The final step involved implementing the Toothpick framework. This step took a bit longer than the other frameworks but overall went quite smoothly as I had previously road tested the framework on a sample project. The main concept in Toothpick revolves around scopes and creating a scope tree. I borrowed this definition from Stephanen Nicolas’s slides Migrate to TP from RG 4.

Scopes are:

a place to define bindings (via modules)
a place to recycle injected instances
Scopes can be used to:

inject dependencies into instances
getInstance of classes
Just like Roboguice 3, Toothpick also has modules that can be used to define bindings such as a particular class should be a singleton. These modules are then installed in a scope and used during the injection process.

A scope lower in the dependency tree can also be used to override a binding defined higher up in the scope tree. We used this feature in our Espresso tests to override the real objects with mocks.

Looking at our app we really only needed 2 scopes;

Application scope for defining global singletons and objects that access the ApplicationContext
Activity scope for defining objects that rely on the Activity Context.
The scope tree looked like this:

                     RootScope 
                        |
                     AppScope
                        |
                   ActivityScope
Your probably thinking why there are 3 scopes when I only mentioned 2. We found that when we updated our Espresso tests we needed the extra root scope to help with overriding the bindings with mocks as mentioned previously.

The application object was updated to install the module in the root scope and to create a scope tree as follows:

public class App extends Application {

    public static final String ROOTSCOPE = "rootscope";
    public static final String APPSCOPE = "appscope";
    
@Override
public void onCreate() {

    super.onCreate();
    context = this.getApplicationContext();

    Scope rootScope = Toothpick.openScopes(ROOTSCOPE);
    rootScope.installModules(new ApModule(this));

    Toothpick.openScopes(ROOTSCOPE, APPSCOPE);

    if (BuildConfig.DEBUG) {
        Toothpick.setConfiguration(Configuration.forDevelopment());
    }

}
Toothpick also has a really nice development feature which allows it to detect cyclic dependencies. When our app was failing to load, this feature proved useful in helping resolve this issue. Toothpick detected a cyclic dependency on startup and even printed out a nice graph showing where the issue was.

The migration involved replacing the Roboguice 3 injector with equivalent Toothpick injector throughout the app and also adding the Toothpick injector to all fragments and activities that were using injection. This update required removing the RoboContext from our services and updating our BaseActivity to extend from AppCompatActivity and our BaseFragment to extend from the support Fragment.

Roboguice

RoboGuice.getInjector(this).injectMembers(this);
Toothpick

Toothpick.inject(this, Toothpick.openScope(App.APPSCOPE));
Our application also extensively used the @ContextSingleton annotation that was popular with Roboguice 3. We noticed that we could replace the Context with the ApplicationContext in all our ContextSingleton classes except for one as these classes were either reading strings or accessing share preferences and did not require the Activity context.

For the one class that required an Activity context we injected this class in a new activity scope in the onCreate() method where it was being used:

@Override
protected void onCreate(Bundle bundle) {
    activityScope = Toothpick.openScopes(Application.ROOTSCOPE, Application.APPSCOPE, this);
    activityScope.installModules(new ActivityModule(this));

    super.onCreate(bundle);
}
When the activity is destroyed the scope also needs to be closed.

@Override
protected void onDestroy() {
    Toothpick.closeScope(this);
    super.onDestroy();
}
Conclusion
The migration from Roboguice 3 to the 5 new frameworks roughly took about 7–10 man days on our mid-size app. The app codebase is about 55K lines of code with another 20K lines of test code. Planning the migration and testing each framework meant the migration went relatively smoothly without encountering too many problems.

The migration was successful and during the migration we even managed to deliver other business features. There are many benefits to upgrading including improved performance, faster development (less boilerplate), happier developers and better maintainability.
