### ISSUE TITLE
Generated classes cause too many unchecked warnings

### ISSUE THREAD

**Issue by litmon** [stephanenicolas/toothpick#285]
Classes generated by toothpick cause unchecked warnings when my project build.
Sample generated code is as follows.

compile option:
https://github.com/litmon/ToothpickSample/blob/master/app/build.gradle#L30-L32

use `@Inject`:
https://github.com/litmon/ToothpickSample/blob/master/app/src/main/java/com/litmon/app/toothpicksample/MainActivity.kt

```
public final class FactoryRegistry extends AbstractFactoryRegistry {
  public FactoryRegistry() {
  }

  @Override
  public <T> Factory<T> getFactory(Class<T> clazz) {
    String className = clazz.getName();
    int bucket = (className.hashCode() & 0);
    switch(bucket) {
      case (0):
      return getFactoryBucket0(clazz, className);
      default:
      return getFactoryInChildrenRegistries(clazz);
    }
  }

  private <T> Factory<T> getFactoryBucket0(Class<T> clazz, String className) {
    switch(className) {
      case ("com.litmon.app.toothpicksample.MainActivity"):
      return (Factory<T>) new com.litmon.app.toothpicksample.MainActivity$$Factory();
      default:
      return getFactoryInChildrenRegistries(clazz);
    }
  }
}
```

`(Factory<T>) new com.litmon.app.toothpicksample.MainActivity$$Factory()` cause unchecked warning. This warning also cause in `MemberInjectorRegistry#getMemberInjectorBucket0()`.
So warning increases as factory class increases.

I want to suppress unchecked warnings.

**Comment by stephanenicolas** [comment]
TP 2.0 doesn't use registries anymore. Please re-open if the issue is present on other generated code.
