### ISSUE TITLE
Abstract classes injection

### ISSUE THREAD

**Issue by DomiBlaze** [stephanenicolas/toothpick#289]
I'm trying to use Room and Toothpick together. Because Room only has an abstract class accessible, I wrote a provider for it, but for some reason toothpick doesn't create a factory, I get the following error: 

`toothpick.registries.NoFactoryFoundException: No factory could be found for class <package>.AppDatabase. Check that the class has either a @Inject annotated constructor or contains @Inject annotated members. If using Registries, check that they are properly setup with annotation processor arguments.`

Annotating members inside abstract AppDatabase didn't lead to anything, constructor can't be annotated, and this is probably wrong anyway. I tried with reflection enabled and disabled, didn't help either

```
@Singleton @ProvidesSingletonInScope
class DataBaseProvider: Provider<AppDatabase> {
    @Inject lateinit var context: Context
    override fun get(): AppDatabase =
            Room.databaseBuilder(context.applicationContext,
                    AppDatabase::class.java, "database").build()

}
```
```
@Database(entities = arrayOf(Habbit::class, Category::class), version = 1)
abstract class AppDatabase : RoomDatabase() {
    abstract fun habbitDao(): IHabbitDao
    abstract fun categoryDao(): ICategoryDao
}
```

`bind(AppDatabase::class.java).toProvider(DataBaseProvider::class.java)`

**Comment by kelsos** [comment]
@DomiBlaze I am using room with toothpick successfully in to projects, without any issues.

Can you try injecting the *Application* to the provider's constructor? And then use the application as a context to create the Room instance?

```kotlin
class DataBaseProvider
@Inject 
constructor(private val application: Application): Provider<AppDatabase> {
}
```

**Comment by stephanenicolas** [comment]
@DomiBlaze <https://github.com/DomiBlaze> it should work. My guess is that
when you inject it, your context is not what you expect.
If you bind your AppDatabase in a module installed into the application
scope, make sure the scope you use for injection is the scope of your
application.

We will need to see the full stack trace to investigate further.

2018-04-20 0:04 GMT-07:00 Konstantinos Paparas <notifications@github.com>:

**Comment by DomiBlaze** [comment]
@stephanenicolas 
Yep, I used the wrong scope for injection, rookie mistake. Maybe it could be added to the error message? Something like `Check that injected scope is supposed to contain requested factory`.
Thanks!

**Comment by stephanenicolas** [comment]
Feel free to create a PR to enhance the appropriate error message.
