### ISSUE TITLE
Kotlin. Not able to call "to" method in module.

### ISSUE THREAD

**Issue by arkivanov** [stephanenicolas/toothpick#292]
Hello,

I ran into one annoying problem, here is the code snippet:

```
toothpick.config.Module

class MyModule : Module() {
    fun test(a: Class<*>, b: Class<*>) {
        bind(a).to(b)
    }
}
```

Problem here is that it actually calls extension method "to" which is used to create pairs and I can't avoid it. Event if I select proper method in auto-complete it still uses extension one. I believe there is a limitation of Kotlin. What do you think is the best way to workaround? Maybe provide alternative method, say "bindTo"?

Thanks!

**Comment by arkivanov** [comment]
My fault, sorry, the solution is:
```
    fun <A: Any, B: A> test(a: Class<A>, b: Class<B>) {
        bind(a).to(b)
    }
```

**Comment by stephanenicolas** [comment]
Thx for closing and giving the answers to others.

2018-05-18 13:54 GMT-07:00 Arkadii Ivanov <notifications@github.com>:
