### ISSUE TITLE
com.github.stephanenicolas.toothpick:smoothie min sdk 15

### ISSUE THREAD

**Issue by thekekc** [stephanenicolas/toothpick#298]
I would be happy to use smoothie classes in my project, but it's min sdk is 14. Are there any limitations on min sdk here? Can it be less?

**Comment by stephanenicolas** [comment]
Feel free to submit a PR if you still need it. Though, working around is as easy as redefining the smoothie classes in your own app. We feel that minSdk 15 is reasonable in 2019.
