### ISSUE TITLE
add Spock and Groovy support

### ISSUE THREAD

**Issue by aplatypus** [stephanenicolas/toothpick#299]
After a few days of getting no result and then working up a small example I've concluded that Toothpick v1.1.3 is not supporting [Groovy](http://groovy-lang.org) and _consequently_ the [Spock](https://github.com/spockframework/spock) testing framework.

For my purposes I find Spock to be a top-notch Behaviour Driven and Data Driven testing framework and we have many 'specifications' to support.  Also, Groovy is a much used JVM and Android language and key component of many popular products (e.g. Jasper Reporting, Gradle, Grails, etc.).

The following code example quicly demonstrates that the `Toothpick.inject(...)` operation does Not work when compiled and run with groovy.  I put these same lines in a 2 x `main` program programs. Called:

  * `TestContextJava.java`
 * `TestContextGroovy.groovy`

The Java version succeeds.  The Groovy buid finishes with   `processOutcome = `**`false`**

The `Scope` is created in a Java only module to ensure I'm just checking the Groovy / Java behaviour.  

**Test example**:

```
   public static void main( String... args) 
    {
        myself.testOne();
    }
    
    
    public  boolean testOne()
    {
        boolean         processOutcome	= false;
        StringBuilder   processReport   = new StringBuilder( 100 );

        String          testHomeDir;
        String          testConfigDir;

        logger.info("testEntities created.");

        try
        {
            final Scope  rootScope  = Toothpick.openScope( RootScope.getRoot()  );
            Toothpick.inject(  this, rootScope );
            
            if(  null == this.appContext  )
            {
                throw new InitialisationException("appContext NOT injected.  [testOne]");
            }
            else
            {
                BaseConfig.setup( appContext );
                
                testHomeDir    = this.appContext.getHomePath();
                testConfigDir  = this.appContext.getConfigPath();

                processOutcome = true;      //  if we got this far it worked;
            }
        }
        catch ( Throwable ex )
        {
            StringBuilder msg = new StringBuilder( 256 );
            msg.append("Failed with exception; '").append(ex.getMessage()).append(".");
            logger.error( msg.toString(), ex );
        }
        
        logger.info( "  processOutcome = ${processOutcome}" );
        
        return processOutcome;
    }
```

With support for Spock, a like example needs to work within a Spock specification.  Spock support would be _awesome_.  Alternative service providers could be used for with feature checking without the needing additional code to get things set-up. 

I hope your team will put this one on the road-map. Please up-vote.  Many thanks.

**Comment by stephanenicolas** [comment]
Hi Will,

There are good chances that we don't work on this one. I can speak for
myself only of course, but Groovy is not really a language of interest for
us. Java and Kotlin are our main focus.

We can help you solve it but we need much more information and you will
have to dig into TP internals.

You will need to check if annotation processing was enabled for groovy, if
it generated the right classes, if they can be found at runtime, you will
need more information on what is going wrong at compile time, etc etc.

Sorry, but we have a completely different roadmap and we are focusing
mostly on TP2 API redesign and probably some adaptations for Kotlin too.

**Comment by aplatypus** [comment]
G'day Stephane,

Thanks for your reply.  It was a step in the right direction.   I don't mind digging into it.  As usual time is the resource that constrains me.  I have a successful work-around for the immediate need.  I will put some notes here so the next person can see what I've found so far.

* [Gradle Groovy plugin](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.GroovyCompileOptions.html#org.gradle.api.tasks.compile.GroovyCompileOptions:javaAnnotationProcessing) manual page

The [groovy annotation facility](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.GroovyCompileOptions.html#org.gradle.api.tasks.compile.GroovyCompile)
* Options:javaAnnotationProcessing) needs to be set **`true`**
   * from the manual page: "When set to true, stubs will be unconditionally generated for all Groovy sources, and Java annotations processors will be executed on those stubs."
* Apparently the APT must follow the Groovy plugin too
  * I'm using Netbeans myself, there are also annotation processor plugins for IDEA and Eclipse
* It is handy to [**`keepStubs`**](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.GroovyCompileOptions.html#org.gradle.api.tasks.compile.GroovyCompileOptions:keepStubs) too, for investigating,
```
    plugins
    {
        id "base"       
        id "java"
        id "groovy"
    	id 'net.ltgt.apt'               version '0.17'      //  Must come AFTER Groovy plugin
    }

    //  Groovy compile
    compileGroovy {
        groovyOptions.keepStubs=true
        groovyOptions.javaAnnotationProcessing=true

        options.compilerArgs << "-Xlint:unchecked"
        options.compilerArgs << "-Xlint:deprecation"
    }
```

That said and done.  The result hasn't changed.  My small Groovy program still logs **`false`** for the injected class.

The generated stub 

```
//  Groovy source ...
    @Inject RuntimeContext      appContext;

    :
            Toothpick.inject(  this, rootScope );
            
            if(  null == this.appContext  )
            {
                throw new InitialisationException("appContext NOT injected.  [testOne]");
                //  caught later method is False when there was an exception
             }

//  Stub:
    public  au.com.fourtel.model.context.RuntimeContext getAppContext() { return (au.com.fourtel.model.context.RuntimeContext)null;}
    public  void setAppContext(au.com.fourtel.model.context.RuntimeContext value) { }
   :
```

*  My impression is that the `@Inject` annotation for `appContext` was wrong.
  * It can only return a Null -- It seems to me that Toothpick's annotation processor hasn't touched the code.
  * If the `javaAnnotationProcessing` option is supposed to pass-on the stub shouldn't the `appContext` stub have an "`@Inject`" or something for it to work?
* Where can I look for the toothpick code?  There was nothing that looked like Toothpick in the build folder.  
* Do I need to set an option to "save generated code" for Toothpick ?

Hoping one of you can give me an idea where to look next.

I thought spock would be worthwhile for Toothpick since Spock encoded the setup  / when / then / ... structures I saw in the Toothpick presentations.  However the better end-game might be to influence the Spock people to build it with Kotlin ... Anyway in case you ever become interested in Spock, this is what a feature spec. looks like.

```
    def "GWDT-55: Access specified desk configuration"()
    {
      setup:  "test control variables"
                :
      when:
                :
      then:
                :
      expect:  
                :
      where:  
                :  // data values
  }
```

**Comment by stephanenicolas** [comment]
Let's divide issues and first tackle Groovy, then spock.

In your build folder, do a `find .` and look for things with `__` like
__Factory or __MemberInjector. Look at what is generated for the java code,
basically the same should be there for Groovy or its stubs more probably.
Also, you definitely need to enable more error logging from the Groovy
compiler, I don't know how, but you need to know exactly what is failing.
You need to understand exactly what is going on, both when compiling the
code, and when annotation processors are applied, to the Groovy code. TP
will want to behave the same as for java code.

S.

2018-07-12 21:52 GMT-07:00 will <notifications@github.com>:

**Comment by aplatypus** [comment]
I have foundJava  generated classes.  None have underscores in them.  I need to put access via Groovy into the background for now, it is clearly going to take more time and not cost effective given I have can get things from a Java helper class (for the time being).   

I will close this as Groovy is not supported officially.  Best to leave it there for now.

**Comment by aplatypus** [comment]
Seems that there is a Groovy / annotation processor mismatch at present.  Some other frameworks that support Groovy use built-in AST API.  And I just found out about a Gradle bug for Annotation Processing (or at least a Lombok/Gradle bug).

Just an update.  Better for others to look for Groovy targetd/supported tool kit.
