### ISSUE TITLE
Toothpick.openScopes Lint Warning

### ISSUE THREAD

**Issue by afaucogney** [stephanenicolas/toothpick#301]
Hi,

 In kotlin, I open a scope with TP in the "init {}". Lint trigger a warning  "Leaking ‘this’ in constructor."
 Is there something special to do ?
```
abstract class BaseViewModel(app: Application) : ViewModel() {
    init {
        // TODO fix warnings
        LogUtil.i(LOG_TAG, "base onCreated")
        val viewModelScope = Toothpick.openScopes(app, this)
        ...
```

**Comment by stephanenicolas** [comment]
Please follow up on this, we're not yet very knowledgeable on Kotlin.

**Comment by stephanenicolas** [comment]
@afaucogney we don't think we can do anything about this. TP3 provides automatic injection of the view model instances. Please look at smoothie-lifecycle-viewodel and its Kotlin extension.
