### ISSUE TITLE
Unit test mock injection for Provider based binding

### ISSUE THREAD

**Issue by amaguran** [stephanenicolas/toothpick#302]
Hello,

First of all, thanks for this great library. It was a great alternative post Roboguice.
I was expecting that ToothpickRule would just use the mocks defined in a unit test class (@Mock annotated fields) and it would not try to check whether it can instantiate the dependencies.
I'm unit testing class B. Class B has a constructor dependency on class A. Class A does not have an @Inject annotated constructor. In the app's module I have bind(A.class).toProvider(AProvider.class). Do I need to do some binding for the unit test as well?
Maybe there is some more info to be added at https://github.com/stephanenicolas/toothpick/wiki/Unit-Testing?

Thanks,
Alex

**Comment by amaguran** [comment]
Hello again,

Is this a known limitation or a bug? 

Thanks,
Alex

**Comment by stephanenicolas** [comment]
No, It should work. But we need to see / understand what you're (/not)
doing.

Which mocking library do you use ?
Do you have the annotation processors enabled for tests ? Are the member
injectora generated for your test classes ?
Do you use Java or Kotlin ?
How is you test defined ?
What is going wromg exactly ? Can you give some code and the stack trace
and tell exactly what is null?
You can also debug and go through the injections ...

But, be sure that all this should work fine.

S.

**Comment by stephanenicolas** [comment]
No follow up, we close this issue. Feel free to re-open wiht more details if needed.
