### ISSUE TITLE
Is it maintained?

### ISSUE THREAD

**Issue by ultimate-deej** [stephanenicolas/toothpick#303]
Hi @stephanenicolas,

What is the status of the project? It's been half a year since the last commit, which makes me worry that you stopped working on this beautiful library.

**Comment by stephanenicolas** [comment]
TP is maintained, it's just that it is stable and we don't wanna add super
wooper features.
We wanna keep TP simple, fast and powerful.

We are planning to work on a version 2 but didn't find time yet. There is
an issue with a draft of specs.

Thx for using TP !

**Comment by PaulWoitaschek** [comment]
Btw, this is the 2.0 milestone which should give you an idea:
https://github.com/stephanenicolas/toothpick/milestone/16

**Comment by stephanenicolas** [comment]
Hell yeah !
