### ISSUE TITLE
Test Factory is replacing main code factory

### ISSUE THREAD

**Issue by L7ColWinters** [stephanenicolas/toothpick#306]
When I used the kaptTest "com.github.stephanenicolas.toothpick:toothpick-compiler:$rootProject.ext.toothpickVersion" in my code i'm able to see that the registries are being created but when I call scope.getInstance(Smoothie::class.java), no Smoothie factory is found. 

I added kaptTest so that I could use @Inject members for the toothpickRule.inject(test) but that seems to be messing with my ability to inject objects from the main code.

Any help is greatly appreciated.

For the time being I guess I'll just remove kaptTest for now since I don't know how to get injections working for test code.

**Comment by L7ColWinters** [comment]
Oh, I guess to get around this I can leave kaptTest and just use a reflection approach for the testing of toothpick. It would've been nice to know about these limitations when starting.

**Comment by stephanenicolas** [comment]
Sorry, we don't clearly understand. As there is no follow up, we close the issue. Feel free to re-open and add more details if it applies.
