### ISSUE TITLE
Introduce toothpick-reflect

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#310]
The idea is to avoid annotation processing, especially for kotlin & java/kotlin projects.
The artifact can replace toothpick's fast implementation (relying on annotation processing) for an alternative reflection based implementation to speed development cyles.

See https://github.com/JakeWharton/butterknife/tree/master/butterknife-reflect for more info. 
Thx Butterknife team for this idea and Samuel Guirrardo Navarro for letting us know about it.

**Comment by PaulWoitaschek** [comment]
Really great idea! Any progress / drafts on this?

**Comment by stephanenicolas** [comment]
We won't have time to work on this before next year.

We are actually trying to see if we can remove registries from TP for the
version 2.
After that we will have more clear ideas on what are the things to be done
in next version.

Stéphane

Le mar. 20 nov. 2018 à 00:19, Paul Woitaschek <notifications@github.com> a
écrit :

**Comment by stephanenicolas** [comment]
Actually, it's more complicated than that.

we are looking to make TP2 incremental for annotation processing. So for
java it will be much faster.
But for Kotlin, we need to evaluate how much we still need to optimize TP2,
especially for mixed java / kotlin sources, then
a reflect version would be needed if the incremental annotation processing
is not fast enough.



Le lun. 26 nov. 2018 à 10:27, Paul Woitaschek <notifications@github.com> a
écrit :

**Comment by stephanenicolas** [comment]
We are delaying any work this because of a few things:
* android studio 3.3. provides an experimental setting "Skip source generation on gradle sync if a project has more than X modules". This settings means that annotation processing is not impacting syncs anymore. 
* TP 2 supports incremental annotation processing
* kotlin compiler will soon support incremental annotation processing 

And overall tp-reflect would remain a different implementation which would entail more maintenance and some troubles to be consistent between the 2 implementations.

We close this issue.

**Comment by lukaville** [comment]
Here is a rough implementation of toothpick-reflect for Toothpick 1.1.3: https://github.com/lukaville/toothpick-reflect

**Comment by stephanenicolas** [comment]
@lukaville , that's impressive. What do you think of submitting a PR on TP. 
There seems to be quite some good stuff in your implementation, a few things we might have done a bit differently but overall, yes, interesting stuff. 

Do you think you could make it match TP 2, getting rid of registries for the most part ? And we could use your PR as a basis for TP-reflect. The work will be slow on our side but we can definitely have a look at it.

One of the things I was considering doing is to use TP inside TP so that we would be able to change the implementation of the factories and the member injectors (using generated code or reflection).
But very honestly, I am still wondering if this all is a good approach as explained above. It's definitely interesting but also still very annoying to have to maintain 2 implementations of a lib...

Anyway, great work !
