### ISSUE TITLE
TP Smoothie and Android Jetpack

### ISSUE THREAD

**Issue by Konsumierer** [stephanenicolas/toothpick#311]
While trying to migrate an Android project to Android Jetpack, the Smoothie modules got in the way, since they still use the old packages for Activities and Fragments. Is there any work planned to support Android Jetpack?

**Comment by stephanenicolas** [comment]
No, but PRs are welcome !
What error do you get ?

Stéphane

**Comment by Konsumierer** [comment]
Well, just found out that the gradle option `android.jetifier=true` and `android.useAndroidX=true` only work beginning with android-gradle-plugin 3.2.0, which will do the magic for 3rd-party-libs. I am still curious what 3rd-party-libs plan to do in the future. If they migrate to the new androidx libraries, then everyone would be excluded who has not yet migrated. What are your thoughts on that @stephanenicolas ?

**Comment by stephanenicolas** [comment]
I think you're right Sebastián. If we need to.migrate, we would have to
introduce new artifacts to depend on Android X. Probably a new version at
some point.

More probably, we will advice users to use the 2 options you mentioned,and
when Android X is the norm, we will switch.

What we wanna avoid in this case is to maintain multiple artifacts to
handle multiple dependencies.

S.
