### ISSUE TITLE
SuppressWarnings - Injectable: Compiler Flag

### ISSUE THREAD

**Issue by PaulWoitaschek** [stephanenicolas/toothpick#314]
Could you provide a compiler flag to suppress the injectable warnings for classes extending classes?

It's a lot of boilerplate to add suppressing annotations for each and every fragment.

I was thinking about sth. like 
`toothpick.ignoreInjectableWarningsFor=android.app.Fragment,androidx.fragment.app.Fragment`
where you specify a list of framework classes where you can't perform constructor injection.

**Comment by stephanenicolas** [comment]
That could be a good idea, I flag it for a future version

Le mar. 20 nov. 2018 à 00:18, Paul Woitaschek <notifications@github.com> a
écrit :

**Comment by stephanenicolas** [comment]
Sorry @PaulWoitaschek , we re-considered this request and we don't like adding an extra option.
The "boiler plate code" is an extra line per fragment class, it's not that bad. Thx though.
