### ISSUE TITLE
TP 2.0 draft Specs

### ISSUE THREAD

**Issue by stephanenicolas** [stephanenicolas/toothpick#315]
TP 2 will be addressing the following specs:

### Killing the registries

Registries are created in TP 1 during the last round of annotation processing which breaks the annotation processing model. It is also difficult to reconciliate them with annotation processing rounds as other APs can generate code using the JSR 330 annotations.
More details in #215 .

Also, registries are too central and will make TP's incremental annotation processing less efficient.
After benchmarking the Groupon app with and without registries, we found out that the registries don't bring any benefits anymore. This is due to the latest change in the registries to accomodate obfuscation.

Killing the registries in TP will also decrease significantly its complexity.
The only remaining annotation processor will easily become incremental and isolating as it generates 1 factory (and/or 1 member injector) per `@Inject` annotated file.

Killing the registries will also decrease the amount of overhead and boilerplate in configuration modules using TP especially for a modularized app, creating new modules was verbose.

And killing the registries will also make it easier to accomodate the dynamic delivery/features and instant apps. (Issue #313)

Finally killing the registries will make it simpler to work on a Toothpick-reflect version, which might be part of release 2.0 (Issue #310) 

### Support Gradle's new incremental annotation processing

Making the unique AP incremental should be easy, it will be isolating.

### Create extension for JUnit 5

We need to add a JUnit 5 extension to be used instead of the unit testing rule when using JUnit 5.

Release 2.0 is scheduled to be released at the beginning of 2019.

**Comment by L7ColWinters** [comment]
So when the registry is gone, will there be another way to use toothpick with obfuscation? Or is this going back to the pre 1.1.3 change where to add obfuscation support one had to not mix annotation and obfuscation together?
