### ISSUE TITLE
[Question] Jacoco results of app tests are obfuscated with Toothpick 2

### ISSUE THREAD

**Issue by RocketRider** [stephanenicolas/toothpick#323]
I know this is more a question than an issue, but I would like to get some insight form you guys what could have resulted in the issue I am facing.

We are using Toothpick 1 in a multi module Android App with library modules, and test modules.
To test the app we run our tests on a staging build which enables proguard.
While using Toothpick 1 this was working fine. But after upgrading to Toothpick 2 something changed.
Now we see obfuscated files in the jacoco ec files. The problem is we can't merge not obfuscated and obfuscated coverage results.
My question to you guys would be, if you know how the upgrade of toothpick could have changed the way jacoco works?

I also asked on stackoverflow if there is any way to merge the results:
https://stackoverflow.com/questions/54629643/merge-jacoco-results-obfuscated-and-not-obfuscated-runs

**Comment by stephanenicolas** [comment]
I don't see how TP can change the way your app is obfuscated. I read stack over flow thread as well but I don't understand clearly what's happening.

**Comment by stephanenicolas** [comment]
Closed as there is no follow up.

**Comment by RocketRider** [comment]
The problem seems to be fixed when I do remove the "-adaptclassstrings" config from the proguard file.
The obfuscated app seems to work fine without this parameter, why does Toothpick need(adds) this?

**Comment by stephanenicolas** [comment]
TP 2 should not need this anymore.
TP1 needed it as registries contained class names as strings.

Le lun. 17 juin 2019 à 07:37, Michael Möbius <notifications@github.com> a
écrit :
