### ISSUE TITLE
Proguard rule require

### ISSUE THREAD

**Issue by rovkinmax** [stephanenicolas/toothpick#325]
I spent 2 hours to find problem with release build after upgrade from 1.1.3 to 2.1.0 version.
Add information about proguard rules for users, who use only **toothpick-runtime** module without smoothie module.
```
-keep class **__Factory { *; }
-keep class **__MemberInjector { *; }
```

**Comment by dimsuz** [comment]
I would suggest that the library should provide a correct proguard rules as part of it.

**Comment by stephanenicolas** [comment]
Could you find this page in the wiki:
https://github.com/stephanenicolas/toothpick/wiki/Proguard-&-TP

It says "In TP 2, consumer projects using Smoothie will receive Proguard
configuration for TP."

Feel free to submit a PR to make the docs more clear, or to re-open and
submit a better way to document this.


If cannot use Smoothie, you can still use the Proguard file provided in the
Smoothie module.
