### ISSUE TITLE
Use context in an injected class

### ISSUE THREAD

**Issue by adenaud** [stephanenicolas/toothpick#326]
Hi, I am migrating a project from RoboGuice to TP, in RoboGuice I used to inject the context in my dependencies using @Inject in the constructor.

````
@Inject MyDependencie(Context context)
````
Is there any way to access the context from an injected dependencie with TP?

**Comment by stephanenicolas** [comment]
There are quite a few problems with this:
* all you dependencies probably don't need the context. It's a heavy dependency toward androids.
* you increase the risk of leaks. If you would pass the activity as a context to a singleton, you're there.

I would encourage to refactor your code, inject only the context:
* when really needed
* either as `@Inject Activity` and `@Inject Application`. Both will work using smoothie and installing its bindings. You need to clarify this for leaks.
* do ***not*** use the old ContextSingleton of TP1. Use TP2.
* read about scopes in the wiki to understand how to deal with activity scopes. RoboGuice didn't address this in a good way.
