### ISSUE TITLE
Can I bind one singleton to two interfaces normally?

### ISSUE THREAD

**Issue by Dimchel** [stephanenicolas/toothpick#327]
I want to do something like that:
`bind(IFoo1.class).to(Foo.class).singletonInScope()
bind(IFoo2.class).to(Foo.class).singletonInScope()`
but in that case will be created two instances of Foo.
So are there any ways to bind Foo class to IFoo1 and IFoo2 interfaces by creating only one instance of Foo. And the other requirement - to initialize Foo.class automatically.

Thank you!

**Comment by stephanenicolas** [comment]
Toothpick doesn't support aliases. But in this case you can do:

```
Foo foo = new Foo();
bind(IFoo1.class).to(foo);
bind(IFoo2.class).to(foo);
```

Re-open if needed.

**Comment by Dimchel** [comment]
> ```
> Foo foo = new Foo();
> bind(IFoo1.class).toInstance(foo);
> bind(IFoo2.class).toInstance(foo);
> ```
Yep. But it this case I should initialize my Foo instance and resolve it dependencies manually.
It's sad (

**Comment by morder** [comment]
+1 to implement this feature

**Comment by dimsuz** [comment]
One more +1 . Had a wish aliases were supported several times.
Without them you end up having more boilerplate than one should for such simple case.

**Comment by stephanenicolas** [comment]
You can also bind to the same provider instance, and inside the provider,
inject your singleton.

I don't think there is much interest in this feature from the maintainers I
know, but what's cool is that TP belongs to its
community as well. Feel free to contribute a feature like this. It might be
worth discussing your plan in an issue before though.

**Comment by dlemures** [comment]
@Dimchel @morder @dimsuz, there are 2 reason why we didn't implement it:
1. On TP we are trying to keep it simple. Having such a feature, will allow to do something like the following code. It can be difficult to follow (error prone) and affect TP speed:
```
A -> B
B -> C
D -> B
```

2. The way TP is implemented, bindings and scope annotations somehow provide a similar information: where and how they are created and for how long they are alive. (not exactly your scenario, but very similar)

However, it is possible to achieve the same by doing it more explicit: using a Provider.

```kotlin
class MyProvider<T>(val scope: Scope, val cls: Class<T>) : Provider<T> {

    override fun get(): T {
        return scope.getInstance(cls)
    }
}
```

Then you can use it:
```java
bind(Foo.class).singletonInScope() 
bind(IFoo1.class).toProviderInstance(MyProvider(scope, Foo.class))
bind(IFoo2.class).toProviderInstance(MyProvider(scope, Foo.class))
```

This sample might not be optimal, but it is to show the idea.
