### ISSUE TITLE
Qualifier Named injection broken

### ISSUE THREAD

**Issue by kengura** [stephanenicolas/toothpick#328]
```
@Qualifier
annotation class Bar

class Foo

class A {
    @Inject
    @Bar
    lateinit var foo: Foo
}

val s0 = Toothpick.openScope("S0")
s0.installModules( object : Module() {
      init {
          bind(Foo::class.java).withName(Bar::class.java).toInstance(Foo())
      }
})
Toothpick.inject(A(), s0)
```
I'm getting error for the code above: 
```
toothpick.locators.NoFactoryFoundException: No factory could be found for class com.shakuro.template.Foo. Check that the class has either a @Inject annotated constructor or contains @Inject annotated members.
```
There is no error when `withName(Bar::class.java)` removed.

**Comment by stephanenicolas** [comment]
Can you show the code that is generated for the A__MemberInjector ?
But there seems to be a bug in TP:
toothpick/compiler/common/ToothpickProcessor.java:474. We should scan all
annotations and see if themselves are annotated using qualifier.

A workaround would be to use @Named(Bar::class.java.name) @Inject or any
other name in @Named that matches the binding.
Also it might be possible that kotlin doesn't annotate the JVM field Foo
properly when you declare the property Foo in A.
It would help if you could also provide the decompiled java code for A.

Le ven. 12 avr. 2019 à 07:21, Ruslan Krohalev <notifications@github.com> a
écrit :

**Comment by kengura** [comment]
```
public final class A__MemberInjector implements MemberInjector<A> {
  @Override
  public void inject(A target, Scope scope) {
    target.foo = scope.getInstance(Foo.class);
  }
}
```

With `@Named("Bar")` and `withName("Bar")` i'm getting the same error.

Unfortunately i can't provide the decompiled java code for A - i have some issues with decompiling apk file.

**Comment by stephanenicolas** [comment]
We definitely have a bug with the qualifiers.. I am gonna open a ticket.
Thanks for reporting it.

With @Named though, there must be something wrong on your side, we use this
feature all the time.
Do you mind creating a gist or a small sample project to reproduce it?



Le lun. 15 avr. 2019 à 01:13, Ruslan Krohalev <notifications@github.com> a
écrit :

**Comment by dector** [comment]
Faced same issue. Neither `@Qualifier` nor `@Named` don't work.

Kotlin, kapt version: `1.3.31`
Toothpick version: `2.1.0`.

Sample project: [toothpick_issue.tar.gz](https://github.com/stephanenicolas/toothpick/files/3133326/toothpick_issue.tar.gz)

**Comment by dector** [comment]
@stephanenicolas Did you have a chance to check the sample project? ^^^

**Comment by stephanenicolas** [comment]
No I was off last weeks.
I will have a look, but I would prefer to review a PR ;)

**Comment by stephanenicolas** [comment]
@dector , you have to apply `@field:Named(...)` instead of `@Named(..)` in Kotlin:
https://kotlinlang.org/docs/reference/annotations.html#annotation-use-site-targets.

For the qualifier, we definitely have a bug. I am gonna have a look at it as soon as possible.

**Comment by dector** [comment]
@stephanenicolas Got it, thanks. Named injections into methods are not allowed for now?

**Comment by stephanenicolas** [comment]
Yes they are, though method injection is very rare.

**Comment by stephanenicolas** [comment]
@kengura @dector , the same goes for the custom annotation in Kotlin.
If, in the example at the top of this thread, you use:

```kotlin
class A {
    @Inject
    @field:Bar
    lateinit var foo: Foo
}
```

Then all seems to be working fine. Can you confirm it works for you as well ?

**Comment by dector** [comment]
Thanks you @stephanenicolas . Applying qualifier to field works well!
