### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by IgorGanapolsky** [stephanenicolas/toothpick#329]
Hello,
when I attempt to compile the sample in Android Studio, It gives this error:
> The module 'smoothie-androidx' is an Android project without build variants, and cannot be built.  

Please advise

**Comment by IgorGanapolsky** [comment]
I believe the issue was that I imported **smoothie-sample** into Android Studio project, instead of the entire git repo.  Can you please confirm how to properly use your sample?

**Comment by stephanenicolas** [comment]
It is working fine for us. Maybe the best would be to add a few screenshots, but honestly our time is limited to help importing the sample in an IDE. The base line should be to build it from the command line. With that we can help.
