### ISSUE TITLE
Smoothie Proguard config breaks Firebase

### ISSUE THREAD

**Issue by ultimate-deej** [stephanenicolas/toothpick#330]
I use Firebase Dynamic Links in my project. Turning ProGuard on caused `FirebaseDynamicLinks.getInstance()` to return `null`. After some digging it turned out that smoothie module was the cause.

At first removing this line seemed to help:
```-adaptclassstrings```
But I didn't want to remove smoothie from my project so I kept trying. After a while I came up with a rule that worked for me:
```-keep class * { @javax.inject.Qualifier <init>(...); }```

Btw, not being a ProGuard expert I would expect this to work instead:
```-keep @javax.inject.Qualifier class *```
But it doesn't 🤷‍♂️.

**Comment by stephanenicolas** [comment]
Can you show some code that you want to preserve, please?

Le mar. 30 avr. 2019 à 02:43, Maxim Naumov <notifications@github.com> a
écrit :

**Comment by ultimate-deej** [comment]
It's not my code I want to preserve. Instead, I want `FirebaseDynamicLinks.getInstance()` to return a non-null value. As to why that rule works or how it affects Firebase, no clue. I discovered it accidentaly, basically. But it suddenly works so I'll just stick with it until a better solution is found.

**Comment by stephanenicolas** [comment]
If I understand correctly,the qualifier annotation part is relevant to your
code.

If the option adaptclassstrings is impacting firebase, I would strongly
suggest that you open a ticket on their repo to ask them to document it.

TP might have required it for TP1 registries but I don't think it's needed
at all for TP2.

**Comment by ultimate-deej** [comment]
I couldn't find the Firebase Dynamic Links repo, this part of Firebase seems to be closed source. Anyway, I don't think it's a problem of Firebase. Because, isn't that rule too broad to be included in a library in the first place? And since it's not probably needed for TP2, could you consider removing it?

**Comment by ultimate-deej** [comment]
A clean project test showed that `-adaptclassstrings` alone doesn't break Firebase. I'll investigate the issue further.

**Comment by zawadz88** [comment]
I've encountered a similar issue when updating from TP 1.1.1 to 2.1.0.
The issue I'm having is with Firebase Performance though.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.firebase.perf.a.b()' on a null object reference
        at com.google.android.gms.internal.firebase-perf.fd.b(Unknown Source:2)
        at com.google.android.gms.internal.firebase-perf.fd.a(Unknown Source:0)
        at com.google.android.gms.internal.firebase-perf.ff.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```
where `com.google.firebase.perf.a` is `com.google.firebase.perf.FirebasePerformance`
In my example, removing `-adaptclassstrings` did the trick.

**Comment by zawadz88** [comment]
Also, I had to modify the ProGuard rules to have it working in my project with 2.x.
```
-dontwarn javax.inject.**
-dontwarn javax.annotation.**
```
had to be changed to
```
-keep class javax.inject.**
-keep class javax.annotation.**
```
and I had to add
```
-keepclassmembers class * {
	@javax.inject.Inject <init>(...);
	@javax.inject.Inject <init>();
	@javax.inject.Inject <fields>;
	public <init>(...);
}
```

**Comment by stephanenicolas** [comment]
The wiki has been updated. I close this oooolllddd ticket. Sorry about that @ultimate-deej

**Comment by RumataEstorish** [comment]
When migrating to gradle plugin 7.0 had to add
-keep @javax.inject.Qualifier public class *
to keep qualifiers working
