### ISSUE TITLE
Support for reactive API

### ISSUE THREAD

**Issue by ww2lin** [stephanenicolas/toothpick#332]
~~Having an api that is "life-cycle" aware. where instead of closing the scopes manually within onDestroy in Android. We should be able to observeOn the events from TP. E.g OnInjection, OnOpenScope, OnClosingScope, OnClosedScope etc.~~

TP should be able to observe on a subject(one example is I'm thinking of is android LifeCycleOwner `myLifecycleOwner.getLifecycle().addObserver(ToothPickObserver());` which then TP will know when to open/close scope.

**Comment by stephanenicolas** [comment]
What would you use the events for ?

**Comment by ww2lin** [comment]
@stephanenicolas Sorry my wording is a little bit confusing, I reword the description.

**Comment by stephanenicolas** [comment]
@ww2lin , Hey Alex. It could be an interesting idea. We definitely would have to add this to smoothie-androidx module. IIRC, view models also provide a life cycle observer when the view model is destroyed, this could be used to shutdown what we often refer to as `presenter scopes`.

If you feel like contributing it to TP, it would be great. 

I would suggest that you would create a listener of lifecycle that would take both a scope and a lifecycleowner in constructor param, the listener would close the scope.

**Comment by stephanenicolas** [comment]
This has been released as part of TP 3.x. Have a look at the smoothie-lifecycle modules.
