### ISSUE TITLE
Tests with Mockk

### ISSUE THREAD

**Issue by ClaireGizard** [stephanenicolas/toothpick#334]
Hello !

Is it possible to add a support for the library Mockk like you did for Mockito and EasyMock ?

Thank's

**Comment by ClaireGizard** [comment]
i think it's already working, i did some test but i'm not sure that all the features work perfectly.

**Comment by stephanenicolas** [comment]
Hi Claire,

I don't think we will have time to add support for Mockk. But we would be
glad to add a PR to support it if you feel like contributing to TP.


Le mer. 5 juin 2019 à 08:58, ClaireGizard <notifications@github.com> a
écrit :

**Comment by dlemures** [comment]
Looking at the TP test implementation, it should already work for the annotations: `@MockK` and `@RelaxedMockK`.

Is there any feature that you found missing @ClaireGizard ?

**Comment by afaucogney** [comment]
Hi, it works too with @InjectedMock, but not with @Spyk.

Le sam. 20 juil. 2019 à 23:58, Daniel Molinero <notifications@github.com> a
écrit :

**Comment by stephanenicolas** [comment]
TP works out of the box for all annotations containing 'Mock' in their
names.
We have added mockk support for TP 3 specs IIRC.

**Comment by dlemures** [comment]
We will add support `@SpyK` (MockK) and `@Spy` (Mockito).

**Comment by stephanenicolas** [comment]
This is getting closed as it has been released in version 3.0.0.
