### ISSUE TITLE
Add documentation for closeScope to the wiki

### ISSUE THREAD

**Issue by LukasWillin** [stephanenicolas/toothpick#339]
Hi Nicolas :)

Thank you for this DI Framework. We really started to love it. 

I wanted to request further documentation of the closeScope function in the wiki. Reason is that I totally missed the hint of the method declaration which sais `closeScope(Object name)`.
We are pretty new to DI Frameworks in Android and tried to close the scope like this at first:

``` java
// Where LibrarySingleton is our Scope Annotation
Scope libraryScope = Toothpick.openScope(LibrarySingleton.class);
// We tried to use closeScope on the scope itself
Toothpick.closeScope(libraryScope);
// instead of
Toothpick.closeScope(LibrarySingleton.class);
```

It would have been nice to find a use of Toothpick#closeScope somewehere in your docs. Probably best to include such a use directly in the [Scopes Wiki](https://github.com/stephanenicolas/toothpick/wiki/Scopes).

If you want I can write you such an example in a pull request.

Kind Regards 
Lukas

**Comment by stephanenicolas** [comment]
Thx @LukasWillin , that's actually a fair comment. I am often close to doing the same mistake with TP when I use it after a while. 

Though, the close and open methods are fairly symmetrical, which makes sense from an API perspective. 
Also, in TP3, it's quite more likely that you will not keep a reference to a scope after opening it. Multiple things contribute to it: the new fluent DSL on scopes, and some additional modules to follow activities, fragments and view model lifecycles. 

I have added a few words in the wiki as you suggested: https://github.com/stephanenicolas/toothpick/wiki/Scopes#a-small-note-on-opening--closing

**Comment by stephanenicolas** [comment]
We are re-opening the ticket. We consider the change for the next major release.
