### ISSUE TITLE
Questions on modularization with TP

### ISSUE THREAD

**Issue by markchristopherng** [stephanenicolas/toothpick#343]
Hi @stephanenicolas @dlemures 

We are in the middle of modularizing our app and we are at the stage where we want to run individual features separately so we don't have to build the whole app. At the moment all our DI configuration is done in the app. We are planning on creating separate modules for different features.  I was just wondering if there was any way to define a hierarchy on the modules so that 

if Feature A depends on Feature B & Feature C   then if you install Module A, then Module B and C get automatically installed as well.

Now that we have modularized quite a bit of our app we have quite a few interfaces for our Singletons that need to binding in a Module. Before this we didn't have to define them in a module as they used the @Singleton annotation.

We can get around this by just manually installing them but it would be a nice feature. I was just wondering how you did your DI on your app at Groupon and if you could share any details?

Regards
Mark

**Comment by stephanenicolas** [comment]
Sorry for the delay, we spend most of our free coding time on TP3.

There are a couple of things in your issue:

Features should not depend on each other. If they share common code, isolate it other modules and make them a dependency of your features. And yes, navigation becomes more tricky when you do so but there are different solutions (do you know [DH3](https://github.com/f2prateek/dart/)?)

When you mention :

> if Feature A depends on Feature B & Feature C then if you install Module A, then Module B and C get automatically installed as well.

You should be creating scopes and sub-scopes for this. You app seem to be using a single application scope. You can create sub scopes, each of them with their own modules. TP doesn't provide support for anything as you describe automatically, but scopes offer the fine grained modularity you are looking for. You can use them to add and remove new bindings by opening and closing sub scopes.

> Now that we have modularized quite a bit of our app we have quite a few interfaces for our Singletons that need to binding in a Module. Before this we didn't have to define them in a module as they used the @singleton annotation.

I don't understand this part: the app module knows about all your code as all your features are its dependencies. I don't see why you have to define bindings. 

At Groupon we have developped a technique that we call the interface technique. We gave a few talks in the bay area about it but not in international conferences. The idea is that you take your legacy code module, and when you extract some code out of it to create a new module (M), you can't cut all the dependencies. So you use interfaces: you create a new module that defines interfaces for the dependencies that are still in the legacy module. This will allow to  extract M, without depending on the legacy code, you will then use bindings. 

Modularization is a complex process, and long, and difficult. Unfortunately, I can't explain all of it here. But TP was definitely not such a problem during this process. You can also look at this issue, it talks about dynamic-features using TP: https://github.com/stephanenicolas/toothpick/issues/313

**Comment by markchristopherng** [comment]
Hi @stephanenicolas 

We just implemented DH3 a couple of weeks ago and its worked out great for us. We understand the navigation problem quite well and your library is really good at helping solve that problem.  Our app is 4 or 5 years old and it's not feasible for us to move to Google's navigation library so it nice having these alternate solutions. 

We probably started modularizing our app about 12 months ago, we started off with three modules app, wear, common and now have over 85 modules. I agree it's a very long journey I would say that we are 70 - 80% of the way. 

Our goal was not to move to instant apps or dynamic apps although that is would be nice and would require more work but to improve build speed, engineering and help with merging and branching. When we talk about features they are really just modules, we aren't talking about Google's definition of features,  so we have lots of modules that would make up a feature.  Our terms are very loose and may cause some confusion.

We haven't had any issue with TP in regards to modularization we just wanted to see what other people have done. Are you able to share any of the slide decks that you gave about modularization in the bay area? We have found the Group libraries to be very good in terms of support and simplicity and keeping up with the latest in Android.

As you probably know during modularization you learn quite a lot as you go you push things up and then you push things down and after doing something you get a better insight on what you should have done in the first place. I would say the way we have done DI in our app is ok (definately room to improve) but it has got has to this point. We don't just use the application scope we do have quite a lot of modules that only get installed at the activity scope and these are internal to a module. We have about 4 DI modules that provide things like logging, analytics etc and are global and need to installed in the application module. Thanks, you have provided enough hints for us to consider.

Looking forward to TP3 :)

Regards
Mark

**Comment by markchristopherng** [comment]
@stephanenicolas @dlemures we just finished our app modularization. I also wrote an article about the journey and a put in a small mention about Dart Henson 3. The article is on this weeks Androidweekly.net issue.

https://medium.com/@markchristopherng/the-gritty-truth-about-app-modularization-e306f05dee5c

**Comment by stephanenicolas** [comment]
@markchristopherng, thx for this article. I am currently traveling but I will find more time to go through it in a deeper way.
Cool for the mention of DH3, it's appreciated.

I've seen you mentioned DI, but didn't mention Toothpick. Though we strongly believe that TP does a better job at modularization than dagger. Especially TP3 with our new refined scopes. 

I don't wanna be pushing for you to mention it, but I am just curious of the reason why you didn't. Was there an issue with TP ? Did you change for another DI engine ?

**Comment by markchristopherng** [comment]
Hi Stephanen,

We still use TP, I didn't mention it because the navigation problem is
universal however people might be using different DIs.

The simplicity of TP made modularization very easy I think if we were using
dagger it might have been more complex.

I'll update my article to mention TP because at the moment it is receiving
a high number of hits.

At the moment we a bit swapped with features but we are definitely planning
to upgrade to TP3 and refine how we use it. i might even write an article
about how we improved our DI but it won't be for a while.

Enjoy your holiday. I need one as well.

Regards
Mark

**Comment by stephanenicolas** [comment]
Thx @markchristopherng for the mention of TP. We definitely appreciate any help on the marketing side ;) 

We also plan an article, even a few, but it will take a while for us as well. 

And yes, vacations is the source of life ;)
