### ISSUE TITLE
Wrong lambda code in wiki

### ISSUE THREAD

**Issue by ppsirker** [stephanenicolas/toothpick#357]
https://github.com/stephanenicolas/toothpick/wiki/Modules-&-Bindings#configuration-lambda
Incorrect lambda expression:
`Scope s = Toothpick.openScope(obj, { scope ->
   scope.installModules(new Module() {{ 
      bind(IFoo.class).toInstance(new Foo()); 
      bind(IBar.class).to(Bar.class); 
   }})});`
corrected
`Scope s = Toothpick.openScope(obj, scope ->
   scope.installModules(new Module() {{ 
      bind(IFoo.class).toInstance(new Foo()); 
      bind(IBar.class).to(Bar.class); 
   }}));`
There is an extra pair of braces.

**Comment by stephanenicolas** [comment]
Thx ! @dlemures do you mind to fix it please ?

**Comment by stephanenicolas** [comment]
I did. Thx @ppsirker

**Comment by dlemures** [comment]
Thx for the suggestion and fix!
