### ISSUE TITLE
superMemberInjector generated with missing type information

### ISSUE THREAD

**Issue by zawadz88** [stephanenicolas/toothpick#360]
In Toothpick 3.0.0 there's an issue where the generated `__MemberInjector` has an incorrect `superMemberInjector` field i.e. it does not set the type argument correctly.

E.g. assume we have `AddNewActivity` with `@Inject` annotated fields. `AddNewActivity` extends `BaseActivity` which has a type parameter e.g.
```

public class AddNewActivity extends BaseActivity<Integer> {
 // ...
}
```
where `BaseActivity` is: 
```
abstract class BaseActivity<T> : SomeInterfaceWithGeneric<T>, AppCompatActivity() {

    @Inject
    lateinit var dummyDependency: DummyDependency
}
```

When you try to build the project KAPT will fail with the following reason:
```
> Task :kaptDebugKotlin FAILED
e: /Users/me/workspace/toothpick/toothpick-sample/build/generated/source/kapt/debug/com/example/toothpick/activity/AddNewActivity__MemberInjector.java:9: error: cannot find symbol
  private MemberInjector<BaseActivity<T>> superMemberInjector = new com.example.toothpick.activity.BaseActivity__MemberInjector();
                                      ^
  symbol:   class T
  location: class AddNewActivity__MemberInjector
e: /Users/me/workspace/toothpick/toothpick-sample/build/generated/source/kapt/debug/com/example/toothpick/activity/AdvancedBackpackItemsActivity__MemberInjector.java:9: error: cannot find symbol
  private MemberInjector<BaseActivity<T>> superMemberInjector = new com.example.toothpick.activity.BaseActivity__MemberInjector();
```
Generated `AddNewActivity__MemberInjector`

```
public final class AddNewActivity__MemberInjector implements MemberInjector<AddNewActivity> {
  private MemberInjector<BaseActivity<T>> superMemberInjector = new com.example.toothpick.activity.BaseActivity__MemberInjector();

  @Override
  public void inject(AddNewActivity target, Scope scope) {
    superMemberInjector.inject(target, scope);
    target.backpackItemValidator = scope.getInstance(BackpackItemValidator.class);
  }
}
```

I've added an example in `toothpick-sample` app to reproduce this:
https://github.com/stephanenicolas/toothpick/compare/master...zawadz88:super-member-injector-bug

This happens if `AddNewActivity` is in either Java or Kotlin and has `@Inject` annotated fields/properties. The issue does not occur in Kotlin when using the newly introduced inject delegates (thanks for introducing these!).

**Comment by dlemures** [comment]
Hi Piotr,

Thanks for the report and sample!

I'll take a look at it on Monday and probably release a patch.

**Comment by stephanenicolas** [comment]
@dlemures, I can take it. The problem comes from the T type param, I guess
we could explore recursively the super type (recursive for
BaseActivity<List<T>>) and replacing with a wildcard ? Should work. Or
define T in the MI class signature...

TDD please. Thx for handling this.

**Comment by stephanenicolas** [comment]
I can't ***

**Comment by zawadz88** [comment]
I've just checked and in TP 2.1.0 `AddNewActivity__MemberInjector` would actually look like this:
```
public final class AddNewActivity__MemberInjector implements MemberInjector<AddNewActivity> {
  private MemberInjector superMemberInjector = new com.example.toothpick.activity.BaseActivity__MemberInjector();

  @Override
  public void inject(AddNewActivity target, Scope scope) {
    superMemberInjector.inject(target, scope);
    target.backpackItemValidator = scope.getInstance(BackpackItemValidator.class);
  }
}
```
i.e. type argument `<BaseActivity<T>>` is not present in `superMemberInjector` field. 

I'm wondering if it was added in TP 3.0 for a reason? Obviously it's nicer to have it, but it's not really needed in Java to compile at least.

**Comment by stephanenicolas** [comment]
Hi Piotr,

I made the change. The idea was to generate better code that wouldn't
trigger any error nor warnings. The TP 2.x code would trigger javac lint
warnings and I wanted to get rid of that.

I am traveling and can't address the  issue at the moment. I couldn't
neither get in touch with @dlemures about it and he will be traveling as
well.

Of you feel like it, it would be greatly appreciated if you could issue a
PR, with unit tests to fix the issue. Daniel will be able to release
shortly after. Please test it and add a unit test if you do so. The PR
should be green.

The problem lies in the MemberInjectorGenerator class.

Regards,
 S.

**Comment by zawadz88** [comment]
Hi @stephanenicolas ,
So I was playing around with this a bit and seems that it would have to generate:
```
public final class AddNewActivity__MemberInjector implements MemberInjector<AddNewActivity> {
  private MemberInjector<BaseActivity> superMemberInjector = new com.example.toothpick.activity.BaseActivity__MemberInjector();

  @Override
  public void inject(AddNewActivity target, Scope scope) {
    superMemberInjector.inject(target, scope);
    target.backpackItemValidator = scope.getInstance(BackpackItemValidator.class);
  }
}
```
It cannot be 
```
private MemberInjector<BaseActivity> superMemberInjector = new com.example.toothpick.activity.BaseActivity__MemberInjector();
```
as `BaseActivity__MemberInjector` does not have a specific type. Having `MemberInjector<BaseActivity> superMemberInjector` also doesn't seem to produce any warnings.

I was able to achieve this by using 
```diff
diff --git a/toothpick-compiler/src/main/java/toothpick/compiler/memberinjector/generators/MemberInjectorGenerator.java b/toothpick-compiler/src/main/java/toothpick/compiler/memberinjector/generators/MemberInjectorGenerator.java
index 274a434..c767e6a 100644
--- a/toothpick-compiler/src/main/java/toothpick/compiler/memberinjector/generators/MemberInjectorGenerator.java
+++ b/toothpick-compiler/src/main/java/toothpick/compiler/memberinjector/generators/MemberInjectorGenerator.java
@@ -90,7 +90,7 @@ public class MemberInjectorGenerator extends CodeGenerator {
           FieldSpec.builder(
                   ParameterizedTypeName.get(
                       ClassName.get(MemberInjector.class),
-                      TypeName.get(superClassThatNeedsInjection.asType())),
+                      TypeName.get(typeUtil.erasure(superClassThatNeedsInjection.asType()))),
                   "superMemberInjector",
                   Modifier.PRIVATE)
               // TODO use proper typing here

```

Are you OK with approach? If so, I can add some proper unit tests and submit a PR.

**Comment by dlemures** [comment]
Nice to start the week with a PR for TP! Reviewed.

**Comment by zawadz88** [comment]
> Thx for the PR @zawadz88 . I was wondering how you manage to instantiate a generic activity ? By subclassing, right ?

Yes, that's exactly right. Parent Activity contains a generic type.

**Comment by stephanenicolas** [comment]
Thx Piotr. I added a Contributing.md file to the repo. Feel free to review
it.

**Comment by zawadz88** [comment]
> I added a Contributing.md file to the repo. Feel free to review it.

Thanks! I'd probably add some info to check if all checks pass before submitting the PR (for forked repos the build gets executed once you submit a PR).
So in other words execute the same commands which are specified in `.travis.yml`:
```
./gradlew clean check
./gradlew -b toothpick-sample/build.gradle clean check -x lint
```
What do you think?

**Comment by dlemures** [comment]
Improved CONTRIBUTING.md with @zawadz88 comments!
thx

**Comment by dlemures** [comment]
TP 3.0.1 with the fix has been released!

Closing
