### ISSUE TITLE
Adding documention about getRootScope

### ISSUE THREAD

**Issue by dlemures** [stephanenicolas/toothpick#366]
We should add documentation to the wiki about the method getRootScope (for Toothpick and KTP).

Maybe we can introduce it inside one of the activities in the example.

**Comment by stephanenicolas** [comment]
https://github.com/stephanenicolas/toothpick/wiki/Scopes#tp-31-root-scope

**Comment by dlemures** [comment]
Thx @stephanenicolas !

Closing
