### ISSUE TITLE
How share a Singleton that implement 2 different interfaces in to different scopes ?

### ISSUE THREAD

**Issue by afaucogney** [stephanenicolas/toothpick#369]
Sorry, this is not easy to find a good title.

I'm trying to build a multi-module app with TP3 ^^ (3.0.2)

Problem is simple:

I have 2 interfaces:

```
interface IFooWrite {
    fun write(n: Int)
}

interface IFooPrint {
    fun print()
}
```

I implemented those 2 interface into a single class
```
@Singleton
class Foo @Inject constructor() : IFooWrite, IFooPrint {
    var number: Int? = null

    override fun write(n: Int) {
        number = n
    }

    override fun print() {
        Log.d("##", number.toString())
    }
}
```

I want to first define a scope, inject IFooWrite in a first module. This feature is responsible to get a data and save it

Then in a second module, I need this data back, so I inject IFooRead, to then print the data.

So I defined the instance Foo as a Singleton, so I expected that both injection will provide me the same instance, that is not the case.

```
class MyApp : Application() {
    override fun onCreate() {
        super.onCreate()

        KTP.openScope("ROOT")
            .installModules(object : Module() {
                init {
                    bind(IFooWrite::class.java).to(Foo::class.java)
                }
            })
            .getInstance(IFooWrite::class.java)
            .write(42)

        KTP.openScope("ROOT")
            .openSubScope("SUB")
            .installModules(object : Module() {
                init {
                    bind(IFooPrint::class.java).to(Foo::class.java)
                }
            })
            .getInstance(IFooPrint::class.java)
            .print()
    }
}
```

This print "##: null"

I tried various try/hack but failed at the end !

**Comment by stephanenicolas** [comment]
There are no aliases in TP, which is the feature you are looking for: #248 . 
You can still create the instance of your singleton manually and bind it twice using `bindToInstance`. 
For now, it's the official workaround.

**Comment by afaucogney** [comment]
Ok now I have a name !
Could you tell us why this is not the normal behavior ?
From a descriptive perspective, I would expect such behavior, don't you ?
Maybe I didn't get the full picture, but defining alias doesn t make the description clearer (even if that would solve the implementation problem)

**Comment by afaucogney** [comment]
@stephanenicolas please have a look on my previous question, because I'm still don't understand why such code doesn't offer the behavior I expect (as mentioned https://github.com/stephanenicolas/toothpick/issues/248#issuecomment-330939778)

It seems I found a viable solution, would that make sens for you ?

Here are the providers:

```
class IFooWriteProvider : Provider<IFooWrite> {

    @Inject
    lateinit var foo: Foo

    override fun get(): IFooWrite {
        return foo
    }
}

class IFooPrintProvider : Provider<IFooPrint> {

    @Inject
    lateinit var foo: Foo

    override fun get(): IFooPrint {
        return foo
    }
}
```

I inject the singleton via TP inside the provider.

And the bindings:

```
        KTP.openScope("ROOT")
            .installModules(object : Module() {
                init {
                    bind(IFooWrite::class.java).toProvider(IFooWriteProvider::class.java)
                }
            })
            .getInstance(IFooWrite::class.java)
            .write(42)


        KTP.openScope("ROOT")
            .openSubScope("SUB")
            .installModules(object : Module() {
                init {
                    bind(IFooPrint::class.java).toProvider(IFooPrintProvider::class.java)
                }
            })
            .getInstance(IFooPrint::class.java)
            .print()
```

This is working well, and ok from my point of view. 
However I thing you had another idea in mind, did you ? (I'm not sure if I understood the workaround)

**Comment by afaucogney** [comment]
Another linked topic. If I add this code (bind(Foo***), the expected behavior does'n work anymore. I had a look on the Factory and MemberInjector, but nothing seems to get changed. Any idea ?

```
     KTP.openScope("ROOT")
            .openSubScope("SUB")
            .installModules(object : Module() {
                init {
                    bind(IFooPrint::class.java).toProvider(IFooPrintProvider::class.java)
                    bind(Foo::class.java).singleton()
                    // bind(Foo::class.java) or this one
                }
            })
            .getInstance(IFooPrint::class.java)
            .print()
```

**Comment by stephanenicolas** [comment]
@afaucogney your workaround is also valid. As long as it works ! :) 
But for your last comment, you should open a new ticket, this is not normal. Please close this one and open a new ticket.

**Comment by dlemures** [comment]
We are looking at ways of make it work out of the box @afaucogney :)
