### ISSUE TITLE
Update ProGuard rules for Toothpick 3.0 and KTP

### ISSUE THREAD

**Issue by zawadz88** [stephanenicolas/toothpick#370]
Hi,
I'm migrating from TP 2.1.0 to TP 3.0 and I've noticed that some ProGuard rules need updating if you're using `@InjectConstructor` and KTP delegates instead of `@Inject`-annotated properties. I didn't find any info about this in the documentation so I'm posting it here.

The following seems to be working for me:
```
-keepnames @toothpick.InjectConstructor class *
-keepclasseswithmembernames class * { toothpick.ktp.delegate.* *; }
-keepclassmembers class * {
    toothpick.ktp.delegate.* *;
}
```
in addition to already defined rules. Note: I'm using that on top of the rules mentioned in #330

**Comment by stephanenicolas** [comment]
Thx Piotr, we should update the wiki with this info.

**Comment by stephanenicolas** [comment]
@zawadz88 can you make a PR on the proguard file that TP passes to downstream projects please ?  I have updated the docs already: https://github.com/stephanenicolas/toothpick/wiki/Proguard-&-TP

**Comment by dimsuz** [comment]
By the way, are there any plans to put proguard rules inside the library jar's resources? Android's new shrinker R8 (now default) supports this, so even clients who do not use smoothie will receive them, no need for manual addition and supporting wiki page. Moshi, okhttp, retrofit use this feature, it's working great.

Maybe I'll create a PR one day, but currently rather busy, so at least keep this in mind, iirc this isn't a complex thing to do.

**Comment by stephanenicolas** [comment]
Thx Piotr, take your time, as we wanna merge also another PR with this one
and release.

But thx for doing it,
 S.

**Comment by stephanenicolas** [comment]
This has been addressed.

**Comment by RumataEstorish** [comment]
When migrating to gradle plugin 7.0 had to add
-keep @javax.inject.Qualifier public class *
to keep qualifiers working
