### ISSUE TITLE
Dependencies of smoothie-lifecycle

### ISSUE THREAD

**Issue by osipxd** [stephanenicolas/toothpick#371]
Hello!
Why `smoothie-lifecycle` depends on `androidx.legacy:legacy-support-v4:1.0.0`? I've not found any usages of it.
And why it depends on `androidx.lifecycle:lifecycle-common-java8` but not on `androidx.lifecycle:lifecycle-common` (wihout java8)?
Same question about `smoothie-lifecycle-viewmodel` module.

**Comment by stephanenicolas** [comment]
You're probably right about the first part of the comment, the dependency on legacy support. We need to check that. 

For the second part, it's the recommended practice for java 8 support : https://developer.android.com/jetpack/androidx/releases/lifecycle

**Comment by osipxd** [comment]
Because of `-java8` I see following error:
```
> Transform artifact lifecycle-common-java8.jar (androidx.lifecycle:lifecycle-common-java8:2.2.0-alpha02) with DexingTransform
AGPBI: {"kind":"error","text":"Default interface methods are only supported starting with Android N (--min-api 24): void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)","sources":[{}],"tool":"D8"}
```
And looks like this specific to Java 8 API (`onCreate`) not used in `smoothie-lifecycle` too. Maybe you can depend on `lifecycle-common`?

As a workaround I've added next lines to build.gradle script:
```groovy


dependencies {
    implementation(deps.toothpick.lifecycle) {
        exclude group: 'androidx.legacy'
    }

    modules {
        module('androidx.lifecycle:lifecycle-common-java8') {
            replacedBy('androidx.lifecycle:lifecycle-common', 'we use min api 19, and can not use java 8')
        }
    }
}
```

**Comment by stephanenicolas** [comment]
Do you feel like doing a PR. Ideally we would also have a way to **test**
that it works both for users using java 8 & 9.

Le jeu. 19 sept. 2019 à 08:28, Osip Fatkullin <notifications@github.com> a
écrit :

**Comment by osipxd** [comment]
Ok, I'll create PR. And try to test it on several java versions.

**Comment by osipxd** [comment]
There is Gradle linter that can automatically detect such cases and fix them. Maybe I'll add it to the project?
https://github.com/nebula-plugins/gradle-lint-plugin

**Comment by osipxd** [comment]
Oh... It not works with `api` and `implementation` configurations https://github.com/nebula-plugins/gradle-lint-plugin/issues/126
