### ISSUE TITLE
Added (useless) binding break the behavior

### ISSUE THREAD

**Issue by afaucogney** [stephanenicolas/toothpick#372]
Another linked topic. If I add this code (bind(Foo***), the expected behavior does'n work anymore. I had a look on the Factory and MemberInjector, but nothing seems to get changed. Any idea ?

```
     KTP.openScope("ROOT")
            .openSubScope("SUB")
            .installModules(object : Module() {
                init {
                    bind(IFooPrint::class.java).toProvider(IFooPrintProvider::class.java)
                    bind(Foo::class.java).singleton()
                    // bind(Foo::class.java) or this one
                }
            })
            .getInstance(IFooPrint::class.java)
            .print()
```

_Originally posted by @afaucogney in https://github.com/stephanenicolas/toothpick/issues/369#issuecomment-532666397_

**Comment by afaucogney** [comment]
Here is the full code:

```
class MyAppApplication : Application() {
    override fun onCreate() {
        super.onCreate()
        KTP.openScope("ROOT")
            .installModules(object : Module() {
                init {
                    bind(IFooWrite::class.java).toProvider(IFooWriteProvider::class.java)
                }
            })
            .getInstance(IFooWrite::class.java)
            .write(42)

        KTP.openScope("ROOT")
            .openSubScope("SUB")
            .installModules(object : Module() {
                init {
                    bind(IFooPrint::class.java).toProvider(IFooPrintProvider::class.java)
                    bind(Foo::class.java)
                }
            })
            .getInstance(IFooPrint::class.java)
            .print()

    }
}

interface IFooWrite {
    fun write(n: Int)
}

interface IFooPrint {
    fun print()
}

@Singleton
class Foo @Inject constructor() : IFooWrite, IFooPrint {
    var number: Int? = null

    override fun write(n: Int) {
        number = n
    }

    override fun print() {
        Log.d("##", number.toString())
    }
}

class IFooWriteProvider : Provider<IFooWrite> {

    @Inject
    lateinit var foo: Foo

    override fun get(): IFooWrite {
        return foo
    }
}

class IFooPrintProvider : Provider<IFooPrint> {

    @Inject
    lateinit var foo: Foo

    override fun get(): IFooPrint {
        return foo
    }
}
```

it prints `null` and should print `42`

**Comment by stephanenicolas** [comment]
But tha's normal, in SUB scope, you override the binding from root that
made Foo a singleton, and you ask it not to be a singleton in the sub scope.
It's a edgy case, but TP seems to be following what you ask for.

Does it make sense to you ?

**Comment by afaucogney** [comment]
In some part yes. 
So I understand that binding in module is prior to annotation ?

However if I use this : 
```
bind(Foo::class.java).singleton()
```

I also get null. Does it mean that singleton() is equal to singletonInScope() ?

**Comment by stephanenicolas** [comment]
Yes, `singleton()` is equal to TP2's `singletonInScope()`.

Normally, bindings and annotation complete each other. They add up basically. 
In the case of @Singleton, there is a contradiction between them:
* @Singleton means your class should have a single instance, and because there is no scope anntation, it should belong to the root scope.
* the binding is defined in a subscope, which means the instance(s depending whether you say `.singleton() or not) belong to the subscope.

So yes, in this very specific example, you will have 2 or more instances of Foo that belong to the 2 different scopes. What configuration are you using ? It seems to me we have a check that should prevent this from happening in debug.

**Comment by stephanenicolas** [comment]
@afaucogney Can we close this issue ?

**Comment by afaucogney** [comment]
For you latest question, I'm not using any specific configuration. The code
you see is the code I ran.

Yes we can close it. I will do it at my next login.
