### ISSUE TITLE
Move the project to Java 8

### ISSUE THREAD

**Issue by osipxd** [stephanenicolas/toothpick#378]
@osipxd after consulting our OSS devs and the other current contributors of TP, we agreed that we want to drop support for java 7 in TP3. We will document the change soon. 
Are you interested in closing this PR, and re-opening a PR with a matching ticket : 1 for the dependency change and one to make sure we enforce java 8 consistently in all modules ?

_Originally posted by @stephanenicolas in https://github.com/stephanenicolas/toothpick/pull/374#issuecomment-535152941_

**Comment by stephanenicolas** [comment]
The issue has been adresed.
