### ISSUE TITLE
by inject() issue

### ISSUE THREAD

**Issue by markchristopherng** [stephanenicolas/toothpick#379]
Hi, 

I have an activity that gets injected by a manager which in turn gets injected with a dao object.
See below for class definitions.

class PayBillActivity() : BaseActivity(R.layout.activity_pay_bill) {

    val payBillManager : IPayBillManager by inject()

    override fun onCreate(savedInstanceState: Bundle?) {
            KTP.openRootScope()
            .openSubScope(AppConsants.APPSCOPE)
            .openSubScope(this)
            .installModules( module {
                   bind<IPayBillDao>().toClass<PayBillDao>()
                   bind<IPayBillManager>().toClass<PayBillManager>()
             })
            .closeOnDestroy(this)
            .inject(this)
    }
}

class PayBillManager : IPayBillManager {
    val payBillDao : IPayBillDao by inject()
}

@InjectConstructor
class PayBillDao : IPayBillDao {
}

When I run the applicaiton it generates a toothpick.locators.NoFactoryFoundException: No factory could be found for class example.di.paybill.PayBillManager

If I changed the line 

from
 val payBillDao : IPayBillDao by inject()
 
to
 @Inject lateinit var payBillDao : IPayBillDao

It works and it generates the factory. Just wondering why the by inject() doesn't generate the factory or am I miss using it somehow? Alternatively, I could pass the dao's object in the manager's constructor which is cleaner.  

I guess I am just trying to understand the difference by @Inject and by inject(). I don't think this is a bug but my lack of knowledge. I am just playing around with TP3 on a sample app we already upgraded our real app to TP3 and its working well.

**Comment by markchristopherng** [comment]
I write an article onTP3 hopefully it is accurate -  https://medium.com/@markchristopherng/toothpick-3-a-hidden-gem-194ae6ee8671

**Comment by dlemures** [comment]
Hi @markchristopherng ,

The behavior you see is the expected one: With KTP, field injection is meant to be used only for the classes where you start your injection (injection root):

```kotlin
MyActivity {

**Comment by dlemures** [comment]
Regarding the article:

![thank you](https://media.giphy.com/media/IcGkqdUmYLFGE/giphy.gif)

Great job and thank you!

Just one comment: the way you are using`openRootScope` is 100% valid, but it does not provide any value. That method is meant to be used for 2 scenarios:

1. You have a single scope and dont wanna deal with names
2. reopen the root scope (`AppConsants.APPSCOPE` in your case) without having to use its name.

Your code could be simplified to use:

```kotlin
 KTP.openRootScope() (you can install modules here too)
        .openSubScope(this)
        ...
```

or 

```kotlin
 KTP.openScope(AppConsants.APPSCOPE)
        .openSubScope(this)
        ...
```

and again: great one 🥳

**Comment by markchristopherng** [comment]
glad you liked the article, thanks again for your effort on this library.

we thought that by inject() could only be used when .inject(this) is called, not sure if the documentation needs to make it clearer or not.

btw.
I have 1 other article in draft that mentions TP3 and DH3. which I am going to release in November when I do my conference talk in Melbourne on modularization. 
https://medium.com/@markchristopherng/the-gritty-truth-about-app-modularisation-part-2-de2ff89bf504


, I actually have

**Comment by dlemures** [comment]
> we thought that by inject() could only be used when .inject(this) is called, not sure if the documentation needs to make it clearer or not.

Not sure i understand what that means. Could you explain a little more?

**Comment by markchristopherng** [comment]
I meant that by inject() can only be used when you start the injection by calling .inject(this)

**Comment by dlemures** [comment]
Yeah, what you are saying it is the way it works (it is equivalent to using `@Inject`).

```kotlin
MyActivity {
   val myDependency : MyDependency by inject()
...
   onCreate {
      KTP.openRootScope()
         .inject(this)
   }
...
}

**Comment by markchristopherng** [comment]
@dlemures @stephanenicolas my article made it to https://androidweekly.net/

**Comment by stephanenicolas** [comment]
Thanks Mark for the article.

I couldn't comment in the article from my phone, so I do it here:
* We recommend the root scope and the app scope to be the same.
* You can use a constant for the app scope but we recommend using the app
instance.
* It would be nice to see a test as you mention it is a strength of TP.
* I would recommend to use `code` for all reference to code in your
article. It would be easier to read.
* It's sad we can't comment to answer the first response.

**Comment by stephanenicolas** [comment]
I added your article to TP's Readme. Thx again.

S.

**Comment by markchristopherng** [comment]
Thanks. 

I'll add those recommendations and the one about the activity scope to the end of the article in the next couple of hours. The app scope is a legacy from our main app's implementation. When i was putting the example together i was wondering if I needed a root and app scope as well they are pretty much the same thing.

I thought about testing  but i wanted to just focus on one thing and the article was getting pretty long. I think testing would be a good article by itself maybe a future article.
