### ISSUE TITLE
Smoothie's "viewmodel" package does not exist

### ISSUE THREAD

**Issue by ZangievM** [stephanenicolas/toothpick#395]
Hi! I try to use Smoothie's "viewmodel" helpers. But I can't do it, because it not exist.
![image](https://user-images.githubusercontent.com/18612980/73381100-3fdb6980-42d6-11ea-8e3a-67f7cee9a8a9.png)

build.gradle:

```
implementation 'com.github.stephanenicolas.toothpick:ktp:3.1.0'
    kapt 'com.github.stephanenicolas.toothpick:toothpick-compiler:3.1.0'
    implementation 'com.github.stephanenicolas.toothpick:smoothie-androidx:3.1.0'
```

**Comment by dlemures** [comment]
For the viewmodel integration, you need the following artifact:

`implementation 'com.github.stephanenicolas.toothpick:smoothie-lifecycle-viewmodel-ktp:X.Y.Z`

**Comment by ZangievM** [comment]
Thank you!
