### ISSUE TITLE
Module's extra dependency to Toothpick

### ISSUE THREAD

**Issue by morder** [stephanenicolas/toothpick#396]
For example, we have two modules - App, Feature
The Feature is a java(kotlin) module, without any extra dependencies
Next, I create some class with @Inject annotation inside the Feature module. So, I need to add `javax.inject:javax.inject:1` dependency.
But I cannot use this class with toothpick's `kapt`, because toothpick requires generated factory.

So, I cannot create a general module without DI dependency :(

**Comment by dlemures** [comment]
Hey @morder !

Toothpick generates some code at compile time to make everything work under the hood. In order for that to work, you'd need to add these 2 dependencies to your `Feature module`:

```
implementation 'com.github.stephanenicolas.toothpick:ktp:3.x' // This one includes javax.inject
kapt 'com.github.stephanenicolas.toothpick:toothpick-compiler:3.x'
```

Without those 2 dependencies, you will not be able to inject any class inside that feature module. Toothpick cannot do its magic 😞

Is there are reason why you don't want to depend on Toothpick on your `feature module`?

**Comment by morder** [comment]
@dlemures Thank for your answer.
I want to be able to use this module is other projects, and other projects can use for example dagger or any other DI.

**Comment by afaucogney** [comment]
@morder can't you add those extra dependencies from the root build.gradle file with something like this:

```
project(':myKTPLessModule') {
  apply plugin: 'kotlin-kapt'

  dependencies {
    implementation 'com.github.stephanenicolas.toothpick:ktp:3.x'
    kapt 'com.github.stephanenicolas.toothpick:toothpick-compiler:3.x'

    //highly recommended
    testImplementation 'com.github.stephanenicolas.toothpick:toothpick-testing-junit5:3.x'
    testImplementation 'mockito or easymock'
  }
}
```

**Comment by dlemures** [comment]
@morder did it work?

**Comment by morder** [comment]
Yes, it's working. Thank you!

**Comment by dlemures** [comment]
awesome!
