### ISSUE TITLE
new article comparing the different DI frameworks

### ISSUE THREAD

**Issue by markchristopherng** [stephanenicolas/toothpick#397]
I written a new article comparing Koin, Kodein, Dagger and Toothpick in detail plus it includes testing. Let me know what you think?

https://medium.com/@markchristopherng/a-dependency-injection-showdown-213339c76515

**Comment by afaucogney** [comment]
The article is cool, and give a good overview about way to do DI today in
Android. Your article is based on a simple project, and so clearly (and
subjectively) KTP is the winner on that field.
However, I would also point that when required, you can handle very deep
and precise scope management with KTP, and you can get this with just a
small piece of work.

**Comment by afaucogney** [comment]
I would like to add some comment :
- In your table, why did you said that Dagger is not compatible with the
JVM ?

Then you show some aspect about Ktor compatibility. What is the use case,
why this feature make sens, or would be nice for a DI framework ?

**Comment by stephanenicolas** [comment]
Thank you for this article. Of course as a toothpick co-author, I am glad
you liked it and that it did well in comparison of other frameworks.

I was really impressed that you spent the time to try them all and give
each DI lib a honest chance to shine.

**Comment by markchristopherng** [comment]
Glad you liked the article. It just got published to https://proandroiddev.com/

I think having a simple example and working code is valuable to get people up and running quickly. I also wanted to back up what I had said in my previous article with some hard evidence.

I got some feedback about the Dagger example that it wasn't using some of the new annotations. Just dong this simple example on Dagger reminded me how complicated it is.

**Comment by markchristopherng** [comment]
Hi @stephanenicolas are you able to add this article as link on your README.md
I think it could be very helpful to new starters.

**Comment by dlemures** [comment]
Thx so much for the article @markchristopherng and congrats for getting it on AndroidWeekly!

Just added it to the README

**Comment by markchristopherng** [comment]
@dlemures The article is a small thing compared to your hard work in creating and maintaining Toothpick. Its been a very popular article with 10K views. I also got lots of feedback from angry Dagger uses.

Maybe you can respond to this person
https://medium.com/@pahakorolev/you-wrote-abouttoothpick-5fd9257302f2
