### ISSUE TITLE
No factory could be found

### ISSUE THREAD

**Issue by vovaksenov99** [stephanenicolas/toothpick#401]
Proguard from here doesn't work for me
https://github.com/stephanenicolas/toothpick/wiki/Proguard-&-TP#tp-3

` Caused by: toothpick.locators.NoFactoryFoundException: No factory could be found for class f.a.c.a.s.a. Check that the class has either a @Inject annotated constructor or contains @Inject annotated members.`

But proguard from this PR is fine
https://github.com/stephanenicolas/toothpick/pull/376

Is this a mistake in wiki and I need proguard from PR?

I use the latest Toothpick version

**Comment by dlemures** [comment]
Hi @vovaksenov99 ,

Did you fix the issue? Could you update thee ticket with more details?

**Comment by vovaksenov99** [comment]
Yes. I did.

I used that proguard preferences.

```
-keepnames @toothpick.InjectConstructor class *
-keepclasseswithmembernames class * { @javax.inject.Inject <init>(...); }
-keep class javax.inject.**
-keep class javax.annotation.**
-keep class **__Factory { *; }
-keep class toothpick.** { *; }
```
