### ISSUE TITLE
java.lang.AbstractMethodError in release build using Smoothie-lifecycle

### ISSUE THREAD

**Issue by arcmaksim** [stephanenicolas/toothpick#402]
I'm using Kotlin (1.3.72), Smoothie-lifecycle (3.1.0), and AndroidX lifecycle (2.2.0) for a fairly small project. After switching build variant to the "release" I encountered exception:

> java.lang.AbstractMethodError: abstract method "void androidx.lifecycle.DefaultLifecycleObserver.onCreate(androidx.lifecycle.LifecycleOwner)"

After a quick search, I found only one case of implementing `DefaultLifecycleObserver` interface - `toothpick.smoothie.lifecycle.LifecycleUtil.closeOnDestroy(LifecycleOwner, Scope)`. After implementing missing methods of `DefaultLifecycleObserver` with empty bodies the issue was resolved.

**Comment by dlemures** [comment]
Hi @arcmaksim ,

Are you using Java 7 or 8 in your project? It might be the reason why you need all methods in `DefaultLifecycleObserver` to be implemented.

As https://github.com/stephanenicolas/toothpick/issues/378, we decided to support Java 8. `DefaultLifecycleObserver` only works from Java 8 https://developer.android.com/reference/androidx/lifecycle/DefaultLifecycleObserver

Please check https://developer.android.com/jetpack/androidx/releases/lifecycle#declaring_dependencies

Does it work if you change it to use the Java 8 of the `androidx lifecycle` dependency?

Btw, sorry for the delay

**Comment by arcmaksim** [comment]
Hi.
I'm using Java 8 of the AndroidX lifecycle dependency and my source and target compatibility are set to Java 8.

```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}

kotlinOptions {
    jvmTarget = "1.8"
}
```

But I couldn't reproduce this behavior on a clean project (with minimal setup). I guess this is related to my overall setup.
I'll try to find out why is my project doesn't work and report it later.

**Comment by dlemures** [comment]
Yes, that's strange. Really appreciate if you report here in case someone encounters the same issue.

**Comment by tim4dev** [comment]
See the answer here https://stackoverflow.com/a/60873211/345810

**Comment by NguyenKhue09** [comment]
Change minSdkVersion to 24. You can see the answer here: https://developer.android.com/jetpack/androidx/releases/compose-runtime
