### ISSUE TITLE
toothpick-sample module is missing from settings.gradle

### ISSUE THREAD

**Issue by ziem** [stephanenicolas/toothpick#411]
Hi,
In https://github.com/stephanenicolas/toothpick/commit/056229f60f22ae790b5a464e7eac82662ebe3b69#diff-88b7c47e47b8ee65263b6784b86fa0a7L7 `toothpick-sample` module was removed from the `settings.gradle` file. I'm wondering if this change was intentional? Without it, when you import the whole toothpick project using Android Studio, the `toothpick-sample` module is not added to the build, and thus the app configuration for the sample is not created.

**Comment by dlemures** [comment]
Hi @ziem ,

`toothpick-sample` is a composite build, that's why we removed it from there. In order to run the sample, open the module `toothpick-sample` as a separate project, that should work. 

If it doesnt work, feel free to reopen the issue.

Thx!
