### ISSUE TITLE
HILT support

### ISSUE THREAD

**Issue by kingargyle** [stephanenicolas/toothpick#413]
I know this we just announced by Google, and is a wrapper to Dagger2 to make it easier to use (why does google always need a wrapper for their stuff).  Anyways, if there is a way to tie in Toothpick to Hilt, is this something that is of interest to the project?

See: https://developer.android.com/training/dependency-injection/hilt-jetpack

**Comment by dlemures** [comment]
Hey @kingargyle ,

What kind of integration? Dagger2 and TP are 2 different DI libraries, each of them with different 
design principles. Could you provide more info about what you would expect from that integration?

**Comment by kingargyle** [comment]
Basically, looking for using the Interfaces, Annotations defined in the androidx.hilt packages but have Toothpick be used underneath the covers instead of using Dagger 2.  Code generation could generate the necessary Toothpick pieces, and the Application could leverage the androidx.hilt components and annotations.

Again not sure how reasonable or do able this would be.

**Comment by dlemures** [comment]
Ok, I understand your question. That would not be possible as we have a different API / code generation strategy. 

But I'm curious, why would you want to use the Hilt API? Anything you are missing?

**Comment by kingargyle** [comment]
Just a standardization on a common Injection mechanism regardless of platform.  Unfortunately it doesn't look like Google took HILT far enough to make it work at an Interface level so that you guys could inject and build what you would need for your own library.

We plan to still migrate off Dagger 1 to Toothpick but I'll have to do some convincing now that HILT is the new shiny apple to some devs.

**Comment by dlemures** [comment]
Yeah, I agree that Google making HILT "the way to do DI on Android" has a big impact. Nevertheless, a few things that could help you:

1. HILT is easy for the most basic use cases, once you add some extra customizations or wanna go with common and recommended patterns as modularization, [it does not look that easy](https://developer.android.com/training/dependency-injection/hilt-multi-module). Simplicity is one of the pillars of Toothpick.
2. HILT 💔 Kotlin.
3. HILT is alpha.
4. Toothpick provides all what you might need and will keep getting better 😜

Let me know if you need some more help.
