### ISSUE TITLE
ViewModel KTP issue: Fatal Exception: java.lang.IllegalStateException: The dependency has not be injected yet 

### ISSUE THREAD

**Issue by ZangievM** [stephanenicolas/toothpick#415]
Hello! I faced an issue and can not understand, why it's happens.

I have a ViewModel:

```kotlin
class AddVehicleViewModel : ViewModel() {
	val repository: VehiclesRepository by inject()
        val settingsInteractor: SettingsInteractor by inject()
        private val manufacturersLiveData: MutableLiveData<Resource<List<ManufacturerData>>> = MutableLiveData()
        fun getManufacturers(): LiveData<Resource<List<ManufacturerData>>> = manufacturersLiveData
        private val profileLiveData: MutableLiveData<Triple<String?, String?, String?>> = MutableLiveData()
        fun getProfileLiveData(): LiveData<Triple<String?, String?, String?>> = profileLiveData
        

        fun loadManufacturers() {
		manufacturersLiveData.postValue(Loading())
		disposables.add(
				repository.getManufacturers()
						.subscribe({ list ->
							manufacturersLiveData.postValue(Success(list))
						}, {
							manufacturersLiveData.postValue(Error(it))
						})
		)
	}
        fun getProfile() {
		profileLiveData.postValue(Triple(settingsInteractor.getFirstName(),
				settingsInteractor.getLastName(),
				settingsInteractor.getAvatarPath()))
	}

}
```

And also I have parent Fragment something like this:

``` kotlin
class AddVehicleFragment : Fragment() {
val viewModel: AddVehicleViewModel by inject()

override fun onActivityCreated(savedInstanceState: Bundle?) {
		super.onActivityCreated(savedInstanceState)
		val scope = KTP.openScopes(DI.SESSION_SCOPE)
				.openSubScope(DI.ADD_VEHICLES_SCOPE)
		scope.installViewModelBinding<AddVehicleViewModel>(this)
				.closeOnViewModelCleared(this)
		scope.inject(this)
                observeProfile()
}
private fun observeProfile() {
                // THIS WORKS FINE!
		viewModel.getProfile()
		viewModel.getProfileLiveData().removeObservers(viewLifecycleOwner)
		viewModel.getProfileLiveData().observe(viewLifecycleOwner, Observer {
			if (it.first == null) viewModel.getProfile()
			else
				bindUser(it.first, it.second, it.third)
		})
	}
}
```

And inside this fragment I have nested dialog fragment. And use this ViewModel by this standard way:
``` kotlin
class ItemsBottomFragment : BottomSheetDialogFragment() {
private lateinit var viewModel: AddVehicleViewModel
override fun onActivityCreated(savedInstanceState: Bundle?) {
		super.onActivityCreated(savedInstanceState)
		viewModel = ViewModelProvider(parentFragment!!)[AddVehicleViewModel::class.java]
                observeManufacturers()
	}
private fun observeManufacturers() {
                // THIS THROWS AN EXCEPTION!
		viewModel.loadManufacturers()
		viewModel.getManufacturers().removeObservers(viewLifecycleOwner)
		viewModel.getManufacturers().observe(viewLifecycleOwner, Observer { resource ->
			when (resource) {
				is Success -> {
					itemsRV.visibility = View.VISIBLE
					progress.visibility = View.GONE
					error_layout.visibility = View.GONE
					manufacturersAdapter!!.setItems(resource.data!!)
				}
				is Loading -> {
					itemsRV.visibility = View.INVISIBLE
					progress.visibility = View.VISIBLE
					error_layout.visibility = View.GONE
				}
				is Error -> {
					itemsRV.visibility = View.INVISIBLE
					progress.visibility = View.GONE
					error_layout.visibility = View.VISIBLE
				}
			}
		})
	}
}
```
And the problem is:
When I call `viewModel.loadManufacturers()` in the nested fragment it throws an Exception: `Fatal Exception: java.lang.IllegalStateException: The dependency has not be injected yet`  on the `repository` property of the AddVehicleViewModel (`val repository: VehiclesRepository by inject()`)

But when I call `viewModel.getProfile()` that uses injected field `settingInteractor` (`val settingsInteractor: SettingsInteractor by inject()`) in the parent fragment is working!

I am not understand what is the reason. Thank you!

**Comment by dlemures** [comment]
Hey @ZangievM !

Could you confirm in which order they are called? Is it possible that `ItemsBottomFragment.onActivityCreated` is called before `AddVehicleFragment. onActivityCreated`? That would explain the problem:

1. `ItemsBottomFragment.onActivityCreated` is called and it's the first getting the instance of `AddVehicleViewModel` and therefore creating it. At this stage TP has not even install the binding for the ViewModel.
2. `AddVehicleFragment. onActivityCreated` is called and then Toothpick using `ViewModelProvider` internally (the same mechanism used inside `ItemsBottomFragment`) gets the same ViewModel that was already created on `ItemsBottomFragment.onActivityCreated`. But this time, Toothpick injects the ViewModel dependencies.

If that is the case, you are trying to use the dependencies for the ViewModel at `1`, but at that stage TP has not even run. 

One of the solutions would be to use TP to inject the ViewModel in the nested fragment as well:

```kotlin
installViewModelBinding<AddVehicleViewModel>(parentFragment!!)
```

Keep us updated 😃

**Comment by ZangievM** [comment]
Hi, @dlemures ! 
`AddVehicleFragment.onActivityCreated` is called first. After that User should press the button on this fragment and after that appears `ItemsBottomFragment` (and correspondingly `ItemsBottomFragment.onActivityCreated` is called). 
Unfortunately, I still can't reproduce this situation. I just got crash report and after that began to understand the situation (: 
I will try your solution. Thank you very much!

**Comment by dlemures** [comment]
Sure, no problem. The solution I gave you should work nevertheless.

Regarding the issue, there must a use case on some specific configuration (device/OS) that changes the order. For instance, configuration change when the dialog is open maybe?

Closing the issue.
