### ISSUE TITLE
Better examples in the wiki

### ISSUE THREAD

**Issue by Macarse** [stephanenicolas/toothpick#66]
https://github.com/stephanenicolas/toothpick/wiki/Scopes#scopes-instances-creation-and-injections

Foo class? setQurtz()? 

Plz use something more "real" and use it everywhere in the docs.

**Comment by stephanenicolas** [comment]
I am not sure with this one. TP docs go further that what a simple example can do. I prefer small examples focused on a feature of TP. But show me I am wrong, I would be happy to merge a PR for a better wiki.
