### ISSUE TITLE
Binding explanation sucks

### ISSUE THREAD

**Issue by Macarse** [stephanenicolas/toothpick#67]
At https://github.com/stephanenicolas/toothpick/wiki/Scopes#scopes-instances-creation-and-injections

```
a binding : is way to express that a class Foo is associated to an implementation Bar, which we denote Foo --> Bar. It means that writing @Inject Foo a; will return a Bar.
```

First time I read I was trying to associate with the Bar in the first example. After the second time I read it I noticed they have nothing to do. What about:

a binding : is way to express that a class `Class` is associated to an instance `Instance`, which we denote `Class` --> `Instance`. It means that writing @Inject Class a; will return an `Instance`.

or use an example with a real life scenario.

**Comment by stephanenicolas** [comment]
lol. Ok, but actually your example would be terrible `Instance` with upper case ...booh.. I wouldn't know what that would mean. 

It should `IFoo --> Foo`, as simple as that.

**Comment by stephanenicolas** [comment]
Is it better now @Macarse ?

**Comment by Macarse** [comment]
@stephanenicolas much better and less confusing. This weekend I will give a full second pass.
