### ISSUE TITLE
Example of optimistic Factory

### ISSUE THREAD

**Issue by Macarse** [stephanenicolas/toothpick#69]
In https://github.com/stephanenicolas/toothpick/wiki/Factories-and-Member-Injectors there is a nice example of the Factory TP creates:

```
//a simplified Factory
public final class Foo$$Factory implements Factory<Foo> {
  @Override
  public Foo createInstance() {
    return new Foo();
  }
}
```

but there is no example of what an optimistic Factory might look like. I wanted to see that while reading.

**Comment by stephanenicolas** [comment]
This has to be made more clear then. An optimistic factory doesn't exist, there are just plain normal factories but we create them optimistically. We create "more factories" that what is exactly needed, as we assume most bindings are `X --> X`, which is actually the most common case.

**Comment by stephanenicolas** [comment]
What do you think of the new explanation: https://github.com/stephanenicolas/toothpick/wiki/Factories-and-Member-Injectors
