### ISSUE TITLE
MemberInjector explanation is broken

### ISSUE THREAD

**Issue by Macarse** [stephanenicolas/toothpick#70]
or it doesn't make sense to me.

https://github.com/stephanenicolas/toothpick/wiki/Factories-and-Member-Injectors

For 
```
public class Foo {
  @Inject void m(Bar bar) {...}
}
```

Shouldn't the code be:

```
//a Member Injector
public final class Foo$$MemberInjector implements  MemberInjector<Foo> {
  @Override
  public void inject(Foo foo, Scope s) {
    Bar bar = s.getInstance(Bar.class);
    foo.m(bar);
  }
}
```

Your variable names and examples still suck. <3

**Comment by stephanenicolas** [comment]
Thx !

**Comment by Macarse** [comment]
It is still wrong.
you are not getting the instance from the scope.
