### ISSUE TITLE
What is Qurtz?

### ISSUE THREAD

**Issue by Macarse** [stephanenicolas/toothpick#71]
@stephanenicolas wtf

**Comment by stephanenicolas** [comment]
http://www.computer-dictionary-online.org/?q=metasyntactic%20variable @Macarse 
I usually use `qurtz` as a third metasymbolic variable name after `foo` & `bar`. We can change to `baz` or `quux` ...

**Comment by stephanenicolas** [comment]
@Macarse Do you prefer `Quux`  ? `Baz` Seems to bring confusion with `Bar`. 
:) 

Please close if you can't suggest something that would make you happy and would make sense for most devs. :)
