### ISSUE TITLE
Field masking

### ISSUE THREAD

**Issue by Macarse** [stephanenicolas/toothpick#72]
Interesting!
https://github.com/stephanenicolas/toothpick/wiki/Factories-and-Member-Injectors

Is it just a performance issue or things might be broken?
Is there a way to detect and log a warning?

**Comment by Macarse** [comment]
I was discussing with @dlemures in chat and we reached to the conclusion that it would not break.

```
public class A {
    String a;

    public static class B extends A {
        int a;

    }

    protected void test() {
        B b = new B();
        ((A) b).a = "hi";
        System.out.println("B.a " + b.a);
        System.out.println("B.a casted" + ((A) b).a);
    }

    public static void main(String[] args) {
      B b = new B();
      b.test();
    }
}
```

MemberInjectors will have the instance casted so there would not be a problem.

Not sure about the possibility of detection. I would guess it's impossible without adding more logic to the annotation processor.

**Comment by stephanenicolas** [comment]
I don't think this work, I got quite a few things to do today, @dlemures , please add a test in the code base. Whatever the result is. But no, casting is not enough, casting doesn't transform objects.

**Comment by stephanenicolas** [comment]
@Macarse please review and close. Thx !

**Comment by dlemures** [comment]
Hey didn't see the comment! Thx for the PR
