### ISSUE TITLE
System service provider constructor has no @Inject annotation 

### ISSUE THREAD

**Issue by Zhuinden** [stephanenicolas/toothpick#88]
Is this a bug?  I am just skimming through the code.

**Comment by stephanenicolas** [comment]
We actually prefer to instantiate these components manually for performance
reason. But the gain is probably limited.
If you prefer to instantiate them via TP, it can make sense.
Do you wanna submit a PR ?

S.

2016-05-30 23:51 GMT-07:00 Zhuinden <notifications@github.com>:

**Comment by stephanenicolas** [comment]
Maybe I didn't get your question right. Does this help :
https://github.com/stephanenicolas/toothpick/blob/master/smoothie/src/main/java/toothpick/smoothie/module/ApplicationModule.java

?

2016-05-30 23:57 GMT-07:00 Stéphane NICOLAS <steff.nicolas@gmail.com>:

**Comment by Zhuinden** [comment]
I'm referring to this one

https://github.com/stephanenicolas/toothpick/blob/master/smoothie/src/main/java/toothpick/smoothie/provider/SystemServiceProvider.java

**Comment by dlemures** [comment]
Hi @Zhuinden ,

Providers are used by Toothpick to specify a custom dependency injection behavior.
These are set through bindings, for instance:

```java
bind(A.class).toProvider(AProvider.class); // 1
bind(A.class).toProvider(new AProvider()); // 2
```

The **first one** simply specifies the class of the provider, so Toothpick(TP) needs to create an instance of it before being able to use it. For that TP uses a [Factory](https://github.com/stephanenicolas/toothpick/wiki/Factories-and-Member-Injectors#factories), so `@Inject` is needed (there are some exceptions). More info about that in the link...

The **second case** is slightly different, we are providing an instance of the provider. So TP does not needed to create an instance -> no factory needed -> no `@Inject` needed.

We can only use the second approach for `SystemServiceProvider`, as we need to specify the `service name` manually: https://github.com/stephanenicolas/toothpick/blob/master/smoothie/src/main/java/toothpick/smoothie/module/ApplicationModule.java#L102

**Comment by Zhuinden** [comment]
Ah, I see. No problem here then.
