### ISSUE TITLE
Enhancement - Use annotations to bypass bind method

### ISSUE THREAD

**Issue by keithsmyth** [stephanenicolas/toothpick#91]
Using the `bind` method is a good way of saying this `class` implements this `interface` for this `scope`.

My suggestion though is to allow developers to use an annotation on the concrete class instead of the bind method if they like, e.g.:
```
@Implements(scope="scope_name")
public class SomeClass {}
```

Advantages is that it is easier to find, as `bind` can be anywhere in the code, but with the annotation you know exactly where to find it.

Disadvantage is that it is very static (compile time), might be hard to read if it implements for multiple different scopes

**Comment by stephanenicolas** [comment]
There are multiple concerns with this approach:

* the implements annotation is not part of JSR 330, we try to stick to it
* the `scope = scope_name` can only work for staticly named scopes whereas most of the scopes in TP have dynamic names (usually an object with a life cycle)
* how would TP decide if multiple implementations are provided ?
* scanning annotations is costly, it would require generating code to issue the binding statement indeed, which would add to the complexity of TP

**Comment by keithsmyth** [comment]
Thanks for the feedback, twas only a suggestion and it sounds like it's not going to gel well with the current status of the library. I'll close :)
